CREATE TABLE XXDBL.XXDBL_OM_SMS_DATA_UPLOAD_STG
(
  SMS_ID                  NUMBER                NOT NULL,
  CREATION_DATE           DATE,
  ORG_ID                  NUMBER,
  SMS_TYPE                VARCHAR2(20 BYTE),
  CUSTOMER_NUMBER         VARCHAR2(10 BYTE),
  CUSTOMER_NAME           VARCHAR2(50 BYTE),
  BOOKED_DATE             DATE,
  ORD_HEADER_ID           NUMBER,
  ORDER_NUMBER            NUMBER,
  ORDERED_QUANTITY        NUMBER,
  ORDERED_SEC_QUANTITY    NUMBER,
  UOM_CODE                VARCHAR2(10 BYTE),
  AMOUNT                  NUMBER,
  PHONE_NUMBER            VARCHAR2(40 BYTE),
  SR_PHONE_NUMBER         VARCHAR2(40 BYTE),
  DELIVERY_ID             NUMBER,
  DELIVERY_CHALLAN_NO     VARCHAR2(240 BYTE),
  PRIMARY_QUANTITY        NUMBER,
  SECONDARY_QUANTITY      NUMBER,
  DRIVER_NAME             VARCHAR2(150 BYTE),
  DRIVER_CONTACT_NO       VARCHAR2(150 BYTE),
  VEHICLE_NO              VARCHAR2(150 BYTE),
  CONFIRM_DATE            DATE,
  TRANSPORTER_CHALLAN_NO  VARCHAR2(240 BYTE),
  MESSAGE_TEXT            VARCHAR2(240 BYTE),
  SENT_FLAG               VARCHAR2(3 BYTE),
  DELIVERED_FLAG          VARCHAR2(3 BYTE)
)
TABLESPACE XXDBL_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;

 


CREATE UNIQUE INDEX XXDBL.IDX_OM_SMS_DATA ON XXDBL.XXDBL_OM_SMS_DATA_UPLOAD_STG
(SMS_ID)
LOGGING
TABLESPACE XXDBL_TS_TX_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

 

ALTER TABLE XXDBL.XXDBL_OM_SMS_DATA_UPLOAD_STG ADD (
  CONSTRAINT IDX_OM_SMS_DATA
  PRIMARY KEY
  (SMS_ID)
  USING INDEX XXDBL.IDX_OM_SMS_DATA
  ENABLE VALIDATE);