/* Formatted on 11/9/2020 9:34:02 AM (QP5 v5.287) */
CREATE TABLE XXDBL.XXDBL_IOU_REQ_DTL
(
   IOU_REQ_ID           NUMBER NOT NULL,
   IOU_NUMBER           VARCHAR2 (100 BYTE),
   IOU_DATE             DATE,
   LEGAL_ENTITY_ID      NUMBER,
   LEGAL_ENTITY         VARCHAR2 (240),
   OPERATING_UNIT       NUMBER,
   OU_NAME              VARCHAR2 (240 BYTE),
   LOCATION_ID          NUMBER,
   LOCATION_NAME        VARCHAR2 (500 BYTE),
   EMPLOYEE_NO          VARCHAR2 (100 BYTE),
   ADVANCE_AMOUNT       NUMBER,
   REASON_FOR_ADVANCE   VARCHAR2 (500 BYTE),
   RETURN_DAYS          NUMBER,
   STATUS               VARCHAR2 (50 BYTE),
   CREATED_BY           NUMBER,
   CREATION_DATE        DATE,
   LAST_UPDATE_LOGIN    NUMBER,
   LAST_UPDATED_BY      NUMBER,
   LAST_UPDATE_DATE     DATE,
   APPROVED_BY          VARCHAR2 (100 BYTE),
   PAYMENT_AMOUNT       NUMBER,
   PAYMENT_DATE         DATE,
   PAID_BY              VARCHAR2 (100 BYTE),
   BILL_AMOUNT          NUMBER,
   ADJUST_AMOUNT        NUMBER,
   ADJUST_DATE          DATE,
   ADJUSTED_BY          VARCHAR2 (100 BYTE),
   CONSTRAINT IOU_REQ_PK PRIMARY KEY (IOU_REQ_ID)
);



DROP SYNONYM XXDBL.XXDBL_IOU_REQ_DTL;

CREATE OR REPLACE SYNONYM APPS.XXDBL_IOU_REQ_DTL FOR XXDBL.XXDBL_IOU_REQ_DTL;

CREATE OR REPLACE SYNONYM APPSRO.XXDBL_IOU_REQ_DTL FOR XXDBL.XXDBL_IOU_REQ_DTL;

GRANT ALTER,
      DELETE,
      INDEX,
      INSERT,
      REFERENCES,
      SELECT,
      UPDATE,
      ON COMMIT REFRESH,
      QUERY REWRITE,
      READ,
      DEBUG,
      FLASHBACK
   ON XXDBL.XXDBL_IOU_REQ_DTL
   TO APPS
   WITH GRANT OPTION;

GRANT INSERT, SELECT, UPDATE ON XXDBL.XXDBL_IOU_REQ_DTL TO APPSDBL;

GRANT SELECT ON XXDBL.XXDBL_IOU_REQ_DTL TO APPSRO;


ALTER TABLE XXDBL.XXDBL_IOU_REQ_DTL
   ADD (LEGAL_ENTITY VARCHAR2 (240));

DROP SYNONYM APPS.XXDBL_IOU_REQ_DTL;


DROP SYNONYM APPSRO.XXDBL_IOU_REQ_DTL;

ALTER TABLE XXDBL.XXDBL_IOU_REQ_DTL
   ADD (BILL_AMOUNT NUMBER);


ALTER TABLE XXDBL.XXDBL_IOU_REQ_DTL
   ADD (APPROVED_BY VARCHAR2 (100 BYTE));

ALTER TABLE XXDBL.XXDBL_IOU_REQ_DTL
   DROP COLUMN LC_RCV_DATE;

ALTER TABLE XXDBL.XXDBL_IOU_REQ_DTL
   ADD (FIRST_APPROVER VARCHAR2 (100 BYTE),
        SECOND_APPROVER VARCHAR2 (100 BYTE));

ALTER TABLE XXDBL.XXDBL_IOU_REQ_DTL
   ADD (APPROVED_DATE DATE);


ALTER TABLE XXDBL.XXDBL_IOU_REQ_DTL
   ADD (FINAL_APPROVER VARCHAR2 (100 BYTE),
        FINAL_APPROVED_DATE DATE,
        FINAL_APPROVE VARCHAR2 (50 BYTE));

ALTER TABLE XXDBL.XXDBL_IOU_REQ_DTL
   ADD (FST_APPROVER_NAME VARCHAR2 (500 BYTE),
        SND_APPROVER_NAME VARCHAR2 (500 BYTE));
        
ALTER TABLE XXDBL.XXDBL_IOU_REQ_DTL
   ADD (EMPLOYEE_NAME VARCHAR2 (500 BYTE));

ALTER TABLE XXDBL.XXDBL_IOU_REQ_DTL
   ADD (REJECTED_BY VARCHAR2 (100 BYTE),
        REJECTED_DATE DATE);

ALTER TABLE XXDBL.XXDBL_IOU_REQ_DTL
   ADD (REJECT_REASON VARCHAR2 (500 BYTE));

SELECT * FROM XXDBL.XXDBL_IOU_REQ_DTL;


ALTER TABLE XXDBL.XXDBL_IOU_REQ_DTL
   DROP COLUMN PAYMENT_AMOUNT;
   
ALTER TABLE XXDBL.XXDBL_IOU_REQ_DTL
   DROP COLUMN FINAL_APPROVE;