/* Formatted on 9/19/2020 3:04:11 PM (QP5 v5.287) */
SELECT UNIT_NAME OU_NAME, LEGAL_ENTITY_NAME LEGAL_ENTITY
  FROM XXDBL_COMPANY_LE_MAPPING_V OU;
  
  SELECT ORG_ID OPERATING_UNIT,UNIT_NAME OU_NAME, LEGAL_ENTITY_ID, LEGAL_ENTITY_NAME LEGAL_ENTITY,HLA.LOCATION_ID,HLA.ADDRESS_LINE_1
       || DECODE (HLA.ADDRESS_LINE_2, NULL, ' ', ' , ')
       || DECODE (HLA.ADDRESS_LINE_3, NULL, ' ', ' , ')
          LOCATION_NAME
  FROM
  HR_ALL_ORGANIZATION_UNITS AOU,
  APPS.HR_LOCATIONS_ALL HLA,
  XXDBL_COMPANY_LE_MAPPING_V OU
  WHERE AOU.LOCATION_ID=HLA.LOCATION_ID
  AND AOU.ORGANIZATION_ID=OU.ORG_ID
  ;
  
  SELECT ORG_ID OPERATING_UNIT,UNIT_NAME OU_NAME,LEGAL_ENTITY_ID, LEGAL_ENTITY_NAME LEGAL_ENTITY,HLA.ADDRESS_LINE_1
       || DECODE (HLA.ADDRESS_LINE_2, NULL, ' ', ' , ')
       || DECODE (HLA.ADDRESS_LINE_3, NULL, ' ', ' , ')
          LOCATION_NAME
          --,OU.*
          ,HLA.*
  FROM
  HR_ALL_ORGANIZATION_UNITS AOU,
  APPS.HR_LOCATIONS_ALL HLA,
  XXDBL_COMPANY_LE_MAPPING_V OU
  WHERE 1=1
  --AND ORGANIZATION_ID=126
  AND AOU.LOCATION_ID=HLA.LOCATION_ID
  AND AOU.ORGANIZATION_ID=OU.ORG_ID
  ;
  