SELECT DISTINCT STATUS
  FROM XXDBL.XXDBL_IOU_REQ_DTL IRD
;


--------------------------------------------------------------------------------
SELECT
'CREATED' STSTUS
FROM DUAL
UNION ALL
SELECT
'APPROVED' STSTUS
FROM DUAL
UNION ALL
SELECT
'PAID' STSTUS
FROM DUAL
UNION ALL
SELECT
'ADJUSTED' STSTUS
FROM DUAL;
