/* Formatted on 9/18/2021 2:03:56 PM (QP5 v5.354) */
SELECT * FROM XX_APEX.XXAPEX_ORD_GRN_TRACK;

SELECT * FROM XXAPEX_ORD_GRN_TRACKING;

SELECT SEGMENT1 FROM PO.PO_HEADERS_ALL;

SELECT NAME FROM APPS.HR_OPERATING_UNITS;

Grant select on APPS.HR_OPERATING_UNITS to XX_APEX;

CREATE OR REPLACE SYNONYM XX_APEX.HR_OPERATING_UNITS FOR APPS.HR_OPERATING_UNITS;

CREATE OR REPLACE SYNONYM XX_APEX.HR_OPERATING_UNITS FOR APPS.HR_OPERATING_UNITS;