/* Formatted on 1/23/2021 10:32:54 AM (QP5 v5.287) */
SELECT RCT.ORG_ID,
       RCTL.SALES_ORDER,
       RCTL.SALES_ORDER_DATE,
       RCTL.INVENTORY_ITEM_ID,
       RCTL.DESCRIPTION,
       RCTL.UOM_CODE UOM,
       RCTL.QUANTITY_ORDERED,
       RCTL.QUANTITY_INVOICED,
       RCT.TRX_NUMBER TRANSACTION_NUMBER,
       RCT.TRX_DATE,
       RCT.BILL_TO_CUSTOMER_ID,
       RCT.BILL_TO_SITE_USE_ID,
       RCT.SHIP_TO_CUSTOMER_ID,
       RCT.SHIP_TO_SITE_USE_ID,
       RCT.REMIT_TO_ADDRESS_ID,
       (SELECT    ADDRESS1
               || ','
               || ADDRESS2
               || ','
               || ADDRESS3
               || ','
               || ADDRESS4
          FROM APPS.HZ_LOCATIONS LOC
         WHERE LOC.LOCATION_ID = RCT.REMIT_TO_ADDRESS_ID)
          ADDRESS,
       RCT.SHIP_DATE_ACTUAL,
       RCT.DOC_SEQUENCE_VALUE,
       --CL.ORG_ID,
       RCTL.UNIT_STANDARD_PRICE,
       RCTL.UNIT_SELLING_PRICE,
       RCTL.INTERFACE_LINE_ATTRIBUTE2 ORDER_TYPE,
       RCTL.REVENUE_AMOUNT,
       RCTL.WAREHOUSE_ID,
       DECODE (RCTL.LINE_TYPE,  'LINE', 'LINE_TOTAL',  'TAX', 'TOTAL_TAX')
          LINE_TYPE,
       RCTD.AMOUNT,
       RCTD.GL_DATE,
       RCTD.GL_POSTED_DATE,
       RCTD.ACCOUNT_CLASS,
       RCTD.ACCTD_AMOUNT,
       RCTT.NAME TRANSACTION_NAME,
       RCTT.DESCRIPTION TRANSACTION_DESCRIPTION,
       (SELECT DESCRIPTION
          FROM APPS.AR_LOOKUPS VAL
         WHERE LOOKUP_TYPE = 'TRANSACTION TYPE' AND LOOKUP_CODE = RCTT.TYPE)
          TRANSACTION_TYPE,
       DECODE (RCTT.TYPE,
               'CB', 'Chargeback',
               'CM', 'Credit Memo',
               'DM', 'Debit Memo',
               'DEP', 'Deposit',
               'GUAR', 'Guarantee',
               'INV', 'Invoice',
               'PMT', 'Receipt',
               'Others')
          TRANSACTION_TYPE
  --,RCTL.*
  --,RCT.*
  --,RCTD.*
  --,RCTT.*
  --,OOH.*
  FROM APPS.RA_CUSTOMER_TRX_ALL RCT,
       APPS.RA_CUSTOMER_TRX_LINES_ALL RCTL,
       APPS.RA_CUST_TRX_LINE_GL_DIST_ALL RCTD,
       APPS.RA_CUST_TRX_TYPES_ALL RCTT,
       APPS.OE_ORDER_HEADERS_ALL OOH,
       APPS.OE_ORDER_LINES_ALL OOL
 WHERE     1 = 1
       AND RCT.CUSTOMER_TRX_ID = RCTL.CUSTOMER_TRX_ID(+)
       AND RCT.CUSTOMER_TRX_ID = RCTD.CUSTOMER_TRX_ID(+)
       AND RCTD.CUSTOMER_TRX_LINE_ID = RCTL.CUSTOMER_TRX_LINE_ID(+)
       AND RCT.CUST_TRX_TYPE_ID = RCTT.CUST_TRX_TYPE_ID(+)
       AND RCTL.SALES_ORDER = OOH.ORDER_NUMBER(+)
       AND OOH.HEADER_ID = OOL.HEADER_ID(+)
       AND RCTL.INTERFACE_LINE_ATTRIBUTE6 = OOL.LINE_ID(+)
       AND RCTD.ACCOUNT_CLASS = 'REV'                                  --'REC'
       AND ( ( :P_ORG_ID IS NULL) OR (RCT.ORG_ID = :P_ORG_ID))
       AND ( :P_TRX_NUMBER IS NULL OR (RCT.TRX_NUMBER = :P_TRX_NUMBER))
       AND ( :P_ORDER_NUMBER IS NULL OR (RCTL.SALES_ORDER = :P_ORDER_NUMBER))
       AND (   :P_VOUCHER_NUM IS NULL
            OR (RCT.DOC_SEQUENCE_VALUE = :P_VOUCHER_NUM));