/* Formatted on 9/21/2021 10:03:22 AM (QP5 v5.354) */
SELECT * FROM GL_BUDGET_ASSIGNMENTS;

SELECT * FROM GL_BUDGETS;

SELECT * FROM GL_BUDGET_PERIOD_RANGES;

SELECT * FROM GL_BUDGET_ASSIGNMENT_RANGES;

SELECT * FROM GL_BUDGET_VERSIONS;

SELECT * FROM GL_BUDGET_BATCHES;

SELECT * FROM GL_BUDGET_ENTITIES;

SELECT * FROM GL_BUDGET_FROZEN_RANGES;

SELECT * FROM GL_BUDGET_INTERFACE;

SELECT * FROM GL_BUDGET_RANGE_INTERIM;

SELECT * FROM GL_BUDGET_TYPES;