/* Formatted on 6/6/2021 3:11:52 PM (QP5 v5.287) */
-- create the "parent" record in RA_INTERFACE_LINES_ALL

BEGIN
   INSERT INTO ra_interface_lines_all (interface_line_context,
                                       interface_line_attribute1,
                                       interface_line_attribute2,
                                       amount,
                                       batch_source_name,
                                       conversion_rate,
                                       conversion_type,
                                       currency_code,
                                       cust_trx_type_id,
                                       description,
                                       gl_date,
                                       line_type,
                                       orig_system_bill_address_id,
                                       orig_system_bill_customer_id,
                                       quantity,
                                       unit_selling_price,
                                       term_id,
                                       taxable_flag,
                                       amount_includes_tax_flag,
                                       set_of_books_id,
                                       org_id)
        VALUES ('DBL_IC_INVOICE',
                'XXDBLCL1',
                '03-JUN-21',
                1000.00,
                'DBL CL Imported Invoice',
                1,
                'User',
                'BDT',
                17162,
                'TIP DESCRIPTION 1 - ITEM #1',
                '06-AUG-2021',
                'LINE',
                5835,
                2660,
                10,
                100.00,
                5,
                'Y',
                'N',
                2079,
                126);

   -- create distribution records for only REV and REC rows

   INSERT INTO ra_interface_distributions_all (account_class,
                                               amount,
                                               code_combination_id,
                                               percent,
                                               interface_line_context,
                                               interface_line_attribute1,
                                               interface_line_attribute2,
                                               org_id)
        VALUES ('REC',
                1000.00,
                3114,
                100,
                'DBL_IC_INVOICE',
                'XXDBLCL1',
                '03-JUN-21',
                126);

   INSERT INTO ra_interface_distributions_all (account_class,
                                               amount,
                                               code_combination_id,
                                               percent,
                                               interface_line_context,
                                               interface_line_attribute1,
                                               interface_line_attribute2,
                                               --interface_line_attribute3,
                                               --interface_line_attribute4,
                                               --interface_line_attribute5,
                                               org_id)
        VALUES ('REV',
                1000.00,
                3211,
                100,
                'DBL_IC_INVOICE',
                'XXDBLCL1',
                '03-JUN-21',
                126);
END;