/* Formatted on 5/7/2020 7:27:29 PM (QP5 v5.287) */
SELECT
       ORG_ID,
       OU_NAME,
       --LEGAL_ENTITY_ID,
       LEGAL_ENTITY_NAME,
       ORGANIZATION_NAME,
       ITEM_CODE,
       ITEM_NAME,
       ITEM_CATEGORY_1 ITEM_CATEGORY_LOB,
       ITEM_CATEGORY_2 ITEM_CATEGORY_Major,
       ITEM_CATEGORY_3 ITEM_CATEGORY_Minor,
       --ITEM_CATEGORY_4,
       UOM,
       SUM(PR_QUANTITY) PR_QTY,
       SUM(PO_QUANTITY) PO_QTY,
       SUM(GRN_QUANTITY) GRN_QTY,
       SUM(ONHAND_QTY) ONHAND_QTY,
       SUM(QTY) CONSUMPTION_QTY,
       SUM(TOTAL_COST) TOTAL_CST
FROM
(SELECT ORG_ID,
       OU_NAME,
       TO_CHAR (LEGAL_ENTITY_ID),
       LEGAL_ENTITY_NAME,
       ORGANIZATION_NAME,
       REQUISITION_NUMBER,
       PR_APPROVED_DATE,
       PR_QUANTITY,
       PO_NUMBER,
       PO_APPROVED_DATE,
       PO_QUANTITY,
       RECEIPT_NUM GRN_NUMBER,
       GRN_DATE,
       GRN_QUANTITY,
       ITEM_CODE,
       ITEM_NAME,
       ITEM_CATEGORY_1,
       ITEM_CATEGORY_2,
       ITEM_CATEGORY_3,
       ITEM_CATEGORY_4,
       ITM.PRIMARY_UOM_CODE UOM,
       NULL ONHAND_QTY,
       NULL TRANSACTION_DATE,
       NULL QTY,
       NULL TOTAL_COST
  FROM APPS.XXDBL_PR_TO_PAY, APPS.MTL_SYSTEM_ITEMS_B ITM
 WHERE     1 = 1
       AND TRUNC (GRN_DATE) BETWEEN :P_DATE_FROM AND :P_DATE_TO
       AND ITEM_CODE=ITM.SEGMENT1
       AND ITM.ORGANIZATION_ID='138'
       AND ITEM_CATEGORY_1 = 'IT'
UNION ALL
SELECT CON.ORG_ID,
       HOU.NAME OU_NAME,
       HOU.DEFAULT_LEGAL_CONTEXT_ID LEGAL_ENTITY_ID,
       OU.LEGAL_ENTITY_NAME LEGAL_ENTITY_NAME,
       CON.ORGANIZATION_NAME,
       NULL REQUISITION_NUMBER,
       NULL PR_APPROVED_DATE,
       NULL PR_QUANTITY,
       NULL PO_NUMBER,
       NULL PO_APPROVED_DATE,
       NULL PO_QUANTITY,
       NULL GRN_NUMBER,
       NULL GRN_DATE,
       NULL GRN_QUANTITY,
       CON.ITEM_CODE,
       CON.ITEM_DESCRIPTION ITEM_NAME,
       ITEM_CATEGORY ITEM_CATEGORY_1,
       ITEM_TYPE ITEM_CATEGORY_2,
       ITEM_CATEGORY_3,
       ITEM_CATEGORY_4,
       UOM,
       NULL ONHAND_QTY,
       TRANSACTION_DATE,
       TRX_QUANTITY QTY,
       TOTAL_COST
  FROM (SELECT A.TRANSACTION_ID,
               C.SEGMENT1 ITEM_CODE,
               C.DESCRIPTION "ITEM_DESCRIPTION",
               C.PRIMARY_UOM_CODE "UOM",
               MIC.SEGMENT1 ITEM_CATEGORY,
               MIC.SEGMENT2 ITEM_TYPE,
               MIC.SEGMENT3 ITEM_CATEGORY_3,
               MIC.SEGMENT4 ITEM_CATEGORY_4,
               PP.NAME AS DEPARTMENT,
               --  A.NEW_COST UNIT_COST,
               (A.PRIMARY_QUANTITY) TRX_QUANTITY,
               CASE
                  WHEN MP.PROCESS_ENABLED_FLAG = 'N'
                  THEN
                     APPS.XX_INV_TRAN_VAL_T (A.TRANSACTION_ID)
                  ELSE
                     APPS.XX_OINV_TRAN_VAL (A.TRANSACTION_ID)
               END
                  AS TOTAL_COST,
               OOD.OPERATING_UNIT ORG_ID,
               --HOU.NAME "OPERATING_UNIT_NAME",
               OOD.ORGANIZATION_NAME,
               B.REQUEST_NUMBER MO_NO,
               TRUNC (A.TRANSACTION_DATE) TRANSACTION_DATE
          FROM APPS.MTL_MATERIAL_TRANSACTIONS A,
               APPS.MTL_TXN_REQUEST_HEADERS B,
               MTL_TXN_REQUEST_LINES_V MTRL,
               APPS.MTL_SYSTEM_ITEMS_B C,
               APPS.MTL_ITEM_CATEGORIES_V MIC,
               APPS.GL_CODE_COMBINATIONS CC,
               INV.MTL_PARAMETERS MP,
               APPS.ORG_ORGANIZATION_DEFINITIONS OOD,
               APPS.HR_OPERATING_UNITS HOU,
               INV.ORG_ACCT_PERIODS PRD,
               APPLSYS.FND_USER FNU,
               (SELECT Q1.*, HAOU.NAME
                  FROM HR.PER_ALL_PEOPLE_F Q1,
                       HR.PER_ALL_ASSIGNMENTS_F PAAF,
                       HR.HR_ALL_ORGANIZATION_UNITS HAOU
                 WHERE     SYSDATE BETWEEN Q1.EFFECTIVE_START_DATE
                                       AND Q1.EFFECTIVE_END_DATE
                       AND SYSDATE BETWEEN PAAF.EFFECTIVE_START_DATE
                                       AND PAAF.EFFECTIVE_END_DATE
                       AND Q1.PERSON_ID = PAAF.PERSON_ID
                       AND PAAF.ORGANIZATION_ID = HAOU.ORGANIZATION_ID) PP
         WHERE     A.ORGANIZATION_ID = MP.ORGANIZATION_ID
               AND MP.ORGANIZATION_ID = OOD.ORGANIZATION_ID
               AND OOD.OPERATING_UNIT = HOU.ORGANIZATION_ID
               AND A.INVENTORY_ITEM_ID = C.INVENTORY_ITEM_ID
               AND A.ORGANIZATION_ID = C.ORGANIZATION_ID
               AND A.INVENTORY_ITEM_ID = MIC.INVENTORY_ITEM_ID
               AND A.ORGANIZATION_ID = MIC.ORGANIZATION_ID
               AND A.TRANSACTION_TYPE_ID IN (63)
               AND A.TRANSACTION_SOURCE_ID = B.HEADER_ID
               AND B.HEADER_ID = MTRL.HEADER_ID
               AND B.CREATED_BY = FNU.USER_ID
               AND PP.PARTY_ID(+) = NVL (FNU.PERSON_PARTY_ID, 0)
               AND A.DISTRIBUTION_ACCOUNT_ID = CC.CODE_COMBINATION_ID
               AND A.ACCT_PERIOD_ID = PRD.ACCT_PERIOD_ID
               AND A.TRANSACTION_QUANTITY < 0
               AND A.ORGANIZATION_ID = PRD.ORGANIZATION_ID
               AND MTRL.INVENTORY_ITEM_ID = A.INVENTORY_ITEM_ID
               AND MTRL.ORGANIZATION_ID = A.ORGANIZATION_ID
               AND MTRL.LINE_ID = A.TRX_SOURCE_LINE_ID
               AND A.TRANSACTION_SOURCE_ID = B.HEADER_ID
               AND CATEGORY_SET_NAME = 'Inventory'
               AND TRUNC (A.TRANSACTION_DATE) BETWEEN :P_DATE_FROM
                                                  AND :P_DATE_TO) CON,
       XXDBL_COMPANY_LE_MAPPING_V OU,
       HR_OPERATING_UNITS HOU
 WHERE     1 = 1
       AND ITEM_CATEGORY = 'IT'
       AND CON.ORG_ID = OU.ORG_ID
       AND HOU.ORGANIZATION_ID = CON.ORG_ID
UNION ALL
  SELECT OU.ORG_ID,
         HOU.NAME OU_NAME,
         HOU.DEFAULT_LEGAL_CONTEXT_ID LEGAL_ENTITY_ID,
         OU.LEGAL_ENTITY_NAME LEGAL_ENTITY_NAME,
         ORG.ORGANIZATION_NAME,
         NULL REQUISITION_NUMBER,
         NULL PR_APPROVED_DATE,
         NULL PR_QUANTITY,
         NULL PO_NUMBER,
         NULL PO_APPROVED_DATE,
         NULL PO_QUANTITY,
         NULL GRN_NUMBER,
         NULL GRN_DATE,
         NULL GRN_QUANTITY,
         MSI.SEGMENT1 ITEM_CODE,
         MSI.DESCRIPTION ITEM_NAME,
         MIC.SEGMENT1 ITEM_CATEGORY_1,
         MIC.SEGMENT2 ITEM_CATEGORY_2,
         MIC.SEGMENT3 ITEM_CATEGORY_3,
         MIC.SEGMENT4 ITEM_CATEGORY_4,
         MSI.PRIMARY_UOM_CODE UOM,
         SUM (PRIMARY_QUANTITY) ONHAND_QTY,
         NULL TRANSACTION_DATE,
         NULL QTY,
         NULL TOTAL_COST
    FROM MTL_MATERIAL_TRANSACTIONS MOQ,           --mtl_onhand_quantities moq,
         ORG_ORGANIZATION_DEFINITIONS ORG,
         MTL_SYSTEM_ITEMS_B MSI,
         MTL_ITEM_CATEGORIES_V MIC,
         MTL_SECONDARY_INVENTORIES SI,
         INV.MTL_ITEM_LOCATIONS MIL,
         XXDBL_COMPANY_LE_MAPPING_V OU,
         HR_OPERATING_UNITS HOU
   WHERE     1 = 1
         AND MOQ.ORGANIZATION_ID = ORG.ORGANIZATION_ID
         AND HOU.ORGANIZATION_ID = ORG.OPERATING_UNIT
         AND ORG.OPERATING_UNIT = OU.ORG_ID
         AND MOQ.ORGANIZATION_ID = MSI.ORGANIZATION_ID
         AND MOQ.INVENTORY_ITEM_ID = MSI.INVENTORY_ITEM_ID
         AND MOQ.ORGANIZATION_ID = MIC.ORGANIZATION_ID
         AND MOQ.INVENTORY_ITEM_ID = MIC.INVENTORY_ITEM_ID
         AND MOQ.ORGANIZATION_ID = SI.ORGANIZATION_ID
         AND MSI.ORGANIZATION_ID = SI.ORGANIZATION_ID
         AND MIC.ORGANIZATION_ID = SI.ORGANIZATION_ID
         AND MOQ.SUBINVENTORY_CODE = SI.SECONDARY_INVENTORY_NAME
         AND MIC.CATEGORY_SET_ID = 1
         AND MIC.SEGMENT2 = 'IT'
         AND TRUNC (MOQ.TRANSACTION_DATE)<= --BETWEEN :P_DATE_FROM AND 
         :P_DATE_TO
         AND SI.DISABLE_DATE IS NULL
         AND MOQ.LOCATOR_ID = MIL.INVENTORY_LOCATION_ID(+)
GROUP BY OU.ORG_ID,
         HOU.NAME,
         HOU.DEFAULT_LEGAL_CONTEXT_ID,
         OU.LEGAL_ENTITY_NAME,
         ORG.ORGANIZATION_NAME,
         MSI.SEGMENT1 ,
         MSI.DESCRIPTION,
         MIC.SEGMENT2,
         MIC.SEGMENT3,
         MIC.SEGMENT4,
         MIC.SEGMENT1,
         MSI.PRIMARY_UOM_CODE
  HAVING SUM (PRIMARY_QUANTITY) <> 0)
  WHERE 1=1
  --AND ITEM_CODE='SPRECONS000000004278'
  GROUP BY
  ORG_ID,
       OU_NAME,
       --LEGAL_ENTITY_ID,
       LEGAL_ENTITY_NAME,
       ORGANIZATION_NAME,
       ITEM_CODE,
       ITEM_NAME,
       ITEM_CATEGORY_1,
       ITEM_CATEGORY_2,
       ITEM_CATEGORY_3,
       ITEM_CATEGORY_4,
       UOM;
  