/* Formatted on 6/21/2020 1:20:54 PM (QP5 v5.287) */
  SELECT PHA.SEGMENT1 PO_NUM,
         PHA.REVISION_NUM,
         PLA.LINE_NUM PO_LINE_NUM,
         PLLA.SHIPMENT_NUM,
         PLA.ITEM_DESCRIPTION,
         PLA.UNIT_MEAS_LOOKUP_CODE,
         PLA.LIST_PRICE_PER_UNIT,
         PLA.CANCEL_FLAG,
         PLA.CANCEL_DATE,
         PLA.QUANTITY PO_LINE_QUANTITY,
         PHA.AUTHORIZATION_STATUS HEADER_APPROVAL_STATUS,
         PHA.APPROVED_FLAG HEADER_APPROVED_FLAG,
         PHA.APPROVED_DATE HEADER_APPROVED_DATE,
         PHA.CLOSED_CODE HEADER_CLOSURE_STATUS,
         PLA.CLOSED_CODE LINE_CLOSURE_STATUS,
         PLLA.CLOSED_CODE SHIPMENT_CLORSURE_STATUS,
         PLLA.APPROVED_FLAG SHIPMENT_APPROVED_FLAG,
         PLLA.APPROVED_DATE SHIPMENT_APPROVED_DATE,
         PHA.CANCEL_FLAG PO_CANCEL_FLAG,
         PLA.CANCEL_FLAG LINE_CANCEL_FLAG,
         PLLA.CANCEL_FLAG SHIPMENT_CANCEL_FLAG,
         PHA.ORG_ID,
         PV.VENDOR_NAME,
         APSS.VENDOR_SITE_CODE
         ,PLA.*
    FROM PO.PO_LINE_LOCATIONS_ARCHIVE_ALL PLLA,
         PO.PO_LINES_ARCHIVE_ALL PLA,
         --PO.PO_LINES_ARCHIVE_ALL PLA2,
         PO.PO_HEADERS_ARCHIVE_ALL PHA,
         APPS.PO_VENDORS PV,
         APPS.AP_SUPPLIER_SITES_ALL APSS
   WHERE     1 = 1
         AND PLA.PO_LINE_ID = PLLA.PO_LINE_ID
         --AND PLA.PO_LINE_ID = PLA2.PO_LINE_ID
         --AND PLA.LINE_NUM = PLA2.LINE_NUM
         --AND PLA.REVISION_NUM = PLA2.REVISION_NUM
         --AND PLA.QUANTITY != PLA2.QUANTITY
         --AND PLA.CANCEL_FLAG = 'N'
         AND PHA.VENDOR_ID = PV.VENDOR_ID
         AND PHA.VENDOR_SITE_ID = APSS.VENDOR_SITE_ID
         AND PLA.PO_HEADER_ID = PLLA.PO_HEADER_ID
         AND PHA.PO_HEADER_ID = PLA.PO_HEADER_ID
         --AND pha.VENDOR_ID = '2550'
         --AND PHA.VENDOR_SITE_ID = '9879'
         AND PHA.SEGMENT1 IN ('10323009890')
         AND PHA.REVISION_NUM = PLA.REVISION_NUM
         AND PLA.REVISION_NUM = PLLA.REVISION_NUM
         AND PHA.REVISION_NUM = PLLA.REVISION_NUM
ORDER BY PHA.SEGMENT1, PLA.LINE_NUM,PLLA.SHIPMENT_NUM;