/* Formatted on 4/7/2020 3:55:24 PM (QP5 v5.287) */
  SELECT PRH.ORG_ID,
         HOU.NAME "Operating unit",
         --PRH.REQUISITION_HEADER_ID REQ_HDR_ID,
         PRH.SEGMENT1 "Requisition Number",
         TO_CHAR (PRH.CREATION_DATE, 'DD-MON-RRRR HH12:MI:SS PM')
            REQ_CREATION_DATE,
         PRH.AUTHORIZATION_STATUS REQ_STATUS,
         --TO_CHAR (PRH.APPROVED_DATE, 'DD-MON-RRRR HH12:MI:SS PM') REQ_APPROVED_DATE,
         --PRL.NEED_BY_DATE REQ_NEED_BY_DATE,
         PHA.SEGMENT1 "PO Number",
         TO_CHAR (PHA.CREATION_DATE, 'DD-MON-RRRR HH12:MI:SS PM') PO_CREATION_DATE,
         PHA.AUTHORIZATION_STATUS PO_STATUS,
         --TO_CHAR (PHA.APPROVED_DATE, 'DD-MON-RRRR HH12:MI:SS PM') PO_APPROVED_DATE,
         --PRL.LINE_NUM REQ_LINE_NUM,
         MSI.SEGMENT1 ITEM_CODE,
         NVL (MSI.DESCRIPTION, PRL.ITEM_DESCRIPTION) ITEM_DESCRIPTION,
         PRL.UNIT_MEAS_LOOKUP_CODE UOM,
         --CAT.CATEGORY_SET_NAME CATEGORY_SET,
         CAT.SEGMENT1 LINE_OF_BUSINESS,
         CAT.SEGMENT2 ITEM_CATEGORY,
         CAT.SEGMENT3 ITEM_TYPE,
         CAT.SEGMENT4 CATELOG,
         CAT.CATEGORY_CONCAT_SEGS CATEGORY_SEGMENTS,
         --PRL.QUANTITY REQ_QTY,
         --PLA.QUANTITY PO_QTY,
         --PRL.ITEM_ID,
         (SELECT PF.FIRST_NAME || ' ' || PF.MIDDLE_NAMES || ' ' || PF.LAST_NAME
            FROM PER_PEOPLE_F PF
           WHERE     PRL.SUGGESTED_BUYER_ID = PF.PERSON_ID
                 AND SYSDATE BETWEEN PF.EFFECTIVE_START_DATE
                                 AND PF.EFFECTIVE_END_DATE)
            BUYER,
         PRL.SUGGESTED_BUYER_ID
         --PROJECT.PROJECT_NAME,
         --PRH.ATTRIBUTE8 PURPOSE,
         --PRL.ATTRIBUTE1 BRAND,
         --PRL.ATTRIBUTE2 ORGIN,
         --PRL.ATTRIBUTE3 MAKE,
         --PRL.ATTRIBUTE6 ORDER_NO,
         --PRL.ATTRIBUTE7 USE_OF_AREA,
--         NVL (SUB.DESCRIPTION, SECONDARY_INVENTORY_NAME) SUBINV,
--         LTRIM (
--            RTRIM (
--                  PPF.FIRST_NAME
--               || ' '
--               || PPF.MIDDLE_NAMES
--               || ' '
--               || PPF.LAST_NAME))
--            GLOBAL_NAME,
--         PRL.DESTINATION_SUBINVENTORY SUBINVENTORY,
--         NVL (HRL.DESCRIPTION, HRL.LOCATION_CODE) LOCATION,
--         PRL.ATTRIBUTE6 REMARKS,
--         DECODE (PRL.ATTRIBUTE_CATEGORY,
--                 'Item Details', PRL.ATTRIBUTE4,
--                 PRL.ATTRIBUTE4)
--            BUYER_ID,
--         PDA.REQ_DISTRIBUTION_ID
    FROM PO_REQUISITION_HEADERS_ALL PRH,
         PO_REQUISITION_LINES_ALL PRL,
         APPS.PO_REQ_DISTRIBUTIONS_ALL PROD,
         MTL_SYSTEM_ITEMS_B MSI,
         ALL_PROJECT_INFO_MASTER PROJECT,
         HR_LOCATIONS_ALL HRL,
         FND_USER FU,
         PER_PEOPLE_F PPF,
         APPS.PO_DISTRIBUTIONS_ALL PDA,
         APPS.PO_LINES_ALL PLA,
         APPS.PO_LINE_LOCATIONS_ALL PLL,
         APPS.PO_HEADERS_ALL PHA,
         HR_OPERATING_UNITS HOU,
         ORG_ORGANIZATION_DEFINITIONS OOD,
         APPS.MTL_ITEM_CATEGORIES_V CAT,
         MTL_SECONDARY_INVENTORIES SUB
   WHERE     1 = 1
         AND PRH.REQUISITION_HEADER_ID = PRL.REQUISITION_HEADER_ID
         AND PRL.ITEM_ID = MSI.INVENTORY_ITEM_ID(+)
         AND PRL.DESTINATION_ORGANIZATION_ID = MSI.ORGANIZATION_ID(+)
         AND PRH.ATTRIBUTE4 = PROJECT.PROJECT_ID(+)
         AND PRL.DELIVER_TO_LOCATION_ID = HRL.LOCATION_ID
         AND PRH.CREATED_BY = FU.USER_ID(+)
         AND PRL.REQUISITION_LINE_ID = PROD.REQUISITION_LINE_ID
         AND PROD.DISTRIBUTION_ID = PDA.REQ_DISTRIBUTION_ID(+)
         AND PDA.PO_LINE_ID = PLA.PO_LINE_ID(+)
         AND PDA.LINE_LOCATION_ID = PLL.LINE_LOCATION_ID(+)
         AND PLL.PO_LINE_ID = PLA.PO_LINE_ID(+)
         AND PLL.PO_HEADER_ID = PHA.PO_HEADER_ID(+)
         AND PDA.PO_HEADER_ID = PHA.PO_HEADER_ID(+)
         AND PLL.PO_LINE_ID = PLA.PO_LINE_ID(+)
         AND FU.EMPLOYEE_ID = PPF.PERSON_ID(+)
         AND PRL.DESTINATION_SUBINVENTORY = SUB.SECONDARY_INVENTORY_NAME(+) ---DESTINATION_SUBINVENTORY
         AND PRL.DESTINATION_ORGANIZATION_ID = SUB.ORGANIZATION_ID(+)
         AND SYSDATE BETWEEN PPF.EFFECTIVE_START_DATE
                         AND PPF.EFFECTIVE_END_DATE
         AND PRH.ORG_ID = HOU.ORGANIZATION_ID
         AND MSI.ORGANIZATION_ID = OOD.ORGANIZATION_ID
         AND PRL.CANCEL_DATE IS NULL
         AND OOD.ORGANIZATION_CODE IN ('156', '136')
         AND MSI.INVENTORY_ITEM_ID = CAT.INVENTORY_ITEM_ID
         AND MSI.ORGANIZATION_ID = CAT.ORGANIZATION_ID
         AND ( ( :P_ORG_ID IS NULL) OR (PRH.ORG_ID = :P_ORG_ID))
         AND ( :P_REQ_NO IS NULL OR (PRH.SEGMENT1 = :P_REQ_NO))
         AND ( :P_ITEM_CODE IS NULL OR (MSI.SEGMENT1 = :P_ITEM_CODE))
         AND (   :P_ITEM_DESC IS NULL
              OR (UPPER (MSI.DESCRIPTION) LIKE
                     UPPER ('%' || :P_ITEM_DESC || '%')))
         AND PRL.DESTINATION_ORGANIZATION_ID =
                NVL ( :P_DEST_ORG_ID, PRL.DESTINATION_ORGANIZATION_ID)
         AND PRH.AUTHORIZATION_STATUS =
                NVL ( :P_AUTHORIZATION_STATUS, PRH.AUTHORIZATION_STATUS)
         AND (   :P_FROM_CREATION_DATE IS NULL
              OR TRUNC (PRH.CREATION_DATE) BETWEEN :P_FROM_CREATION_DATE
                                               AND :P_TO_CREATION_DATE)
ORDER BY PRL.LINE_NUM