/* Formatted on 7/2/2020 5:55:47 PM (QP5 v5.287) */
SELECT PRHA.SEGMENT1 "req_number",
       PAH.ACTION_CODE "req_status",
       PAH.ACTION_DATE "sataus date",
       PAH.SEQUENCE_NUM,
       PAH.OBJECT_ID,
       PHA.SEGMENT1,
       PAH1.ACTION_CODE,
       PAH1.ACTION_DATE,
       PHA.SEGMENT1 "po_number",
       PHA.PO_HEADER_ID,
       PAH1.action_code "po_status"
  FROM PO_REQUISITION_HEADERS_ALL PRHA,
       PO_REQUISITION_LINES_ALL PRLA,
       PO_REQ_DISTRIBUTIONS_ALL PRDA,
       (SELECT *
          FROM PO_ACTION_HISTORY
         WHERE     OBJECT_TYPE_CODE = 'REQUISITION'
               AND OBJECT_SUB_TYPE_CODE = 'PURCHASE') PAH,
       PO_DISTRIBUTIONS_ALL PDA,
       PO_HEADERS_ALL PHA,
       (SELECT *
          FROM PO_ACTION_HISTORY
         WHERE OBJECT_TYPE_CODE = 'PO' AND OBJECT_SUB_TYPE_CODE <> 'PURCHASE')
       PAH1
 WHERE     PRHA.REQUISITION_HEADER_ID = PRLA.REQUISITION_HEADER_ID
       AND PRLA.REQUISITION_LINE_ID = PRDA.REQUISITION_LINE_ID
       AND PRHA.REQUISITION_HEADER_ID = PAH.OBJECT_ID
       --AND PRHA.SEGMENT1 = '700003682'
       --AND PAH.OBJECT_TYPE_CODE='REQUISITION'
       --AND PAH.OBJECT_SUB_TYPE_CODE='PURCHASE'
       AND PDA.REQ_DISTRIBUTION_ID(+) = PRDA.DISTRIBUTION_ID
       AND PDA.PO_HEADER_ID = PHA.PO_HEADER_ID(+)
       AND PHA.PO_HEADER_ID = PAH1.OBJECT_ID(+)