/* Formatted on 10/21/2020 5:58:02 PM (QP5 v5.354) */
SELECT LC.FUNCTIONAL_AMOUNT
  FROM MTL_UNITS_OF_MEASURE        UOM,
       PON_PRICE_ELEMENT_TYPES_VL  PE,
       INL_CHARGE_LINES            CL,
       INL_TAX_LINES               TL,
       INL_ASSOCIATIONS            ASSOC,
       INL_SHIP_HEADERS_ALL        SH,
       INL_SHIP_LINES_ALL          SL2,
       INL_SHIP_LINES_ALL          SL,
       INL_ALLOCATIONS_V           ALLOC,
       XX_LC_DETAILS               LC
 WHERE     UOM.UOM_CODE = SL.PRIMARY_UOM_CODE
       AND PE.PRICE_ELEMENT_TYPE_ID(+) = CL.CHARGE_LINE_TYPE_ID
       AND SH.ORGANIZATION_ID = 197
       AND SL.INVENTORY_ITEM_ID = 497352
       AND LC.PO_HEADER_ID = 497352
       AND SL.SHIP_LINE_SOURCE_ID = 656020
       AND SL2.SHIP_LINE_ID(+) =
           DECODE (ALLOC.FROM_PARENT_TABLE_NAME,
                   'INL_SHIP_LINES', ALLOC.FROM_PARENT_TABLE_ID,
                   NULL)
       AND CL.CHARGE_LINE_ID(+) =
           DECODE (ALLOC.FROM_PARENT_TABLE_NAME,
                   'INL_CHARGE_LINES', ALLOC.FROM_PARENT_TABLE_ID,
                   NULL)
       AND TL.TAX_LINE_ID(+) =
           DECODE (ALLOC.FROM_PARENT_TABLE_NAME,
                   'INL_TAX_LINES', ALLOC.FROM_PARENT_TABLE_ID,
                   NULL)
       AND SL2.SHIP_HEADER_ID(+) = ALLOC.SHIP_HEADER_ID
       AND ASSOC.ASSOCIATION_ID(+) = ALLOC.ASSOCIATION_ID
       AND SH.SHIP_HEADER_ID = SL.SHIP_HEADER_ID
       AND SH.SHIP_HEADER_ID = ALLOC.SHIP_HEADER_ID
       AND SL.SHIP_HEADER_ID = ALLOC.SHIP_HEADER_ID
       AND SL.SHIP_LINE_ID = ALLOC.SHIP_LINE_ID
       AND LC.PO_HEADER_ID = 369990
       AND LC.LC_STATUS = 'Y'
       AND SH.SHIP_STATUS_CODE <> 'CLOSED'
       AND ALLOC.ADJUSTMENT_NUM =
           (SELECT MAX (ADJUSTMENT_NUM)
              FROM INL_ALLOCATIONS_V
             WHERE     SHIP_HEADER_ID = SL.SHIP_HEADER_ID
                   AND SHIP_LINE_ID = SL.SHIP_LINE_ID
                   AND PARENT_SHIP_LINE_ID = SL.PARENT_SHIP_LINE_ID)
       --  AND msi.organization_id = 150
       --     AND sh.SHIP_NUM = 81
       AND DECODE (ASSOC.FROM_PARENT_TABLE_NAME,
                   'INL_CHARGE_LINES', 'CHARGE',
                   'INL_TAX_LINES', 'TAX',
                   'ITEM PRICE') =
           'ITEM PRICE';
           
           
--------------------------------------------------------------------------------
/* Formatted on 10/22/2020 9:57:15 AM (QP5 v5.354) */
  SELECT LC.FUNCTIONAL_AMOUNT, SL.*
    FROM XX_LC_DETAILS LC, INL_SHIP_LINES_ALL SL, INL_SHIP_HEADERS_ALL SH
   WHERE     1 = 1
         AND LC.PO_HEADER_ID = 361046
         AND SL.SHIP_LINE_SOURCE_ID = 628316
         AND SL.INVENTORY_ITEM_ID = 128992
         AND SH.SHIP_HEADER_ID = SL.SHIP_HEADER_ID
         AND SL.SHIP_TO_ORGANIZATION_ID = SH.ORGANIZATION_ID
         --AND LC.PO_NUMBER='25113005742'
         AND LC.LC_STATUS = 'Y'
         AND SH.SHIP_STATUS_CODE <> 'CLOSED'
ORDER BY LC.CREATION_DATE DESC