/* Formatted on 1/30/2021 3:55:46 PM (QP5 v5.287) */
CREATE OR REPLACE PACKAGE apps.xxdbl_cer_item_upld_pkg
IS
   p_responsibility_id   NUMBER := apps.fnd_global.resp_id;
   p_respappl_id         NUMBER := apps.fnd_global.resp_appl_id;
   p_user_id             NUMBER := apps.fnd_global.user_id;
   p_org_id              NUMBER := apps.fnd_global.org_id;

   PROCEDURE item_basis_upd (errbuf       OUT NOCOPY NUMBER,
                             retcode      OUT NOCOPY VARCHAR2);

   PROCEDURE gl_aloc_basis_proc;

   PROCEDURE recp_rout_procedure (p_formula_no    IN     VARCHAR2,
                                  x_out_message      OUT VARCHAR2);

   PROCEDURE formula_upload_prc (errbuf              OUT VARCHAR2,
                                 retcode             OUT NUMBER,
                                 p_batch_number   IN     NUMBER);

   PROCEDURE xxdbl_formula_insert (
      p_record_type                 IN VARCHAR2 DEFAULT NULL,
      p_formula_no                  IN VARCHAR2 DEFAULT NULL,
      p_formula_vers                IN NUMBER DEFAULT NULL,
      p_formula_type                IN VARCHAR2 DEFAULT NULL,
      p_formula_desc1               IN VARCHAR2 DEFAULT NULL,
      p_formula_desc2               IN VARCHAR2 DEFAULT NULL,
      p_formula_class               IN VARCHAR2 DEFAULT NULL,
      p_fmcontrol_class             IN VARCHAR2 DEFAULT NULL,
      p_inactive_ind                IN NUMBER DEFAULT NULL,
      p_owner_organization_code     IN VARCHAR2 DEFAULT NULL,
      p_total_input_qty             IN NUMBER DEFAULT NULL,
      p_total_output_qty            IN NUMBER DEFAULT NULL,
      p_yield_uom                   IN VARCHAR2 DEFAULT NULL,
      p_formula_status              IN VARCHAR2 DEFAULT NULL,
      p_owner_code                  IN VARCHAR2 DEFAULT NULL,
      p_formula_id                  IN NUMBER DEFAULT NULL,
      p_formulaline_id              IN NUMBER DEFAULT NULL,
      p_line_type                   IN VARCHAR2 DEFAULT NULL,
      p_line_no                     IN NUMBER DEFAULT NULL,
      p_item_no                     IN VARCHAR2 DEFAULT NULL,
      p_inventory_item_id           IN NUMBER DEFAULT NULL,
      p_revision                    IN VARCHAR2 DEFAULT NULL,
      p_qty                         IN NUMBER DEFAULT NULL,
      p_detail_uom                  IN VARCHAR2 DEFAULT NULL,
      p_master_formula_id           IN NUMBER DEFAULT NULL,
      p_release_type                IN NUMBER DEFAULT NULL,
      p_scrap_factor                IN VARCHAR2 DEFAULT NULL,
      p_scale_type_hdr              IN VARCHAR2 DEFAULT NULL,
      p_scale_type_dtl              IN NUMBER DEFAULT NULL,
      p_cost_alloc                  IN NUMBER DEFAULT NULL,
      p_phantom_type                IN NUMBER DEFAULT NULL,
      p_rework_type                 IN NUMBER DEFAULT NULL,
      p_buffer_ind                  IN NUMBER DEFAULT NULL,
      p_by_product_type             IN VARCHAR2 DEFAULT NULL,
      p_ingredient_end_date         IN DATE DEFAULT NULL,
      p_attribute1                  IN VARCHAR2 DEFAULT NULL,
      p_attribute2                  IN VARCHAR2 DEFAULT NULL,
      p_attribute3                  IN VARCHAR2 DEFAULT NULL,
      p_attribute4                  IN VARCHAR2 DEFAULT NULL,
      p_attribute5                  IN VARCHAR2 DEFAULT NULL,
      p_attribute6                  IN VARCHAR2 DEFAULT NULL,
      p_attribute7                  IN VARCHAR2 DEFAULT NULL,
      p_attribute8                  IN VARCHAR2 DEFAULT NULL,
      p_attribute9                  IN VARCHAR2 DEFAULT NULL,
      p_attribute10                 IN VARCHAR2 DEFAULT NULL,
      p_attribute11                 IN VARCHAR2 DEFAULT NULL,
      p_attribute12                 IN VARCHAR2 DEFAULT NULL,
      p_attribute13                 IN VARCHAR2 DEFAULT NULL,
      p_attribute14                 IN VARCHAR2 DEFAULT NULL,
      p_attribute15                 IN VARCHAR2 DEFAULT NULL,
      p_attribute16                 IN VARCHAR2 DEFAULT NULL,
      p_attribute17                 IN VARCHAR2 DEFAULT NULL,
      p_attribute18                 IN VARCHAR2 DEFAULT NULL,
      p_attribute19                 IN VARCHAR2 DEFAULT NULL,
      p_attribute20                 IN VARCHAR2 DEFAULT NULL,
      p_attribute21                 IN VARCHAR2 DEFAULT NULL,
      p_attribute22                 IN VARCHAR2 DEFAULT NULL,
      p_attribute23                 IN VARCHAR2 DEFAULT NULL,
      p_attribute24                 IN VARCHAR2 DEFAULT NULL,
      p_attribute25                 IN VARCHAR2 DEFAULT NULL,
      p_attribute26                 IN VARCHAR2 DEFAULT NULL,
      p_attribute27                 IN VARCHAR2 DEFAULT NULL,
      p_attribute28                 IN VARCHAR2 DEFAULT NULL,
      p_attribute29                 IN VARCHAR2 DEFAULT NULL,
      p_attribute30                 IN VARCHAR2 DEFAULT NULL,
      p_dtl_attribute1              IN VARCHAR2 DEFAULT NULL,
      p_dtl_attribute2              IN VARCHAR2 DEFAULT NULL,
      p_dtl_attribute3              IN VARCHAR2 DEFAULT NULL,
      p_dtl_attribute4              IN VARCHAR2 DEFAULT NULL,
      p_dtl_attribute5              IN VARCHAR2 DEFAULT NULL,
      p_dtl_attribute6              IN VARCHAR2 DEFAULT NULL,
      p_dtl_attribute7              IN VARCHAR2 DEFAULT NULL,
      p_dtl_attribute8              IN VARCHAR2 DEFAULT NULL,
      p_dtl_attribute9              IN VARCHAR2 DEFAULT NULL,
      p_dtl_attribute10             IN VARCHAR2 DEFAULT NULL,
      p_dtl_attribute11             IN VARCHAR2 DEFAULT NULL,
      p_dtl_attribute12             IN VARCHAR2 DEFAULT NULL,
      p_dtl_attribute13             IN VARCHAR2 DEFAULT NULL,
      p_dtl_attribute14             IN VARCHAR2 DEFAULT NULL,
      p_dtl_attribute15             IN VARCHAR2 DEFAULT NULL,
      p_dtl_attribute16             IN VARCHAR2 DEFAULT NULL,
      p_dtl_attribute17             IN VARCHAR2 DEFAULT NULL,
      p_dtl_attribute18             IN VARCHAR2 DEFAULT NULL,
      p_dtl_attribute19             IN VARCHAR2 DEFAULT NULL,
      p_dtl_attribute20             IN VARCHAR2 DEFAULT NULL,
      p_dtl_attribute21             IN VARCHAR2 DEFAULT NULL,
      p_dtl_attribute22             IN VARCHAR2 DEFAULT NULL,
      p_dtl_attribute23             IN VARCHAR2 DEFAULT NULL,
      p_dtl_attribute24             IN VARCHAR2 DEFAULT NULL,
      p_dtl_attribute25             IN VARCHAR2 DEFAULT NULL,
      p_dtl_attribute26             IN VARCHAR2 DEFAULT NULL,
      p_dtl_attribute27             IN VARCHAR2 DEFAULT NULL,
      p_dtl_attribute28             IN VARCHAR2 DEFAULT NULL,
      p_dtl_attribute29             IN VARCHAR2 DEFAULT NULL,
      p_dtl_attribute30             IN VARCHAR2 DEFAULT NULL,
      p_attribute_category          IN VARCHAR2 DEFAULT NULL,
      p_dtl_attribute_category      IN VARCHAR2 DEFAULT NULL,
      p_tpformula_id                IN NUMBER DEFAULT NULL,
      p_iaformula_id                IN NUMBER DEFAULT NULL,
      p_scale_multiple              IN VARCHAR2 DEFAULT NULL,
      p_contribute_yield_ind        IN VARCHAR2 DEFAULT NULL,
      p_scale_uom                   IN VARCHAR2 DEFAULT NULL,
      p_contribute_step_qty_ind     IN VARCHAR2 DEFAULT NULL,
      p_scale_rounding_variance     IN NUMBER DEFAULT NULL,
      p_rounding_direction          IN VARCHAR2 DEFAULT NULL,
      p_text_code_hdr               IN NUMBER DEFAULT NULL,
      p_text_code_dtl               IN NUMBER DEFAULT NULL,
      --p_user_id                     IN NUMBER DEFAULT NULL,
      p_creation_date               IN DATE DEFAULT NULL,
      p_created_by                  IN NUMBER DEFAULT NULL,
      p_last_updated_by             IN NUMBER DEFAULT NULL,
      p_last_update_date            IN DATE DEFAULT NULL,
      p_last_update_login           IN NUMBER DEFAULT NULL,
      p_user_name                   IN VARCHAR2 DEFAULT NULL,
      p_delete_mark                 IN NUMBER DEFAULT NULL,
      p_auto_product_calc           IN VARCHAR2 DEFAULT NULL,
      p_prod_percent                IN NUMBER DEFAULT NULL,
      p_prod_or_ingr_scale_type     IN VARCHAR2 DEFAULT NULL,
      p_yield_or_consumption_type   IN VARCHAR2 DEFAULT NULL,
      p_verify_flag                 IN VARCHAR2 DEFAULT NULL,
      p_error_msg                   IN VARCHAR2 DEFAULT NULL,
      p_routing_no                  IN VARCHAR2 DEFAULT NULL,
      p_material_assignment_step    IN VARCHAR2 DEFAULT NULL,
      p_operation_no                IN NUMBER DEFAULT NULL,
      p_at                          IN VARCHAR2 DEFAULT NULL,
      p_batch_number                IN NUMBER DEFAULT NULL);
END xxdbl_cer_item_upld_pkg;
/