CREATE TABLE W_RCV_TRANSACTIONS  
( 
    TRANSACTION_ID NUMBER,
    QUANTITY NUMBER,
    PRIMARY_QUANTITY NUMBER,
    PO_HEADER_ID NUMBER,
    PO_LINE_ID NUMBER,
    PO_LINE_LOCATION_ID NUMBER,
    TRANSACTION_TYPE NUMBER,
    LCM_SHIPMENT_LINE_ID NUMBER,
    CONSTRAINT RCV_TRX_PK PRIMARY KEY (TRANSACTION_ID)
); 


ALTER TABLE W_RCV_TRANSACTIONS 
ADD VENDOR_ID NUMBER;

ALTER TABLE
   W_RCV_TRANSACTIONS
MODIFY
(
   TRANSACTION_TYPE VARCHAR2(50)
);

CREATE TABLE W_PO_HEADERS_ALL  
( 
    PO_HEADER_ID NUMBER,
    SEGMENT1 VARCHAR2(20),
    VENDOR_ID NUMBER,
    CONSTRAINT PO_HDR_PK PRIMARY KEY (PO_HEADER_ID)
); 


CREATE TABLE W_AP_SUPPLIERS  
( 
    VENDOR_ID NUMBER,
    VENDOR_NAME VARCHAR2(100),
    CONSTRAINT AP_SUP_PK PRIMARY KEY (VENDOR_ID)
); 


CREATE TABLE W_PO_LINE_LOCATIONS_ALL  
( 
    QUANTITY NUMBER,
    QUANTITY_RECEIVED NUMBER,
    SHIP_TO_ORGANIZATION_ID NUMBER,
    LINE_LOCATION_ID NUMBER,
    PO_LINE_ID NUMBER,
    PO_HEADER_ID NUMBER,
    CONSTRAINT PLL_PK PRIMARY KEY (LINE_LOCATION_ID)
); 