/* Formatted on 1/27/2022 5:02:08 PM (QP5 v5.374) */
CREATE TABLE XX_APEX.XXAPEX_PO_TAX_DATA_HDR
(
    PO_TAX_ID            NUMBER,
    CREATION_DATE        DATE,
    CREATED_BY           NUMBER,
    LAST_UPDATE_DATE     DATE,
    LAST_UPDATED_BY      NUMBER,
    LAST_UPDATE_LOGIN    NUMBER,
    PO_NUMBER            VARCHAR2 (240 BYTE),
    COMPANY_CODE         VARCHAR2 (20 BYTE),
    UNIT_NAME            VARCHAR2 (240 BYTE),
    SUPPLIER_NAME        VARCHAR2 (240 BYTE),
    SUPPLIER_NUMBER      VARCHAR2 (30 BYTE),
    PURCHASING_GROUP     VARCHAR2 (240 BYTE),
    LC_NUMBER            VARCHAR2 (30 BYTE),
    CONSTRAINT PO_TAX_PK PRIMARY KEY (PO_TAX_ID)
);

CREATE OR REPLACE SYNONYM APPSRO.XXAPEX_PO_TAX_DATA_HDR FOR XX_APEX.XXAPEX_PO_TAX_DATA_HDR;

CREATE OR REPLACE SYNONYM APPS.XXAPEX_PO_TAX_DATA_HDR FOR XX_APEX.XXAPEX_PO_TAX_DATA_HDR;