/* Formatted on 8/11/2020 2:35:23 PM (QP5 v5.354) */
CREATE TABLE W_MSML_PRODUCTION_DETILS
(
    PRODUCTION_ID      INTEGER NOT NULL,
    CATEGORY_NAME      VARCHAR2 (10),
    PROCESS_TYPE       VARCHAR2 (50),
    PRODUCTION_DATE    VARCHAR2 (100),
    CONSTRAINT MSML_PRODUCTION_PK PRIMARY KEY (PRODUCTION_ID)
);


CREATE TABLE W_MSML_PRODUCTION_DETILS
(
  ROW_WID          INTEGER,
  PRODUCTION_ID    INTEGER                      NOT NULL,
  CATEGORY_NAME    VARCHAR2(10 BYTE),
  PROCESS_TYPE     VARCHAR2(50 BYTE),
  PRODUCTION_DATE  VARCHAR2(100 BYTE),
  PRODQTY          INTEGER,
  CONSTRAINT MSML_PRODUCTION_PK PRIMARY KEY (PRODUCTION_ID)
)