--30424100115
---222151

--1. 
SELECT * FROM MTL_MATERIAL_TRANSACTIONS
WHERE TRANSACTION_SOURCE_ID = &&PO_HEADER_ID
UNION
SELECT *
FROM mtl_material_transactions
WHERE transaction_action_id = 24
AND trx_source_line_id IN
( SELECT transaction_id FROM RCV_TRANSACTIONS
WHERE PO_HEADER_ID =&&PO_HEADER_ID
);

--2.
SELECT * FROM MTL_TRANSACTION_ACCOUNTS
WHERE TRANSACTION_ID IN
( SELECT TRANSACTION_ID FROM MTL_MATERIAL_TRANSACTIONS
WHERE TRANSACTION_SOURCE_ID = &&PO_HEADER_ID )
UNION
SELECT *
FROM MTL_TRANSACTION_ACCOUNTS
WHERE TRANSACTION_ID IN
(SELECT transaction_id
FROM mtl_material_transactions
WHERE transaction_action_id = 24
AND trx_source_line_id IN
( SELECT transaction_id FROM RCV_TRANSACTIONS
WHERE PO_HEADER_ID =&&PO_HEADER_ID
)
);

--3.
SELECT xal.*
FROM XLA_AE_LINES XAL
WHERE XAL.APPLICATION_ID = 707
AND xal.AE_HEADER_ID IN
( SELECT XAH.ae_header_id
FROM XLA_AE_HEADERS XAH
WHERE XAH.APPLICATION_ID =707
AND XAH.event_id IN
( SELECT EV.event_id
FROM apps.XLA_TRANSACTION_ENTITIES_UPG ENT,
XLA_EVENTS EV
WHERE ENT.APPLICATION_ID = 707
AND EV.APPLICATION_ID = 707
AND ENT.ENTITY_CODE = 'RCV_ACCOUNTING_EVENTS'
AND EV.ENTITY_ID = ENT.ENTITY_ID
AND (NVL(ENT.SOURCE_ID_INT_1,'-99'),ENT.ledger_id) IN
(SELECT RT.TRANSACTION_ID,cav.ledger_id
FROM RCV_TRANSACTIONS RT,
rcv_accounting_events rae,
cst_acct_info_v cav
WHERE RT.PO_HEADER_ID = &&PO_HEADER_ID
AND rae.organization_id = cav.organization_id
AND rae.rcv_transaction_id = rt.transaction_id)
)
);

--4.
SELECT xal.*
FROM XLA_AE_LINES XAL
WHERE XAL.APPLICATION_ID = 707
AND xal.AE_HEADER_ID IN
( SELECT XAH.ae_header_id
FROM XLA_AE_HEADERS XAH
WHERE XAH.APPLICATION_ID =707
AND XAH.event_id IN
( SELECT EV.event_id
FROM apps.XLA_TRANSACTION_ENTITIES_UPG ENT,
XLA_EVENTS EV
WHERE ENT.APPLICATION_ID = 707
AND EV.APPLICATION_ID = 707
AND ENT.ENTITY_CODE = 'MTL_ACCOUNTING_EVENTS'
AND EV.ENTITY_ID = ENT.ENTITY_ID
AND (NVL(ENT.SOURCE_ID_INT_1,'-99'),ENT.ledger_id) IN
(SELECT mmt.TRANSACTION_ID,cav.ledger_id
FROM RCV_TRANSACTIONS RT,
cst_acct_info_v cav,
mtl_material_transactions mmt
WHERE RT.PO_HEADER_ID = &&PO_HEADER_ID
AND mmt.organization_id = cav.organization_id
AND mmt.trx_source_line_id = rt.transaction_id
AND mmt.transaction_action_id = 24 )
)
)
UNION
SELECT xal.*
FROM XLA_AE_LINES XAL
WHERE XAL.APPLICATION_ID = 707
AND xal.AE_HEADER_ID IN
( SELECT XAH.ae_header_id
FROM XLA_AE_HEADERS XAH
WHERE XAH.APPLICATION_ID =707
AND XAH.event_id IN
( SELECT EV.event_id
FROM apps.XLA_TRANSACTION_ENTITIES_UPG ENT,
XLA_EVENTS EV
WHERE ENT.APPLICATION_ID = 707
AND EV.APPLICATION_ID = 707
AND ENT.ENTITY_CODE = 'MTL_ACCOUNTING_EVENTS'
AND EV.ENTITY_ID = ENT.ENTITY_ID
AND (NVL(ENT.SOURCE_ID_INT_1,'-99'),ENT.ledger_id) IN
(SELECT mmt.TRANSACTION_ID,cav.ledger_id
FROM RCV_TRANSACTIONS RT,
cst_acct_info_v cav,
mtl_material_transactions mmt
WHERE RT.PO_HEADER_ID = &&PO_HEADER_ID
AND mmt.organization_id = cav.organization_id
AND mmt.rcv_transaction_id = rt.transaction_id)
)
);

--5.
 SELECT * FROM RCV_TRANSACTIONS
WHERE PO_HEADER_ID =&&PO_HEADER_ID;

--6.
 SELECT * FROM RCV_ACCOUNTING_EVENTS
WHERE PO_HEADER_ID =&&PO_HEADER_ID;