/* Formatted on 12/6/2020 11:09:49 AM (QP5 v5.287) */
CREATE OR REPLACE SYNONYM APPS.XXDBL_COMM_INV_HEADERS FOR XXDBL.XXDBL_COMM_INV_HEADERS;


CREATE OR REPLACE PUBLIC SYNONYM XXDBL_COMM_INV_HEADERS FOR XXDBL.XXDBL_COMM_INV_HEADERS;

ALTER TABLE XXDBL.XXDBL_COMM_INV_HEADERS
   ADD (CH_REQ_DT DATE,
        CH_SEND_DT DATE,
        CH_RCV_DT DATE,
        DT_TO_SALES_SEVC DATE,
        DT_TO_SALES_SEVC_DEL VARCHAR2 (500 BYTE),
        DT_TO_CUST DATE,
        DT_TO_CUST_DEL_RES VARCHAR2 (500 BYTE),
        DT_FROM_CUST DATE,
        DT_TO_BANK DATE,
        B2B_ACCT_DT DATE,
        MATURITY_DT DATE,
        DECRIPENCY_DETL VARCHAR2 (500 BYTE),
        DECRIPENCY_AMNT NUMBER,
        REALIZED_DT DATE,
        REALIZED_AMNT NUMBER,
        BILL_ENTRY_NO VARCHAR2 (100 BYTE),
        BILL_ENTRY_DT DATE,
        CUST_ACCT_SIGN_DT DATE,
        EXP_NO VARCHAR2 (100 BYTE),
        EXP_DT DATE,
        EXP_EXPIRE_DT DATE,
        EXP_VAL NUMBER,
        EXP_QTY NUMBER,
        UD_IP_NO VARCHAR2 (100 BYTE),
        UD_IP_RCV_DT DATE,
        UD_IP_HND_OVR_DT DATE,
        UD_IP_ISSUE_DT DATE,
        UD_IP_EXP_DT DATE,
        UD_IP_VAL NUMBER,
        UD_IP_QTY NUMBER,
        UD_ISSUE_DT DATE,
        UD_VAL NUMBER,
        UD_QTY NUMBER,
        INFO_REMARKS VARCHAR2 (500 BYTE));



SELECT * FROM xxdbl.xxdbl_comm_inv_headers;