CREATE TABLE XX_APEX.XX_APEX_CNF_JOB_DETAILS
(
  JOB_DETAILS_ID    NUMBER GENERATED ALWAYS AS IDENTITY ( START WITH 999 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 NOORDER NOKEEP) NOT NULL,
  JOB_MASTER_ID     NUMBER,
  EXPENSE_LIST_ID   NUMBER,
  AMOUNT            NUMBER,
  DAMURRAGE_AMOUNT  NUMBER,
  EXPENSE_ITEM_QTY  NUMBER,
  REMARKS           VARCHAR2(4000 BYTE),
  CREATED_BY        NUMBER,
  CREATION_DATE     DATE,
  LAST_UPDATED_BY   NUMBER,
  LAST_UPDATE_DATE  DATE,
  ATTRIBUTE1        VARCHAR2(255 BYTE),
  ATTRIBUTE2        VARCHAR2(255 BYTE),
  ATTRIBUTE3        VARCHAR2(255 BYTE),
  ATTRIBUTE4        VARCHAR2(255 BYTE),
  ATTRIBUTE5        VARCHAR2(255 BYTE)
);


CREATE UNIQUE INDEX XX_APEX.XX_APEX_CNF_JOB_DETAILS_PK ON XX_APEX.XX_APEX_CNF_JOB_DETAILS
(JOB_DETAILS_ID);

ALTER TABLE XX_APEX.XX_APEX_CNF_JOB_DETAILS ADD (
  CONSTRAINT XX_APEX_CNF_JOB_DETAILS_PK
  PRIMARY KEY
  (JOB_DETAILS_ID)
  USING INDEX XX_APEX.XX_APEX_CNF_JOB_DETAILS_PK
  ENABLE VALIDATE);



CREATE OR REPLACE PUBLIC SYNONYM XX_APEX_CNF_JOB_DETAILS FOR XX_APEX.XX_APEX_CNF_JOB_DETAILS;


ALTER TABLE XX_APEX.XX_APEX_CNF_JOB_DETAILS ADD (
  CONSTRAINT XX_APEX_CNF_JOB_DETAILS_FK 
  FOREIGN KEY (JOB_MASTER_ID) 
  REFERENCES XX_APEX.XX_APEX_CNF_JOB_MASTER (JOB_MASTER_ID)
  ON DELETE CASCADE
  ENABLE VALIDATE);
