Object List
-----------------------------------

TABLE
---------------
XX_APEX_CNF_EXPENSE_LIST
XX_APEX_CNF_JOB_MASTER
XX_APEX_CNF_JOB_DETAILS
XX_APEX_MENU_LIST
XX_APEX_MENU_MODULE
XX_APEX_MENU_PERMISSION
HR_OPERATING_UNITS

Package
--------------
XX_APEX_PKG_CNF_JOB_ENTRY