/* Formatted on 7/29/2020 5:15:52 PM (QP5 v5.287) */
SELECT L.CUST_TRX_TYPE_NAME,
       DECODE (L.CUST_TRX_TYPE_NAME,
               'Invoice', '1',
               'Credit Memo', '2',
               'Projects Credit Memo', '7',
               'Projects Invoice', '8',
               'Waxing Income Inv.', '42186',
               'Intercompany', '20',
               'Invoice-OKL', '21',
               'Credit Memo-OKL', '22',
               'Investor-OKL', '23',
               'Intercompany CM', '24',
               'Rental Income CM', '1053',
               'Twisting Income CM', '1147',
               'Raw Cotton Sales CM', '1149',
               'Yarn Sales CM', '1151',
               'Insurance Claim INV', '1351',
               'Scraps Sales DM', '1417',
               'Scraps Sales CM', '1471',
               'Rental Income DM', '1553',
               'Twisting Income DM', '1649',
               'Raw Cotton Sales DM', '1651',
               'Yarn Sales DM', '1653',
               'Insurance Claim CM', '1735',
               'Sub-Contract CM', '1797',
               'Sub-Contract INV', '1885',
               'Scraps Sales INV', '1921',
               'Rental Income INV', '2033',
               'Twisting Income INV', '2127',
               'Raw Cotton Sales INV', '2129',
               'Yarn Sales INV', '2131',
               'Insurance Claim DM', '2213',
               'Sub-Contract DM', '2281',
               'Raw Cotton Sales', '3000',
               'Realization Adj.', '3037',
               'Open Invoice', '5037',
               'Open CN', '5108',
               'Yarn Sales INV-(Mel)', '7116',
               'Yarn Sales INV-(Syn)', '7117',
               'Rewinding Income INV', '7118',
               'Yarn Sales CM-(Mel)', '8118',
               'Yarn Sales CM-(Syn)', '8119',
               'Others Income INV', '11152',
               'Others Income CM', '12141',
               'Other Income INV', '13139',
               'Interest Income FDR', '16169',
               -99),
       L.INVOICING_RULE_NAME,
       DECODE (L.INVOICING_RULE_NAME,
               'Arrears Invoice', '-3',
               'Advance Invoice', '-2',
               NULL, NULL,
               -99),
       L.TERM_NAME,
       DECODE (L.TERM_NAME,
               '30 NET', '4',
               'IMMEDIATE', '5',
               '60 NET', '1000',
               '90 NET', '1001',
               '180 NET', '1002',
               '45 NET', '1003',
               '120 NET', '1004',
               'AT SIGHT', '2004',
               NULL, NULL,
               -99),
       L.UOM_NAME,
       DECODE (L.UOM_NAME,
               'Vial', 'VL',
               'Bucket', 'BKT',
               'Ban', 'BND',
               'Can', 'CAN',
               'Mili Liter', 'ML',
               'Centi Meter', 'CMT',
               'Coil', 'COL',
               'Cone', 'CON',
               'Drum', 'DRM',
               'Feet', 'FT',
               'Gallon', 'GLN',
               'Gram', 'GM',
               'Gross', 'GRS',
               'Guti', 'GTI',
               'LBS', 'LBS',
               'Link', 'LNK',
               'Milligram', 'MG',
               'Reel', 'REL',
               'Ream', 'RIM',
               'Sheet', 'SHT',
               'Tin', 'TIN',
               'Tube', 'TUB',
               'Bundle', 'BUN',
               'Square Meter', 'SQM',
               'Number', 'NO',
               'Meter', 'MTR',
               'Liter', 'LTR',
               'Kilogram', 'KG',
               'Maunds', 'MND',
               'Metric Ton', 'MT',
               'Square Feet', 'SFT',
               'Square Inch', 'SQI',
               'Bag', 'BAG',
               'Bale', 'BL',
               'Bottle', 'BTL',
               'Box', 'BOX',
               'Cotta', 'COT',
               'Cylinder', 'CYL',
               'Jar', 'JAR',
               'Lot', 'LOT',
               'Number Of Service', 'NOS',
               'Packet', 'PKT',
               'Pair', 'PAR',
               'Piece', 'PCS',
               'Point', 'PNT',
               'Pot', 'POT',
               'Roll', 'ROL',
               'Set', 'SET',
               'Running Feet', 'RFT',
               'Yard', 'YRD',
               'Cubic Feet', 'CFT',
               'Meter Cube', 'M3',
               'Min', 'MIN',
               'Quarter', 'QAT',
               'Grain', 'GR',
               'Thousand', 'TH',
               'Unit', 'UNT',
               'Daily', 'DAY',
               'Bi-Weekly', 'BWK',
               'Yearly', 'YR',
               'Quarterly', 'QTR',
               'Half Yearly', 'HYR',
               'Weekly', 'WK',
               'Monthly', 'MTH',
               'Counting', 'CNT',
               'Job', 'JOB',
               'Decimal', 'DCM',
               'GG', 'GG',
               'Hour', 'HR',
               'Inch', 'INC',
               'Container', 'CTR',
               'Dozen', 'DOZ',
               'Carton', 'CTN',
               NULL, NULL,
               -99),
       L.AGREEMENT_NAME,
       DECODE (L.AGREEMENT_NAME, NULL, NULL, -99),
       L.FOB_POINT,
       DECODE (L.FOB_POINT,
               'BUY', 'BUY',
               'CUSTOMER SITE', 'CUSTOMER SITE',
               'FACTORY', 'FACTORY',
               'LOAD', 'LOAD',
               'SEL', 'SEL',
               'SHIP POINT', 'SHIP POINT',
               NULL, NULL,
               -99),
       L.ACCOUNTING_RULE_NAME,
       DECODE (L.ACCOUNTING_RULE_NAME,  'Immediate', '1',  NULL, NULL,  -99),
       L.MEMO_LINE_NAME,
       DECODE (L.MEMO_LINE_NAME,
               'Chargeback Line', '1',
               'Debit Memo Receipt Reversal', '2',
               'Intercompany Freight', '8',
               'Global Intercompany', '9',
               NULL, NULL,
               -99),
       DECODE (
          L.LINE_TYPE,
          'LINE', DECODE (
                     DECODE (
                        AOL.MINIMUM_ACCOUNTABLE_UNIT,
                        NULL, ROUND (L.UNIT_SELLING_PRICE * L.QUANTITY,
                                     AOL.PRECISION),
                          ROUND (
                               L.UNIT_SELLING_PRICE
                             * L.QUANTITY
                             / AOL.MINIMUM_ACCOUNTABLE_UNIT)
                        * AOL.MINIMUM_ACCOUNTABLE_UNIT),
                     AMOUNT, NULL,
                     NULL, NULL,
                     -99),
          NULL),
       L.RECEIPT_METHOD_NAME,
       DECODE (L.RECEIPT_METHOD_NAME,
               'CCL1-KNIT Bank Receipts', '4012',
               'CCL2 Bank Receipts', '4013',
               'JFL-RMG Bank Receipts', '4031',
               'PLC-RMG Bank Receipts', '9000',
               'Manual Bank Receipts', '1000',
               'DTTL Bank Receipts', '8000',
               'JKL-EMB Bank Receipts', '11000',
               'DBL-KNIT Bank Receipts', '4014',
               'DBL-RMG Bank Receipts', '4015',
               'MTL Bank Receipts', '4016',
               'MFL-KNIT Bank Receipts', '4017',
               'MFL-RMG Bank Receipts', '4018',
               'DEZL Bank Receipts', '12000',
               'ASL Bank Receipts', '3000',
               'CEL Bank Receipts', '3001',
               'CTSL Bank Receipts', '3002',
               'DSL Bank Receipts', '3003',
               'DREDGING Bank Receipts', '4000',
               'DBLPHARMA Bank Receipts', '4001',
               'NSL Bank Receipts', '4002',
               'JSL Bank Receipts', '4003',
               'TTSL Bank Receipts', '4004',
               'TPWL Bank Receipts', '4005',
               'DBLCL Bank Receipts', '4006',
               'DBLTL Bank Receipts', '4007',
               'DBTL Bank Receipts', '4008',
               'DDL Bank Receipts', '4009',
               'DBT Bank Receipts', '4010',
               'CCL1 Bank Receipts', '4011',
               'JAL-RMG Bank Receipts', '4029',
               'JKL-RMG Bank Receipts', '4032',
               'AP/AR Netting(1)', '-1',
               'Receipt - Clearing (Dummy)', '1001',
               'Receipts - Cash', '1002',
               'JKL-KNIT Bank Receipts', '4033',
               'JKL-KNIT', '4034',
               'HTL-2 DYEING Bank Receipts', '10000',
               'PPPL-ACCESSORIES Bank Receipts', '4019',
               'PPPL-PACKING Bank Receipts', '4020',
               'MSML Bank Receipts', '4021',
               'FFL-KNIT Bank Receipts', '4022',
               'FFL-RMG Bank Receipts', '4023',
               'HTL-DYEING Bank Receipts', '4024',
               'HTL-KNIT Bank Receipts', '4025',
               'HTL-WASHING Bank Receipts', '4026',
               'JFL-KNIT Bank Receipts', '4030',
               'AP/AR Netting', '1',
               'DDSL Bank Receipts', '6000',
               'DLL Bank Receipts', '6001',
               'JKL-PRNT Bank Receipts', '7000',
               'DBL Cash Clearing', '2000',
               'JAL-EMB Bank Receipts', '4027',
               'JAL-KNIT Bank Receipts', '4028',
               'DHL Bank Receipts', '5000',
               NULL, NULL,
               -99),
       L.LINE_TYPE,
       DECODE (L.LINE_TYPE,
               'CHARGES', 'CHARGES',
               'FREIGHT', 'FREIGHT',
               'LINE', 'LINE',
               'TAX', 'TAX',
               -99),
       L.CONVERSION_TYPE,
       DECODE (L.CONVERSION_TYPE,
               '1000', '1000',
               '1061', '1061',
               'Corporate', 'Corporate',
               'EMU FIXED', 'EMU FIXED',
               'Spot', 'Spot',
               'User', 'User',
               NULL, NULL,
               -99),
       L.PRIMARY_SALESREP_NUMBER,
       DECODE (L.PRIMARY_SALESREP_NUMBER,  '-3', '-3',  NULL, NULL,  -99),
       L.PRINTING_OPTION,
       DECODE (L.PRINTING_OPTION,
               'NOT', 'NOT',
               'PRI', 'PRI',
               NULL, NULL,
               -99),
       DECODE (
          L.AMOUNT,
          NULL, NULL,
          DECODE (
               L.AMOUNT
             - DECODE (
                  AOL.MINIMUM_ACCOUNTABLE_UNIT,
                  NULL, ROUND (L.AMOUNT, AOL.PRECISION),
                    ROUND (L.AMOUNT / AOL.MINIMUM_ACCOUNTABLE_UNIT)
                  * AOL.MINIMUM_ACCOUNTABLE_UNIT),
             0, NULL,
             -99)),
       DECODE (T.ALLOW_FREIGHT_FLAG,
               'N', DECODE (L.LINE_TYPE, 'FREIGHT', -99, NULL),
               NULL),
       L.SET_OF_BOOKS_ID,
       DECODE (L.SET_OF_BOOKS_ID,  '2095', '2095',  NULL, NULL,  -99),
       L.CREDIT_METHOD_FOR_ACCT_RULE,
       DECODE (L.CREDIT_METHOD_FOR_ACCT_RULE,
               'LIFO', 'LIFO',
               'PRORATE', 'PRORATE',
               'UNIT', 'UNIT',
               NULL, NULL,
               -99),
       L.CREDIT_METHOD_FOR_INSTALLMENTS,
       DECODE (L.CREDIT_METHOD_FOR_INSTALLMENTS,
               'FIFO', 'FIFO',
               'LIFO', 'LIFO',
               'PRORATE', 'PRORATE',
               NULL, NULL,
               -99),
       DECODE (L.LINK_TO_LINE_ID,
               NULL, DECODE (L.TRX_NUMBER, NULL, NULL, -99),
               NULL),
       DECODE (
          T.TYPE,
          'CM', DECODE (L.TERM_ID,
                        NULL, DECODE (L.TERM_NAME, NULL, NULL, -99),
                        -99),
          NULL),
       DECODE (
          T.TYPE,
          'CM', DECODE (
                   L.REFERENCE_LINE_ID,
                   NULL, DECODE (
                            L.REFERENCE_LINE_CONTEXT,
                            NULL, DECODE (
                                     NVL (TO_CHAR (L.INVOICING_RULE_ID),
                                          L.INVOICING_RULE_NAME),
                                     NULL, NULL,
                                     -99),
                            NULL),
                   NULL),
          NULL),
       DECODE (
          T.TYPE,
          'CM', DECODE (L.RELATED_CUSTOMER_TRX_ID,
                        NULL, DECODE (L.RELATED_TRX_NUMBER, NULL, NULL, -99),
                        -99),
          NULL),
       DECODE (
          T.TYPE,
          'CM', NULL,
          DECODE (L.LINK_TO_LINE_ID,
                  NULL, DECODE (L.TERM_NAME, NULL, -99, NULL))),
       DECODE (UPPER (L.CONVERSION_TYPE),
               'USER', DECODE (L.CONVERSION_RATE, NULL, -99, NULL),
               NULL),
       DECODE (UPPER (L.CONVERSION_TYPE),
               'USER', NULL,
               DECODE (L.CONVERSION_RATE, NULL, NULL, -99)),
       DECODE (L.ACCOUNTING_RULE_NAME,
               NULL, DECODE (L.INVOICING_RULE_NAME, NULL, NULL, -99),
               DECODE (L.INVOICING_RULE_NAME, NULL, -99)),
       DECODE (
          L.LINE_TYPE,
          'TAX', DECODE (L.AMOUNT,
                         NULL, DECODE (L.TAX_RATE, NULL, -99, NULL),
                         NULL),
          NULL),
       DECODE (L.LINE_TYPE,
               'LINE', DECODE (L.LINK_TO_LINE_ID, NULL, NULL, -99),
               'CHARGES', DECODE (L.LINK_TO_LINE_ID, NULL, NULL, -99),
               NULL),
       DECODE (L.LINE_TYPE,
               'TAX', DECODE (L.LINK_TO_LINE_ID, NULL, -99, NULL),
               NULL),
       DECODE (L.MEMO_LINE_NAME,
               NULL, NULL,
               DECODE (L.MTL_SYSTEM_ITEMS_SEG1, NULL, NULL, -99)),
       DECODE (L.RELATED_TRX_NUMBER,
               NULL, DECODE (L.RELATED_BATCH_SOURCE_NAME, NULL, NULL, -99),
               DECODE (L.RELATED_BATCH_SOURCE_NAME, NULL, -99, NULL)),
       DECODE (
          L.LINE_TYPE,
          'LINE', DECODE (L.CREDIT_METHOD_FOR_ACCT_RULE,
                          'UNIT', DECODE (L.QUANTITY, NULL, -99, NULL),
                          NULL),
          NULL),
       DECODE (
          L.LINE_TYPE,
          'TAX', DECODE (
                    T.TYPE,
                    'CM', NULL,
                    DECODE (
                       L.TAX_CODE,
                       NULL, DECODE (
                                   L.TAX_REGIME_CODE
                                || L.TAX
                                || L.TAX_STATUS_CODE
                                || L.TAX_RATE_CODE
                                || L.TAX_JURISDICTION_CODE,
                                NULL, -99,
                                NULL),
                       NULL)),
          NULL),
       DECODE (
          L.LINE_TYPE,
          'CHARGES', DECODE (
                        L.INVOICING_RULE_ID,
                        NULL, DECODE (
                                 L.INVOICING_RULE_NAME,
                                 NULL, DECODE (
                                          L.ACCOUNTING_RULE_ID,
                                          NULL, DECODE (
                                                   L.ACCOUNTING_RULE_NAME,
                                                   NULL, NULL,
                                                   -99),
                                          -99),
                                 -99),
                        -99),
          NULL),
       DECODE (
          L.LINE_TYPE,
          'CHARGES', DECODE (L.UOM_CODE,
                             NULL, DECODE (L.UOM_NAME, NULL, NULL, -99),
                             -99),
          NULL),
       DECODE (L.LINE_TYPE,
               'CHARGES', DECODE (L.QUANTITY,  1, NULL,  -1, NULL,  -99),
               NULL),
       DECODE (L.LINE_TYPE,
               'CHARGES', DECODE (T.TYPE,  'CM', NULL,  'DM', NULL,  -99),
               NULL),
       DECODE (T.POST_TO_GL, 'N', DECODE (L.GL_DATE, NULL, NULL, -99), NULL),
       L.TAX_EXEMPT_FLAG,
       DECODE (L.TAX_EXEMPT_FLAG,
               'E', 'E',
               'R', 'R',
               'S', 'S',
               NULL, NULL,
               -99),
       L.TAX_EXEMPT_REASON_CODE_MEANING,
       DECODE (L.TAX_EXEMPT_REASON_CODE_MEANING,
               'education', 'EDUCATION',
               'hospital', 'HOSPITAL',
               'manufacturer', 'MANUFACTURER',
               'R10upgrade', 'R10UPGRADE',
               'resale', 'RESALE',
               'research', 'RESEARCH',
               NULL, NULL,
               -99),
       DECODE (
          L.LINE_TYPE,
          'LINE', DECODE (
                     L.TAX_EXEMPT_FLAG,
                     'E', DECODE (
                             L.TAX_EXEMPT_REASON_CODE,
                             NULL, DECODE (L.TAX_EXEMPT_REASON_CODE_MEANING,
                                           NULL, -99,
                                           NULL),
                             NULL),
                     NULL),
          NULL),
       DECODE (L.INTERFACE_LINE_CONTEXT, NULL, -99, NULL),
       L.INTERFACE_LINE_ID
  FROM RA_INTERFACE_LINES_GT L, RA_CUST_TRX_TYPES T, FND_CURRENCIES AOL
 WHERE     L.REQUEST_ID = :b1
       AND L.CUST_TRX_TYPE_NAME = T.NAME(+)
       AND L.CURRENCY_CODE = AOL.CURRENCY_CODE(+);
       
       
       SELECT C.ROWID,
L.INTERFACE_LINE_ID,
L.REQUEST_ID,
L.LAST_UPDATE_LOGIN, 
L.LAST_UPDATED_BY
FROM  AR_INTERFACE_CONTS C,
      RA_INTERFACE_LINES_GT L
WHERE  L.REQUEST_ID = :b1
AND    L.LINE_TYPE = 'LINE'
AND    L.INTERFACE_LINE_CONTEXT = 'DBL_IC_INVOICE'
AND    L.INTERFACE_LINE_CONTEXT = C.INTERFACE_LINE_CONTEXT
AND    L.INTERFACE_LINE_ATTRIBUTE1 = C.INTERFACE_LINE_ATTRIBUTE1
AND    L.INTERFACE_LINE_ATTRIBUTE2 = C.INTERFACE_LINE_ATTRIBUTE2
AND    L.INTERFACE_LINE_ATTRIBUTE3 = C.INTERFACE_LINE_ATTRIBUTE3
AND    L.INTERFACE_LINE_ATTRIBUTE4 = C.INTERFACE_LINE_ATTRIBUTE4
AND    L.INTERFACE_LINE_ATTRIBUTE5 = C.INTERFACE_LINE_ATTRIBUTE5

SELECT
  D.ROWID,
  L.INTERFACE_LINE_ID,
  L.REQUEST_ID,
  L.LAST_UPDATE_LOGIN, 
  L.LAST_UPDATED_BY
FROM  RA_INTERFACE_DISTRIBUTIONS D,
      RA_INTERFACE_LINES_GT L
WHERE  L.REQUEST_ID = :b1
AND    L.INTERFACE_LINE_CONTEXT = 'DBL_IC_INVOICE'
AND    L.INTERFACE_LINE_CONTEXT = D.INTERFACE_LINE_CONTEXT
AND    L.INTERFACE_LINE_ATTRIBUTE1 = D.INTERFACE_LINE_ATTRIBUTE1
AND    L.INTERFACE_LINE_ATTRIBUTE2 = D.INTERFACE_LINE_ATTRIBUTE2
AND    L.INTERFACE_LINE_ATTRIBUTE3 = D.INTERFACE_LINE_ATTRIBUTE3
AND    L.INTERFACE_LINE_ATTRIBUTE4 = D.INTERFACE_LINE_ATTRIBUTE4
AND    L.INTERFACE_LINE_ATTRIBUTE5 = D.INTERFACE_LINE_ATTRIBUTE5