/* Formatted on 7/13/2019 10:51:00 AM (QP5 v5.287) */
  SELECT OOD.OPERATING_UNIT ORG_ID,
         HOU.NAME OPERATING_UNIT,
         OOD.ORGANIZATION_NAME,
         OOD.ORGANIZATION_CODE WHAREHOUSE_ORG_CODE,
         GMD.SUBINVENTORY,
         GBH.BATCH_NO,
         (SELECT MEANING FROM APPS.FND_LOOKUP_VALUES FLV WHERE FLV.LOOKUP_TYPE='BATCH_STATUS' AND TO_CHAR(GBH.BATCH_STATUS)=TO_CHAR(FLV.LOOKUP_CODE)) BATCH_STATUS,
         (SELECT MEANING FROM APPS.GEM_LOOKUPS GL WHERE GL.LOOKUP_TYPE='LINE_TYPE' AND TO_CHAR(GMD.LINE_TYPE)=TO_CHAR(GL.LOOKUP_CODE)) LINE_TYPE,
         MLN.LOT_NUMBER,
         MSIB.INVENTORY_ITEM_ID,
         MSIB.SEGMENT1 || '.' || MSIB.SEGMENT2 || '.' || MSIB.SEGMENT3 ITEM_CODE,
         MSIB.DESCRIPTION ITEM_DESCRIPTION,
         GMD.ACTUAL_QTY,
         MMT.TRANSACTION_QUANTITY,
         --NVL (SUM (MTLN.TRANSACTION_QUANTITY), 0) TRX_QTY,
         TO_CHAR (GMD.MATERIAL_REQUIREMENT_DATE) REQUIREMENT_DATE,
         CASE WHEN GMD.LINE_TYPE = '-1' THEN GMD.ACTUAL_QTY END Ingredients_Quantity,
         CASE WHEN GMD.LINE_TYPE = '1' THEN GMD.ACTUAL_QTY END Product_Quantity,
         CASE WHEN GMD.LINE_TYPE = '2' THEN GMD.ACTUAL_QTY END ByProduct_Quantity,
         GMD.DTL_UM UOM,
         MC.SEGMENT2 COIL_TYPE,
         MTT.TRANSACTION_TYPE_NAME,
         FFMB.FORMULA_NO,
         FFMB.FORMULA_DESC1 FORMULA_DESCRIPTION,
         GR.RECIPE_NO,
         GR.RECIPE_DESCRIPTION,
         GBSR.RESOURCES,
         GBSR.COST_ANALYSIS_CODE,
         GBSA.ACTIVITY,
         GAV.ACTIVITY_DESC,
         GOV.OPRN_DESC,
         GOV.OPERATION_STATUS,
         GS.MEANING STATUS_MEANING,
         GS.DESCRIPTION STATUS_DESCRIPTION,
         MTLN.GRADE_CODE
         --,GOR.*
         --,MTLV.*
         --,GOV.*
         --,GOA.*
         --,GBS.*
         --,GOA.*
         --,GBSA.*
         --,GBSR.*
         --,GBHS.*
         --,MTRL.*
         --,GRVR.*
         --,GR.*
         --,FMD.*
         --,GBH.*
         --,GMD.*
         --MMT.*
         --MTT.*
         --,MTLN.*
    FROM APPS.GME_BATCH_STEP_RESOURCES GBSR,
         APPS.GME_BATCH_HEADER GBH,
         APPS.GME_BATCH_STEPS GBS,
         APPS.GME_BATCH_STEP_ACTIVITIES GBSA,
         APPS.GMD_ACTIVITIES_VL GAV,
         APPS.GMD_OPERATION_ACTIVITIES GOA,
         APPS.GMD_OPERATIONS_VL GOV,
         APPS.GMD_OPERATION_RESOURCES GOR,
         APPS.GMD_ROUTINGS GRT,
         APPS.GME_BATCH_HISTORY GBHS,
         APPS.GMD_STATUS GS,
         APPS.GME_MATERIAL_DETAILS GMD,
         APPS.HR_OPERATING_UNITS HOU,
         APPS.ORG_ORGANIZATION_DEFINITIONS OOD,
         INV.MTL_PARAMETERS MP,
         INV.MTL_TRANSACTION_TYPES MTT,
         INV.MTL_MATERIAL_TRANSACTIONS MMT,
         INV.MTL_ITEM_CATEGORIES MIC,
         INV.MTL_CATEGORIES_B MC,
         INV.MTL_SYSTEM_ITEMS_B MSIB,
         INV.MTL_TRANSACTION_LOT_NUMBERS MTLN,
         INV.MTL_LOT_NUMBERS MLN,
         APPS.MTL_TRANSACTION_LOT_VAL_V MTLV,
         APPS.FM_FORM_MST_B FFMB,
         APPS.FM_MATL_DTL FMD,
         APPS.GMD_RECIPES GR,
         APPS.GMD_RECIPE_VALIDITY_RULES GRVR,
         INV.MTL_TXN_REQUEST_HEADERS MTRH,
         INV.MTL_TXN_REQUEST_LINES MTRL,
         APPS.MTL_TXN_REQUEST_HEADERS_V MTRHV
   WHERE     1 = 1
         AND MMT.TRANSACTION_ID = MTLV.TRANSACTION_ID
         AND MMT.ORGANIZATION_ID = MTLV.ORGANIZATION_ID
         AND MLN.ORGANIZATION_ID = MTLN.ORGANIZATION_ID
         AND MLN.INVENTORY_ITEM_ID = MTLN.INVENTORY_ITEM_ID
         AND MLN.LOT_NUMBER = MTLN.LOT_NUMBER
         AND MSIB.INVENTORY_ITEM_ID = MLN.INVENTORY_ITEM_ID
         AND MSIB.ORGANIZATION_ID = MLN.ORGANIZATION_ID
         AND MSIB.INVENTORY_ITEM_ID = MIC.INVENTORY_ITEM_ID
         AND MSIB.ORGANIZATION_ID = MIC.ORGANIZATION_ID
         AND MIC.CATEGORY_ID = MC.CATEGORY_ID
         --AND MLN.LOT_NUMBER = '16M6RW09I16'
         AND MMT.TRANSACTION_SOURCE_TYPE_ID = 5
         AND MTLN.TRANSACTION_ID = MMT.TRANSACTION_ID
         AND MMT.TRANSACTION_TYPE_ID = MTT.TRANSACTION_TYPE_ID
         AND OOD.ORGANIZATION_ID = MLN.ORGANIZATION_ID
         AND GMD.ORGANIZATION_ID = MP.ORGANIZATION_ID
         AND OOD.OPERATING_UNIT = HOU.ORGANIZATION_ID
         AND OOD.OPERATING_UNIT = 126
         AND OOD.ORGANIZATION_CODE = '251'
         --AND MC.SEGMENT2 = 'ROLLING COIL'   -- 'PICKLED COIL'-- 'ROLLING COIL'
         AND MTT.TRANSACTION_TYPE_NAME='WIP Completion'
         --AND UPPER (MTT.TRANSACTION_TYPE_NAME) IN ('WIP COMPLETION', 'WIP COMPLETION RETURN')
         --AND UPPER (MTT.TRANSACTION_TYPE_NAME) IN ('WIP ISSUE', 'WIP RETURN')
         AND GMD.MATERIAL_DETAIL_ID = MMT.TRX_SOURCE_LINE_ID
         AND GBH.BATCH_ID = GMD.BATCH_ID
         AND GMD.BATCH_ID = GBSR.BATCH_ID
         --AND GMD.LINE_TYPE = '1'
         AND GBH.BATCH_NO = 3259
         AND FFMB.FORMULA_ID = GBH.FORMULA_ID
         AND FFMB.FORMULA_ID = FMD.FORMULA_ID
         AND FMD.LINE_TYPE=GMD.LINE_TYPE
         AND FMD.ORGANIZATION_ID = MSIB.ORGANIZATION_ID
         AND GR.FORMULA_ID = GBH.FORMULA_ID
         AND GR.ROUTING_ID = GBH.ROUTING_ID
         AND GRT.ROUTING_ID=GR.ROUTING_ID
         AND GBH.RECIPE_VALIDITY_RULE_ID = GRVR.RECIPE_VALIDITY_RULE_ID
         AND GRVR.RECIPE_ID = GR.RECIPE_ID
         AND MTRH.HEADER_ID=GBH.MOVE_ORDER_HEADER_ID
         AND MTRH.REQUEST_NUMBER=MTRHV.REQUEST_NUMBER
         AND MTRH.HEADER_ID=MTRL.HEADER_ID
         AND MSIB.INVENTORY_ITEM_ID = MTRL.INVENTORY_ITEM_ID
         AND GBH.BATCH_ID = GBS.BATCH_ID
         AND GBSA.BATCH_ID = GBS.BATCH_ID
         AND GBS.BATCHSTEP_ID = GBSA.BATCHSTEP_ID
         AND GBHS.BATCH_ID = GBS.BATCH_ID
         AND GBH.BATCH_STATUS=GBHS.NEW_STATUS
         AND GBSA.ACTIVITY=GAV.ACTIVITY
         AND GOA.ACTIVITY=GAV.ACTIVITY
         AND GOA.OPRN_ID=GBS.OPRN_ID
         AND GOA.OPRN_LINE_ID=GBSA.OPRN_LINE_ID
         AND GOV.OPRN_ID=GOA.OPRN_ID
         AND GOV.OPERATION_STATUS=GS.STATUS_CODE
         AND GOA.OPRN_LINE_ID=GOR.OPRN_LINE_ID
--------------------------------------------------------------------------------
--         AND MMT.TRANSACTION_SOURCE_ID = GBH.BATCH_ID
--         AND MMT.ORGANIZATION_ID = MTLN.ORGANIZATION_ID             --NOT NEED
--         AND OOD.ORGANIZATION_ID = MSIB.ORGANIZATION_ID
--         AND MIC.CATEGORY_SET_ID = 1                                        
--         AND GMD.LINE_TYPE = '1'                                            
--         AND MSIB.INVENTORY_ITEM_ID = GMD.INVENTORY_ITEM_ID                 
--         AND MSIB.ORGANIZATION_ID = GMD.ORGANIZATION_ID                     
--         AND GBH.ORGANIZATION_ID = MIC.ORGANIZATION_ID              --NOT NEED
--         AND OOD.ORGANIZATION_ID = GBH.ORGANIZATION_ID                      
--------------------------------------------------------------------------------
--GROUP BY OOD.OPERATING_UNIT,
--         HOU.NAME,
--         OOD.ORGANIZATION_NAME,
--         OOD.ORGANIZATION_CODE,
--         GMD.SUBINVENTORY,
--         GBH.BATCH_NO,
--         GBH.BATCH_STATUS,
--         GMD.LINE_TYPE,
--         MLN.LOT_NUMBER,
--         (MSIB.SEGMENT1 || '.' || MSIB.SEGMENT2 || '.' || MSIB.SEGMENT3),
--         MSIB.DESCRIPTION,
--         GMD.ACTUAL_QTY,
--         --       TO_CHAR (GMD.MATERIAL_REQUIREMENT_DATE) REQUIREMENT_DATE,
--         --       CASE WHEN GMD.LINE_TYPE = '-1' THEN GMD.ACTUAL_QTY END
--         --          Ingredients_Quantity,
--         --       CASE WHEN GMD.LINE_TYPE = '1' THEN GMD.ACTUAL_QTY END Product_Quantity,
--         --       CASE WHEN GMD.LINE_TYPE = '2' THEN GMD.ACTUAL_QTY END
--         --          ByProduct_Quantity,
--         GMD.DTL_UM,
--         GMD.MATERIAL_REQUIREMENT_DATE,
--         MTT.TRANSACTION_TYPE_NAME,
--         FFMB.FORMULA_NO,
--         FFMB.FORMULA_DESC1,
--         MC.SEGMENT2;
;
