/* Formatted on 1/12/2020 10:24:18 AM (QP5 v5.287) */
SELECT CAD.*
  FROM CM_ADJS_DTL CAD
  , CST_COST_TYPES CCT
  , MTL_SYSTEM_ITEMS_B MSI
 --,ORG_ORGANIZATION_DEFINITIONS OOD
 WHERE     1 = 1
       AND CAD.COST_TYPE_ID = CCT.COST_TYPE_ID(+)
       AND CAD.ORGANIZATION_ID = MSI.ORGANIZATION_ID(+)
       AND CAD.INVENTORY_ITEM_ID = MSI.INVENTORY_ITEM_ID(+)
       AND TRUNC(CAD.ADJUSTMENT_DATE) BETWEEN NVL(:P_DATE_FROM,TRUNC(CAD.ADJUSTMENT_DATE)) AND NVL(:P_DATE_TO,TRUNC(CAD.ADJUSTMENT_DATE))
--AND MSI.ORGANIZATION_ID = OOD.ORGANIZATION_ID