SELECT 11 SL,                                              --ADDED BY Majid
          XAL.APPLICATION_ID,
          'OPM_INV_RCV' JE_SOURCE,
          --GEH.ENTITY_CODE,
          XAH.JE_CATEGORY_NAME JE_CATEGORY,
          CC.SEGMENT1 COMPANY,
          CC.SEGMENT2 LOCATION,
          CC.SEGMENT3 PRODUCT_LINE,
          CC.SEGMENT4 COST_CENTER,
          CC.SEGMENT5 ACCOUNT,
          CC.SEGMENT6 SUB_ACCOUNT,
          CC.SEGMENT7 INTER_COMPANY,
          CC.SEGMENT8 EXPENSE_CATEGORY,
          CC.SEGMENT9 FUTURE,
          FLEX.DESCRIPTION ACCTDESC,
          (SELECT DESCRIPTION
             FROM FND_FLEX_VALUES_VL A
            WHERE A.FLEX_VALUE_SET_ID = 1017041
                  AND A.FLEX_VALUE = CC.SEGMENT6
                  AND PARENT_FLEX_VALUE_LOW =
                        (SELECT FLEX_VALUE
                           FROM FND_FLEX_VALUES_VL B
                          WHERE FLEX_VALUE_SET_ID = 1017040
                                AND B.FLEX_VALUE = CC.SEGMENT5))
             SUBACCDESC,
          TO_CHAR (NULL) VOUCHER_NUMBER_2,
          GEH.TRANSACTION_ID VOUCHER_NUMBER,
          GJH.DOC_SEQUENCE_VALUE GL_VOUCHER_NUMBER,
          GJL.JE_LINE_NUM GL_JE_LINE_NUM,
          XAL.ACCOUNTING_DATE VOUCHER_DATE,
          NULL PARTICULARS,
          NVL (XAL.ENTERED_DR, 0) ENTERED_DEBITS,
          NVL (XAL.ENTERED_CR, 0) ENTERED_CREDITS,
          SUM(XAL.ACCOUNTED_DR) ACCOUNTED_DR,
          XAL.ACCOUNTED_CR,
          NULL CHEQUE_NUMBER,
          TRUNC (SYSDATE) CHEQUE_DATE,
          APS.SEGMENT1 PARTY_CODE,
          APS.VENDOR_NAME PARTY_NAME,
          ENTITY_CODE TRANSACTION_TYPE,
          CC.CHART_OF_ACCOUNTS_ID,
          GJH.LEDGER_ID,
          NULL DFF_CONTEXT,
          NULL ATTRIBUTE1,
          NULL ATTRIBUTE2,
          NULL ATTRIBUTE3,
          NULL ATTRIBUTE4,
          NULL ATTRIBUTE5
          --,GEL.*
     FROM APPS.XLA_AE_LINES XAL,
          APPS.XLA_AE_HEADERS XAH,
          APPS.GL_IMPORT_REFERENCES GIR,
          APPS.GL_JE_LINES GJL,
          APPS.GL_JE_HEADERS GJH,
          APPS.FND_DOC_SEQUENCE_CATEGORIES CAT,
          APPS.GL_CODE_COMBINATIONS CC,
          APPS.FND_FLEX_VALUES_VL FLEX,
          APPS.MTL_SYSTEM_ITEMS_B MST,
          APPS.ORG_ORGANIZATION_DEFINITIONS ORG,
          APPS.MTL_ITEM_CATEGORIES MIC,
          APPS.MTL_CATEGORIES_B MCB,
          APPS.GMF_XLA_EXTRACT_HEADERS GEH,
          APPS.GMF_XLA_EXTRACT_LINES GEL,
          APPS.XLA_DISTRIBUTION_LINKS XDL,
          APPS.RCV_TRANSACTIONS RT,
          APPS.RCV_SHIPMENT_HEADERS RSH,
          APPS.RCV_SHIPMENT_LINES RSL,
          APPS.AP_SUPPLIERS APS
    WHERE     XDL.AE_HEADER_ID = XAH.AE_HEADER_ID
          AND XDL.AE_LINE_NUM = XAL.AE_LINE_NUM
          AND XAL.AE_HEADER_ID = XAH.AE_HEADER_ID
          AND XAL.GL_SL_LINK_ID = GIR.GL_SL_LINK_ID
          AND GIR.GL_SL_LINK_TABLE IN ('APECL', 'XLAJEL')
          AND GIR.JE_HEADER_ID = GJL.JE_HEADER_ID
          AND GIR.JE_LINE_NUM = GJL.JE_LINE_NUM
          AND GIR.JE_HEADER_ID = GJH.JE_HEADER_ID
          AND GJH.JE_HEADER_ID = GJL.JE_HEADER_ID
          AND GJL.CODE_COMBINATION_ID = CC.CODE_COMBINATION_ID
          AND GJH.JE_CATEGORY = CAT.CODE
          AND CAT.APPLICATION_ID = 101
          AND CC.SEGMENT5 = FLEX.FLEX_VALUE_MEANING
          AND GEH.ORGANIZATION_ID = MST.ORGANIZATION_ID
          AND GEH.INVENTORY_ITEM_ID = MST.INVENTORY_ITEM_ID
          AND GEH.ORGANIZATION_ID = ORG.ORGANIZATION_ID
          AND MIC.INVENTORY_ITEM_ID = MST.INVENTORY_ITEM_ID
          AND MIC.ORGANIZATION_ID = MST.ORGANIZATION_ID
          AND MCB.STRUCTURE_ID = 101
          AND MCB.CATEGORY_ID = MIC.CATEGORY_ID
          AND GJH.ACTUAL_FLAG = 'A'
          AND GJL.STATUS = 'P'
          AND (NVL (XAL.ACCOUNTED_DR, 0) <> 0
               OR NVL (XAL.ACCOUNTED_CR, 0) <> 0)
          AND GEH.HEADER_ID = GEL.HEADER_ID
          --AND GEH.LINE_ID = GEL.LINE_ID
          AND GEH.EVENT_ID = GEL.EVENT_ID
          AND XDL.SOURCE_DISTRIBUTION_TYPE = GEH.ENTITY_CODE
          AND XDL.EVENT_ID = GEH.EVENT_ID
          AND XDL.SOURCE_DISTRIBUTION_ID_NUM_1 = GEL.LINE_ID
          AND XDL.APPLICATION_ID = 555
          AND CATEGORY_SET_ID = 1
          AND GEH.SOURCE_LINE_ID(+) = RT.TRANSACTION_ID
          AND RSH.SHIPMENT_HEADER_ID = RSH.SHIPMENT_HEADER_ID
          AND RSH.SHIPMENT_HEADER_ID = RSL.SHIPMENT_HEADER_ID
          AND RSL.SHIPMENT_LINE_ID = RT.SHIPMENT_LINE_ID
          AND APS.VENDOR_ID = RSH.VENDOR_ID
          AND GEH.ENTITY_CODE = 'PURCHASING'
          and APS.SEGMENT1 = '10321'
          and GJH.LEDGER_ID = 2063
          and CC.SEGMENT5 = '128101'
          AND GEH.TRANSACTION_ID  = 368272
          and XAL.ACCOUNTING_DATE between '01-JUL2019' AND '30-JUN-2020'
          GROUP BY
          XAL.APPLICATION_ID,
          'OPM_INV_RCV',
          --GEH.ENTITY_CODE,
          XAH.JE_CATEGORY_NAME,
          CC.SEGMENT1,
          CC.SEGMENT2,
          CC.SEGMENT3,
          CC.SEGMENT4,
          CC.SEGMENT5,
          CC.SEGMENT6 ,
          CC.SEGMENT7 ,
          CC.SEGMENT8 ,
          CC.SEGMENT9 ,
          FLEX.DESCRIPTION ,
          CC.SEGMENT6,
          CC.SEGMENT5,
          TO_CHAR (NULL) ,
          GEH.TRANSACTION_ID ,
          GJH.DOC_SEQUENCE_VALUE ,
          GJL.JE_LINE_NUM ,
          XAL.ACCOUNTING_DATE ,
          NULL ,
          NVL (XAL.ENTERED_DR, 0) ,
          NVL (XAL.ENTERED_CR, 0) ,
          XAL.ACCOUNTED_CR,
          NULL ,
          TRUNC (SYSDATE) ,
          APS.SEGMENT1,
          APS.VENDOR_NAME ,
          ENTITY_CODE ,
          CC.CHART_OF_ACCOUNTS_ID,
          GJH.LEDGER_ID,
          NULL ,
          NULL ,
          NULL ,
          NULL ,
          NULL ,
          NULL 