SELECT 
       MSI.ORGANIZATION_ID,
       OOD.ORGANIZATION_CODE,
       OOD.ORGANIZATION_NAME,
       MSI.INVENTORY_ITEM_ID,
       MSI.SEGMENT1 ITEM_CODE,
       MSI.DESCRIPTION,
       MSI.PRIMARY_UOM_CODE,
       MSI.SECONDARY_UOM_CODE,
       MSI.ATTRIBUTE14 TEMPLATE_NAME,
       CAT.CATEGORY_SET_NAME CATEGORY_SET,
       CAT.CATEGORY_ID,
       CAT.SEGMENT1 LINE_OF_BUSINESS,
       CAT.SEGMENT2 ITEM_CATEGORY,
       CAT.SEGMENT3 ITEM_TYPE,
       CAT.SEGMENT4 CATELOG,
       CAT.CATEGORY_CONCAT_SEGS CATEGORY_SEGMENTS,
       MSI.CREATION_DATE
  --,MSI.*
  --,OOD.*
  --,CAT.*
  FROM APPS.MTL_SYSTEM_ITEMS_B MSI, APPS.ORG_ORGANIZATION_DEFINITIONS OOD, APPS.MTL_ITEM_CATEGORIES_V CAT
 WHERE     1 = 1
       AND MSI.ORGANIZATION_ID = OOD.ORGANIZATION_ID
       AND MSI.INVENTORY_ITEM_ID = CAT.INVENTORY_ITEM_ID
       AND MSI.ORGANIZATION_ID = CAT.ORGANIZATION_ID
       AND (   :P_OPERATING_UNIT IS NULL    OR (OOD.OPERATING_UNIT = :P_OPERATING_UNIT))
       AND (   :P_ORG_NAME IS NULL          OR (UPPER(OOD.ORGANIZATION_NAME) LIKE UPPER('%'||:P_ORG_NAME||'%') ))
       AND (   :P_ORGANIZATION_CODE IS NULL OR (OOD.ORGANIZATION_CODE = :P_ORGANIZATION_CODE))
       AND (   :P_ITEM_CODE IS NULL         OR (MSI.SEGMENT1 = :P_ITEM_CODE))
       AND (   :P_ITEM_DESC IS NULL         OR (UPPER(MSI.DESCRIPTION) LIKE UPPER('%'||:P_ITEM_DESC||'%') ))
       AND (   :P_ITEM_CATEGORIES IS NULL OR (UPPER( CAT.SEGMENT1||'.'||CAT.SEGMENT2||'.'||CAT.SEGMENT3||'.'||CAT.SEGMENT4) = UPPER (:P_ITEM_CATEGORIES)))
       AND (   :P_LINE_OF_BUSINESS IS NULL  OR (CAT.SEGMENT1 = :P_LINE_OF_BUSINESS))
       AND (   :P_MAJOR_CATEGORY IS NULL    OR (CAT.SEGMENT2 = :P_MAJOR_CATEGORY))
       AND (   :P_MINOR_CATEGORY IS NULL    OR (CAT.SEGMENT3 = :P_MINOR_CATEGORY))
       AND (   :P_ITEM_CATELOG IS NULL      OR (CAT.SEGMENT4 = :P_ITEM_CATELOG))
       AND MSI.INVENTORY_ITEM_STATUS_CODE='Active'
       --AND ORGANIZATION_CODE NOT IN ('IMO')
       --AND ORGANIZATION_CODE IN ('251')
       --AND OPERATING_UNIT IN (85)
       --AND MSI.INVENTORY_ITEM_ID IN ('7297')
       --AND MSI.SEGMENT1 IN ('FT-GP6060-038BK')
       --AND MSI.SEGMENT1 LIKE ('PUMA%')
       --AND MSI.DESCRIPTION IN ('40S1-COTTON-100%-CH ORGANIC')
       --AND MSI.PRIMARY_UOM_CODE='PCS'
       --AND MSI.ORGANIZATION_ID IN (101)
       AND CAT.CATEGORY_SET_ID=1
       --AND CAT.CATEGORY_ID='74551'
       --AND CAT.SEGMENT2 NOT IN ('FINISH GOODS')
       --AND CAT.SEGMENT2='BRND'
       --AND CAT.SEGMENT3='GIFT'
       --AND TO_CHAR(MSI.CREATION_DATE,'DD-MON-RR')>'05-MAR-21'
       AND MSI.ENABLED_FLAG = 'Y';

--------------------------------------------------------------------------------
     
 SELECT 
       MSI.ORGANIZATION_ID,
       MP.ORGANIZATION_CODE,
       MSI.INVENTORY_ITEM_ID,
       MSI.SEGMENT1 ITEM_CODE,
       MSI.DESCRIPTION,
       MSI.INVENTORY_ITEM_FLAG,
       MSI.CUSTOMER_ORDER_FLAG,
       MSI.CUSTOMER_ORDER_ENABLED_FLAG,
       MSI.INVOICE_ENABLED_FLAG,
       MSI.PURCHASING_ITEM_FLAG,
       MSI.SERVICE_ITEM_FLAG,
       MSI.PURCHASING_ENABLED_FLAG,
       MSI.STOCK_ENABLED_FLAG,
       MSI.LIST_PRICE_PER_UNIT,
       MSI.PRIMARY_UOM_CODE,
       MSI.PROCESS_COSTING_ENABLED_FLAG,
       MSI.PROCESS_YIELD_SUBINVENTORY,
       MSI.PROCESS_SUPPLY_SUBINVENTORY,
       MSI.INVENTORY_ASSET_FLAG
  --,MSI.*
  --,MP.*
  FROM MTL_SYSTEM_ITEMS_B MSI, MTL_PARAMETERS MP
 WHERE     1 = 1
       AND MSI.ORGANIZATION_ID = MP.ORGANIZATION_ID
       AND (   :P_ORGANIZATION_CODE IS NULL OR (MP.ORGANIZATION_CODE = :P_ORGANIZATION_CODE))
       AND (   :P_ITEM_CODE IS NULL OR (MSI.SEGMENT1 = :P_ITEM_CODE))
       AND     (:P_ITEM_DESC IS NULL OR (UPPER(MSI.DESCRIPTION) LIKE UPPER('%'||:P_ITEM_DESC||'%') ))
       --AND OOD.ORGANIZATION_ID=:P_ORGANIZATION_ID--101
       --AND ORGANIZATION_CODE NOT IN ('IMO')
       AND MSI.INVENTORY_ITEM_STATUS_CODE='Active'
       --AND OPERATING_UNIT=85
       --AND MSI.ORGANIZATION_ID=101
       --AND MSI.SEGMENT1='BRND'
       --AND MSI.SEGMENT2='GIFT'
       --AND MSI.INVENTORY_ITEM_ID='24408'
       --AND MSI.SEGMENT1 IN ('SCRP')
       --AND UPPER(MSI.DESCRIPTION) LIKE UPPER('%'||:P_ITEM_DESC||'%')
       --AND MSI.PRIMARY_UOM_CODE='PCS'
       --AND MSI.DESCRIPTION LIKE 'Tea%'
       AND MSI.ENABLED_FLAG = 'Y';

--------------------------------------------------------------------------------
SELECT
    MCS.CATEGORY_SET_NAME,
    MCS.CATEGORY_SET_ID,
    MC.SEGMENT1                  LINE_OF_BUSINESS,
    MC.SEGMENT2                  ITEM_CATEGORY,
    MC.SEGMENT3                  ITEM_TYPE,
    MC.SEGMENT4                  CATELOG,
    MC.SEGMENT1 || '.' || MC.SEGMENT2 || '.' || MC.SEGMENT3 || '.' || MC.SEGMENT4 CATEGORY_SEGMENT,
    MC.CATEGORY_ID
    --,MCS.*
FROM
    INV.MTL_CATEGORIES_B MC,
    APPS.MTL_CATEGORY_SETS MCS
WHERE 1=1
    AND MC.STRUCTURE_ID=MCS.STRUCTURE_ID
    AND MCS.CATEGORY_SET_ID=1
    AND (   :P_ITEM_CATEGORIES IS NULL OR (UPPER( MC.SEGMENT1||'.'||MC.SEGMENT2||'.'||MC.SEGMENT3||'.'||MC.SEGMENT4) = UPPER (:P_ITEM_CATEGORIES)))
    AND (   :P_LINE_OF_BUSINESS IS NULL OR (UPPER (MC.SEGMENT1) LIKE UPPER ('%' || :P_LINE_OF_BUSINESS || '%')))
    AND (   :P_MAJOR_CATEGORY IS NULL OR (UPPER (MC.SEGMENT2) LIKE UPPER ('%' || :P_MAJOR_CATEGORY || '%')))
    AND (   :P_MINOR_CATEGORY IS NULL OR (UPPER (MC.SEGMENT3) LIKE UPPER ('%' || :P_MINOR_CATEGORY || '%')))
    AND (   :P_ITEM_CATELOG IS NULL OR (UPPER (MC.SEGMENT4) LIKE UPPER ('%' || :P_ITEM_CATELOG || '%')))
    AND (   :P_ITEM_ALL_CATEGORIES IS NULL OR ((   MC.SEGMENT1||'.'||MC.SEGMENT2||'.'||MC.SEGMENT3||'.'||MC.SEGMENT4) LIKE UPPER ('%' ||:P_ITEM_ALL_CATEGORIES|| '%')))-- IN ('NA.NA.NA.NA')
    --AND MC.SEGMENT2 IN ('FINISH GOODS')
    --AND MC.SEGMENT3 IN ('SEWING THREAD')
    --AND MC.CATEGORY_ID=204853
    AND (   :P_CATEGORY_ID IS NULL OR (MC.CATEGORY_ID = :P_CATEGORY_ID))
;