---------------------------**LOT_DETAILS**--------------------------------------
SELECT 
       MSI.ORGANIZATION_ID,
       OOD.ORGANIZATION_CODE,
       OOD.ORGANIZATION_NAME,
       MLN.LOT_NUMBER,
       MLN.CREATION_DATE,
       MLN.ORIGINATION_DATE,
       MSI.INVENTORY_ITEM_ID,
       MSI.SEGMENT1 ITEM_CODE,
       MSI.DESCRIPTION,
       MSI.PRIMARY_UOM_CODE,
       MSI.SECONDARY_UOM_CODE,
       CAT.CATEGORY_SET_NAME CATEGORY_SET,
       CAT.SEGMENT1 LINE_OF_BUSINESS,
       CAT.SEGMENT2 ITEM_CATEGORY,
       CAT.SEGMENT3 ITEM_TYPE,
       CAT.SEGMENT4 CATELOG,
       CAT.CATEGORY_CONCAT_SEGS CATEGORY_SEGMENTS
  --,MSI.*
  --,OOD.*
  --,CAT.*
  --,MLN.*
  FROM APPS.MTL_SYSTEM_ITEMS_B MSI, APPS.ORG_ORGANIZATION_DEFINITIONS OOD, APPS.MTL_ITEM_CATEGORIES_V CAT, INV.MTL_LOT_NUMBERS MLN
 WHERE     1 = 1
       AND MSI.ORGANIZATION_ID = MLN.ORGANIZATION_ID
       AND MSI.INVENTORY_ITEM_ID = MLN.INVENTORY_ITEM_ID
       AND MSI.ORGANIZATION_ID = OOD.ORGANIZATION_ID
       AND MSI.INVENTORY_ITEM_ID = CAT.INVENTORY_ITEM_ID
       AND MSI.ORGANIZATION_ID = CAT.ORGANIZATION_ID
       AND (   :P_OPERATING_UNIT IS NULL    OR (OOD.OPERATING_UNIT = :P_OPERATING_UNIT))
       AND (   :P_ORG_NAME IS NULL          OR (UPPER(OOD.ORGANIZATION_NAME) LIKE UPPER('%'||:P_ORG_NAME||'%') ))
       AND (   :P_ORGANIZATION_CODE IS NULL OR (OOD.ORGANIZATION_CODE = :P_ORGANIZATION_CODE))
       AND (   :P_LOT_NUMBER IS NULL        OR (MLN.LOT_NUMBER = :P_LOT_NUMBER))
       AND (   :P_ITEM_CODE IS NULL         OR (MSI.SEGMENT1 = :P_ITEM_CODE))
       AND (   :P_ITEM_DESC IS NULL         OR (UPPER(MSI.DESCRIPTION) LIKE UPPER('%'||:P_ITEM_DESC||'%') ))
       AND (   :P_LINE_OF_BUSINESS IS NULL  OR (CAT.SEGMENT1 = :P_LINE_OF_BUSINESS))
       AND (   :P_MAJOR_CATEGORY IS NULL    OR (CAT.SEGMENT2 = :P_MAJOR_CATEGORY))
       AND (   :P_MINOR_CATEGORY IS NULL    OR (CAT.SEGMENT3 = :P_MINOR_CATEGORY))
       AND (   :P_ITEM_CATELOG IS NULL      OR (CAT.SEGMENT4 = :P_ITEM_CATELOG))
       AND CAT.CATEGORY_SET_ID=1
       --AND ORGANIZATION_CODE NOT IN ('IMO')
       --AND ORGANIZATION_CODE IN ('251')
       --AND OPERATING_UNIT IN (85)
       --AND MSI.ORGANIZATION_ID IN (101)
       --AND MSI.SEGMENT2='BRND'
       --AND MSI.SEGMENT3='GIFT'
       --AND MSI.INVENTORY_ITEM_ID IN ('7297')
       --AND MSI.SEGMENT1 IN ('FT-GP6060-038BK')
       --AND MSI.PRIMARY_UOM_CODE='PCS'
       AND MSI.ENABLED_FLAG = 'Y';


---------------------------**LOT_TRANSACTION**----------------------------------
SELECT
MTLN.TRANSACTION_ID
,MTLN.INVENTORY_ITEM_ID
,MTLN.ORGANIZATION_ID
,MTLN.TRANSACTION_DATE
,MTLN.TRANSACTION_SOURCE_TYPE_ID
,MTLN.TRANSACTION_SOURCE_NAME
,MTLN.TRANSACTION_QUANTITY
,MTLN.PRIMARY_QUANTITY
,MTLN.LOT_NUMBER
,MTLN.ORIGINATION_DATE
,MTLN.*
FROM
INV.MTL_TRANSACTION_LOT_NUMBERS MTLN
WHERE 1=1
AND MTLN.LOT_NUMBER = :P_LOT_NUMBER --IN --
;

SELECT
*
FROM
APPS.MTL_TRANSACTION_LOT_VAL_V MTLT;

SELECT
*
FROM
MTL_ITEM_LOCATIONS
