SELECT
MC.SEGMENT1                  LINE_OF_BUSINESS,
MC.SEGMENT2                  ITEM_CATEGORY,
MC.SEGMENT3                  ITEM_TYPE,
MC.SEGMENT4                  CATELOG,
MC.CATEGORY_ID
FROM
INV.MTL_CATEGORIES_B MC,
APPS.MTL_CATEGORY_SETS MCS
WHERE 1=1
AND MC.STRUCTURE_ID=MCS.STRUCTURE_ID
AND MCS.CATEGORY_SET_ID=1
AND (   :P_LINE_OF_BUSINESS IS NULL OR (UPPER (MC.SEGMENT1) LIKE UPPER ('%' || :P_LINE_OF_BUSINESS || '%')))
AND (   :P_MAJOR_CATEGORY IS NULL OR (UPPER (MC.SEGMENT2) LIKE UPPER ('%' || :P_MAJOR_CATEGORY || '%')))
AND (   :P_MINOR_CATEGORY IS NULL OR (UPPER (MC.SEGMENT3) LIKE UPPER ('%' || :P_MINOR_CATEGORY || '%')))
AND (   :P_ITEM_CATELOG IS NULL OR (UPPER (MC.SEGMENT4) LIKE UPPER ('%' || :P_ITEM_CATELOG || '%')))
AND (   :P_CATEGORY_ID IS NULL      OR (MC.CATEGORY_ID = :P_CATEGORY_ID))
--AND MC.CATEGORY_ID=204853
;


SELECT DISTINCT CAT.CATEGORY_CONCAT_SEGS     CATEGORY_SEGMENT,
                CAT.SEGMENT1                  LINE_OF_BUSINESS,
                CAT.SEGMENT2                  ITEM_CATEGORY,
                CAT.SEGMENT3                  ITEM_TYPE,
                CAT.SEGMENT4                  CATELOG,
                CAT.CATEGORY_ID
  --,CAT.*
  FROM APPS.MTL_ITEM_CATEGORIES_V CAT
 WHERE     1 = 1
       AND (   :P_ITEM_CATEGORY IS NULL OR (UPPER (CAT.CATEGORY_CONCAT_SEGS) LIKE UPPER ('%' || :P_ITEM_CATEGORY || '%')))
       AND (   :P_LINE_OF_BUSINESS IS NULL OR (UPPER (CAT.SEGMENT1) LIKE UPPER ('%' || :P_LINE_OF_BUSINESS || '%')))
       AND (   :P_MAJOR_CATEGORY IS NULL OR (UPPER (CAT.SEGMENT2) LIKE UPPER ('%' || :P_MAJOR_CATEGORY || '%')))
       AND (   :P_MINOR_CATEGORY IS NULL OR (UPPER (CAT.SEGMENT3) LIKE UPPER ('%' || :P_MINOR_CATEGORY || '%')))
       AND (   :P_ITEM_CATELOG IS NULL OR (UPPER (CAT.SEGMENT4) LIKE UPPER ('%' || :P_ITEM_CATELOG || '%')))
       AND (   :P_CATEGORY_ID IS NULL      OR (CAT.CATEGORY_ID = :P_CATEGORY_ID))
        --AND (   :P_LINE_OF_BUSINESS IS NULL  OR (CAT.SEGMENT1 = :P_LINE_OF_BUSINESS))
        --AND (   :P_MAJOR_CATEGORY IS NULL    OR (CAT.SEGMENT2 = :P_MAJOR_CATEGORY))
        --AND (   :P_MINOR_CATEGORY IS NULL    OR (CAT.SEGMENT3 = :P_MINOR_CATEGORY))
        --AND (   :P_ITEM_CATELOG IS NULL      OR (CAT.SEGMENT4 = :P_ITEM_CATELOG))
;

       
--------------------------------------------------------------------------------

SELECT CAT.*
  --,MSI.*
  FROM APPS.MTL_ITEM_CATEGORIES_V CAT, APPS.MTL_SYSTEM_ITEMS_KFV MSI
 WHERE     1 = 1
       AND MSI.INVENTORY_ITEM_ID = CAT.INVENTORY_ITEM_ID
       AND MSI.ORGANIZATION_ID = CAT.ORGANIZATION_ID
       AND (   :P_ITEM_CODE IS NULL         OR (MSI.SEGMENT1 = :P_ITEM_CODE))
       AND (   :P_ITEM_DESC IS NULL         OR (UPPER(MSI.DESCRIPTION) LIKE UPPER('%'||:P_ITEM_DESC||'%') ))
       AND (   :P_LINE_OF_BUSINESS IS NULL  OR (CAT.SEGMENT1 = :P_LINE_OF_BUSINESS))
       AND (   :P_MAJOR_CATEGORY IS NULL    OR (CAT.SEGMENT2 = :P_MAJOR_CATEGORY))
       AND (   :P_MINOR_CATEGORY IS NULL    OR (CAT.SEGMENT3 = :P_MINOR_CATEGORY))
       AND (   :P_ITEM_CATELOG IS NULL      OR (CAT.SEGMENT4 = :P_ITEM_CATELOG));
       
--------------------------------------------------------------------------------

SELECT DISTINCT 
                MIC.CATEGORY_SET_ID,
                MCS.CATEGORY_SET_NAME CATEGORY_SET,
                MC.CATEGORY_ID,
                MC.SEGMENT1 LINE_OF_BUSINESS,
                MC.SEGMENT2 ITEM_CATEGORY,
                MC.SEGMENT3 ITEM_TYPE,
                MC.SEGMENT4 CATELOG
  --,MC.*
  --MSI.*
  --,MIC.*
  FROM INV.MTL_ITEM_CATEGORIES MIC,
       INV.MTL_CATEGORIES_B MC,
       APPS.MTL_CATEGORY_SETS MCS
 WHERE     1 = 1
       AND MIC.CATEGORY_SET_ID = MCS.CATEGORY_SET_ID
       AND MIC.CATEGORY_ID = MC.CATEGORY_ID
       AND MC.CATEGORY_ID=204853
       --AND MCS.CATEGORY_SET_NAME = 'Inventory'
       --AND MCS.CATEGORY_SET_NAME = 'Inventory'
       --AND UPPER(MC.SEGMENT2) LIKE UPPER('%SPARE%')--='SPINNING'
       --AND MC.SEGMENT2='SERVICE'
       --AND MC.SEGMENT1||'.'||MC.SEGMENT2||'.'||MC.SEGMENT3||'.'||MC.SEGMENT3 IN ('NA.NA.NA.NA')
       --AND    MC.SEGMENT1 || '.' || MC.SEGMENT2 || '.' || MC.SEGMENT3 || '.' || MC.SEGMENT4 IN ('IT.SERVICE.INTERNET.Service')
       --AND    MC.SEGMENT1 || '.' || MC.SEGMENT2 || '.' || MC.SEGMENT3 || '.' || MC.SEGMENT4 IN ('KNITTING.RAW MATERIAL.DYED YARN.Dyed Yarn')
       --AND    MC.SEGMENT1 || '.' || MC.SEGMENT2 || '.' || MC.SEGMENT3 || '.' || MC.SEGMENT4 IN ('KNITTING.RAW MATERIAL.YARN.Yarn')
       ;
       