/* Formatted on 1/28/2020 4:21:06 PM (QP5 v5.287) */
  SELECT OOD.OPERATING_UNIT,
         OOD.ORGANIZATION_NAME,
         OOD.ORGANIZATION_CODE,
         OOD.ORGANIZATION_ID,
         OHQD.SUBINVENTORY_CODE,
         --MSI.DESCRIPTION SUBINVENTORY_NAME,
         OHQD.LOT_NUMBER,
         MSIB.SEGMENT1 ITEM_CODE,
         MSIB.DESCRIPTION,
         OHQD.INVENTORY_ITEM_ID,
         SUM (OHQD.PRIMARY_TRANSACTION_QUANTITY) AS ONHAND_QTY,
         OHQD.TRANSACTION_UOM_CODE UOM_CODE
    FROM APPS.MTL_ONHAND_QUANTITIES_DETAIL OHQD,
         APPS.ORG_ORGANIZATION_DEFINITIONS OOD,
         --APPS.MTL_SECONDARY_INVENTORIES MSI,
         APPS.MTL_SYSTEM_ITEMS_B MSIB,
         APPS.MTL_ITEM_CATEGORIES_V CAT
   WHERE     1 = 1
         AND MSIB.ORGANIZATION_ID = OOD.ORGANIZATION_ID
         AND OHQD.ORGANIZATION_ID = OOD.ORGANIZATION_ID
         AND OHQD.INVENTORY_ITEM_ID = MSIB.INVENTORY_ITEM_ID
         AND (   :P_OPERATING_UNIT IS NULL OR (OOD.OPERATING_UNIT = :P_OPERATING_UNIT))
         AND (   :P_ORGANIZATION_CODE IS NULL OR (OOD.ORGANIZATION_CODE = :P_ORGANIZATION_CODE))
         AND (   :P_ORGANIZATION_ID IS NULL OR (OOD.ORGANIZATION_ID = :P_ORGANIZATION_CODE))
         AND (   :P_SUBINVENTORY IS NULL OR (OHQD.SUBINVENTORY_CODE = :P_SUBINVENTORY))
         AND (   :P_LOT_NUMBER IS NULL OR (OHQD.LOT_NUMBER = :P_LOT_NUMBER))
         AND MSIB.INVENTORY_ITEM_ID = CAT.INVENTORY_ITEM_ID
         AND MSIB.ORGANIZATION_ID = CAT.ORGANIZATION_ID
         AND CAT.CATEGORY_SET_ID=1
         AND (   :P_LINE_OF_BUSINESS IS NULL  OR (CAT.SEGMENT1 = :P_LINE_OF_BUSINESS))
         AND (   :P_MAJOR_CATEGORY IS NULL    OR (CAT.SEGMENT2 = :P_MAJOR_CATEGORY))
         AND (   :P_MINOR_CATEGORY IS NULL    OR (CAT.SEGMENT3 = :P_MINOR_CATEGORY))
         --AND MSI.ORGANIZATION_ID=OOD.ORGANIZATION_ID
         --AND OHQD.SUBINVENTORY_CODE!='DUMMY FG'
         --AND OOD.OPERATING_UNIT IN (125,131)
         --AND OHQD.ORGANIZATION_ID IN ('101','113','1345','1346')
         --AND OOD.ORGANIZATION_CODE IN ('SCI')
         --AND MSIB.INVENTORY_ITEM_ID=55605
         --AND MSIB.SEGMENT1='BRND'
         --AND MSIB.SEGMENT1='GIFT'
         --AND MSIB.SEGMENT1 IN ('CMNT.SBAG.0001')
         --AND CAT.SEGMENT2 NOT IN ('RAW MATERIAL')
         AND ( :P_ITEM_CODE IS NULL OR (MSIB.SEGMENT1 = :P_ITEM_CODE))
GROUP BY OOD.OPERATING_UNIT,
         MSIB.SEGMENT1,
         MSIB.DESCRIPTION,
         OHQD.INVENTORY_ITEM_ID,
         OHQD.LOT_NUMBER,
         OHQD.SUBINVENTORY_CODE,
         --MSI.DESCRIPTION,
         OHQD.TRANSACTION_UOM_CODE,
         OOD.ORGANIZATION_ID,
         OOD.ORGANIZATION_CODE,
         OOD.ORGANIZATION_NAME
ORDER BY ORGANIZATION_CODE;


--------------------------------------------------------------------------------

SELECT OOD.OPERATING_UNIT,
       OOD.ORGANIZATION_NAME,
       OOD.ORGANIZATION_CODE,
       OOD.ORGANIZATION_ID,
       MSI.SECONDARY_INVENTORY_NAME SUBINVENTORY_CODE,
       MSI.DESCRIPTION SUBINVENTORY_NAME,
       OOD.BUSINESS_GROUP_ID,
       OOD.SET_OF_BOOKS_ID,
       OOD.CHART_OF_ACCOUNTS_ID
  --,OOD.*
  --,MSI.*
  FROM APPS.ORG_ORGANIZATION_DEFINITIONS OOD,
       APPS.MTL_SECONDARY_INVENTORIES MSI
 WHERE     1 = 1
       AND MSI.ORGANIZATION_ID = OOD.ORGANIZATION_ID
       AND OOD.ORGANIZATION_ID = :P_ORGANIZATION_ID
       --OPERATING UNIT: LEDGER_ID--MASTER_ORG
       --ORGANIZATION_NAME--ORGANIZATION_CODE
       --ORGANIZATION_ID: SUB-LEDGER_ID
       --BUSINESS_GROUP_ID: INVENTORY_ID                      --101
       --AND ORGANIZATION_CODE=:P_ORGANIZATION_CODE--'SCI'
       --AND OPERATING_UNIT=:P_OPERATING_UNIT--85
       AND MSI.DISABLE_DATE IS NULL;

--------------------------------------------------------------------------------
  /* Formatted on 1/28/2020 4:21:06 PM (QP5 v5.287) */
  SELECT OOD.OPERATING_UNIT,
         OOD.ORGANIZATION_NAME,
         OOD.ORGANIZATION_CODE,
         OOD.ORGANIZATION_ID,
         OHQD.SUBINVENTORY_CODE,
         --MSI.DESCRIPTION SUBINVENTORY_NAME,
         OHQD.LOT_NUMBER,
         MSIB.SEGMENT1 ITEM_CODE,
         MSIB.DESCRIPTION,
         OHQD.INVENTORY_ITEM_ID,
         SUM (OHQD.PRIMARY_TRANSACTION_QUANTITY) AS ONHAND_QTY,
         OHQD.TRANSACTION_UOM_CODE UOM_CODE
    FROM APPS.MTL_ONHAND_QUANTITIES_DETAIL OHQD,
         APPS.ORG_ORGANIZATION_DEFINITIONS OOD,
         --APPS.MTL_SECONDARY_INVENTORIES MSI,
         APPS.MTL_SYSTEM_ITEMS_B MSIB
   WHERE     1 = 1
         AND MSIB.ORGANIZATION_ID = OOD.ORGANIZATION_ID
         AND OHQD.ORGANIZATION_ID = OOD.ORGANIZATION_ID
         AND OHQD.INVENTORY_ITEM_ID = MSIB.INVENTORY_ITEM_ID
         AND (   :P_OPERATING_UNIT IS NULL OR (OOD.OPERATING_UNIT = :P_OPERATING_UNIT))
         AND (   :P_ORGANIZATION_CODE IS NULL OR (OOD.ORGANIZATION_CODE = :P_ORGANIZATION_CODE))
         AND (   :P_ORGANIZATION_ID IS NULL OR (OOD.ORGANIZATION_ID = :P_ORGANIZATION_CODE))
         AND (   :P_SUBINVENTORY IS NULL OR (OHQD.SUBINVENTORY_CODE = :P_SUBINVENTORY))
         AND (   :P_LOT_NUMBER IS NULL OR (OHQD.LOT_NUMBER = :P_LOT_NUMBER))
         --AND MSI.ORGANIZATION_ID=OOD.ORGANIZATION_ID
         --AND OHQD.SUBINVENTORY_CODE!='DUMMY FG'
         --AND OOD.OPERATING_UNIT IN (125,131)
         --AND OHQD.ORGANIZATION_ID IN ('101','113','1345','1346')
         --AND OOD.ORGANIZATION_CODE IN ('SCI')
         --AND MSIB.INVENTORY_ITEM_ID=55605
         --AND MSIB.SEGMENT1='BRND'
         --AND MSIB.SEGMENT1='GIFT'
         --AND MSIB.SEGMENT1 IN ('CMNT.SBAG.0001')
         AND ( :P_ITEM_CODE IS NULL OR (MSIB.SEGMENT1 = :P_ITEM_CODE))
GROUP BY OOD.OPERATING_UNIT,
         MSIB.SEGMENT1,
         MSIB.DESCRIPTION,
         OHQD.INVENTORY_ITEM_ID,
         OHQD.LOT_NUMBER,
         OHQD.SUBINVENTORY_CODE,
         --MSI.DESCRIPTION,
         OHQD.TRANSACTION_UOM_CODE,
         OOD.ORGANIZATION_ID,
         OOD.ORGANIZATION_CODE,
         OOD.ORGANIZATION_NAME
ORDER BY ORGANIZATION_CODE;