/* Formatted on 9/15/2020 3:05:57 PM (QP5 v5.354) */
SELECT *
  FROM INV.MTL_TRANSACTION_TYPES MTT
 WHERE 1 = 1 
 AND (   :P_TRANSACTION_TYPE_ID IS NULL    OR (MTT.TRANSACTION_TYPE_ID = :P_TRANSACTION_TYPE_ID))
 AND (   :P_SOURCE_TYPE_ID IS NULL    OR (MTT.TRANSACTION_SOURCE_TYPE_ID = :P_SOURCE_TYPE_ID))
 --AND MTT.TRANSACTION_TYPE_ID IN (64)
 --AND MTT.TRANSACTION_SOURCE_TYPE_ID IN ( 5)
 --AND MTT.TRANSACTION_TYPE_NAME IN ('WIP Issue')
 --AND TRANSACTION_ACTION_ID IN (24)
 AND (   :P_TRANSACTION_TYPE IS NULL OR (UPPER(MTT.TRANSACTION_TYPE_NAME) LIKE UPPER('%'||:P_TRANSACTION_TYPE||'%') ));
 
 
 
 SELECT *
  FROM MTL_TXN_SOURCE_TYPES MTST
 WHERE 1 = 1
    --AND MTST.TRANSACTION_SOURCE_TYPE_ID='1084'
    AND (   :P_TRANSACTION_SOURCE_TYPE_ID IS NULL    OR (MTST.TRANSACTION_SOURCE_TYPE_ID = :P_TRANSACTION_SOURCE_TYPE_ID))
;