/* Formatted on 10/1/2020 3:31:37 PM (QP5 v5.287) */
CREATE TABLE XXDBL_SEDO_FILE_UPD
(
   SEDO_FILE_ID     NUMBER NOT NULL,
   SEDO_FILE_NAME   VARCHAR2 (50) NOT NULL,
   REMARKS          VARCHAR2 (100),
   CONSTRAINT SEDO_FILE_PK PRIMARY KEY (SEDO_FILE_ID)
);

DROP TABLE XXDBL_SEDO_FILE_UPD;