SELECT
*
FROM
XXDBL.XXDBL_BILL_REC_HEADER
order by creation_date desc;

SELECT
*
FROM
XXDBL_BILL_REC_HEADER;

ALTER TABLE XXDBL.XXDBL_BILL_REC_HEADER 
ADD (
  LC_NUMBER VARCHAR2(50)
);

DROP SYNONYM XXDBL_BILL_REC_HEADER;

CREATE OR REPLACE SYNONYM APPSRO.XXDBL_BILL_REC_HEADER FOR XXDBL.XXDBL_BILL_REC_HEADER;

CREATE OR REPLACE SYNONYM APPS.XXDBL_BILL_REC_HEADER FOR XXDBL.XXDBL_BILL_REC_HEADER;


GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, READ, DEBUG, FLASHBACK ON XXDBL.XXDBL_BILL_REC_HEADER TO APPS WITH GRANT OPTION;

GRANT SELECT ON XXDBL.XXDBL_BILL_REC_HEADER TO APPSRO;