/* Formatted on 11/11/2021 3:15:14 PM (QP5 v5.365) */
ALTER TABLE xxdbl.XXDBL_INVOICE_TRACKING_SYSTEM
    ADD (sms_sent_status VARCHAR2 (50 BYTE));

CREATE OR REPLACE SYNONYM APPS.XXDBL_INVOICE_TRACKING_SYSTEM FOR XXDBL.XXDBL_INVOICE_TRACKING_SYSTEM;


CREATE OR REPLACE SYNONYM APPSRO.XXDBL_INVOICE_TRACKING_SYSTEM FOR XXDBL.XXDBL_INVOICE_TRACKING_SYSTEM;


select
*
from
xxdbl.XXDBL_INVOICE_TRACKING_SYSTEM