/* Formatted on 8/27/2020 10:20:38 AM (QP5 v5.287) */
CREATE TABLE XXDBL.XXDBL_ITEM_ALOC_BASIS_STG
(
   SL_NO                NUMBER NOT NULL,
   CREATION_DATE        DATE,
   CREATED_BY           NUMBER,
   ORGANIZATION_CODE    VARCHAR2 (10 BYTE),
   ITEM_CODE            VARCHAR2 (100 BYTE),
   ALLOC_CODE           VARCHAR2 (100 BYTE),
   BASIS_TYPE           VARCHAR2 (100 BYTE),
   COST_ANALYSIS_CODE   VARCHAR2 (10 BYTE),
   STATUS               VARCHAR2 (10 BYTE),
   STATUS_MESSAGE       VARCHAR2 (240 BYTE),
   SET_PROC_ID          VARCHAR2 (50 BYTE)
);

CREATE UNIQUE INDEX XXDBL.IDX_ITM_ALOC_BS
   ON XXDBL.XXDBL_ITEM_ALOC_BASIS_STG (SL_NO)
   LOGGING
   TABLESPACE XXDBL_TS_TX_DATA
   PCTFREE 10
   INITRANS 2
   MAXTRANS 255
   STORAGE (INITIAL 64 K
            NEXT 1 M
            MAXSIZE UNLIMITED
            MINEXTENTS 1
            MAXEXTENTS UNLIMITED
            PCTINCREASE 0
            BUFFER_POOL DEFAULT);

ALTER TABLE XXDBL.XXDBL_ITEM_ALOC_BASIS_STG ADD (
  CONSTRAINT IDX_ITM_ALOC_BS
  PRIMARY KEY
  (SL_NO)
  USING INDEX XXDBL.IDX_ITM_ALOC_BS
  ENABLE VALIDATE);

GRANT SELECT ON XXDBL.XXDBL_ITEM_ALOC_BASIS_STG TO APPS WITH GRANT OPTION;

GRANT SELECT ON XXDBL.XXDBL_ITEM_ALOC_BASIS_STG TO APPSRO;

CREATE OR REPLACE SYNONYM APPS.XXDBL_ITEM_ALOC_BASIS_STG FOR XXDBL.XXDBL_ITEM_ALOC_BASIS_STG;

DROP TABLE XXDBL.XXDBL_ITEM_ALOC_BASIS_STG;