/* Formatted on 11/14/2020 9:11:57 AM (QP5 v5.287) */
SELECT PHA.SEGMENT1,
       PHA.PO_HEADER_ID,
       PV.VENDOR_NAME,
       OOD.ORGANIZATION_ID,
       MIS.SEGMENT1 "Item Code",
       MIS.DESCRIPTION,
       PLA.UNIT_MEAS_LOOKUP_CODE,
       PDA.QUANTITY_ORDERED QUANTITY,
       PLA.UNIT_PRICE,
       PDA.QUANTITY_ORDERED * PLA.UNIT_PRICE TOTAL_PRICE,
       (PDA.QUANTITY_ORDERED * PLA.UNIT_PRICE) * NVL (PHA.RATE, 1)
          FUNCTIONAL_AMOUNT
  FROM PO_HEADERS_ALL PHA,
       PO_LINES_ALL PLA,
       PO_LINE_LOCATIONS_ALL PLL,
       APPS.PO_DISTRIBUTIONS_ALL PDA,
       PO_VENDORS PV,
       MTL_SYSTEM_ITEMS_B MIS,
       HR_ALL_ORGANIZATION_UNITS OU,
       ORG_ORGANIZATION_DEFINITIONS OOD
 WHERE     PHA.PO_HEADER_ID = PLA.PO_HEADER_ID
       AND PLA.PO_LINE_ID = PLL.PO_LINE_ID
       AND PLA.PO_HEADER_ID = PLL.PO_HEADER_ID
       AND PLA.ITEM_ID = MIS.INVENTORY_ITEM_ID
       AND MIS.ORGANIZATION_ID = PLL.SHIP_TO_ORGANIZATION_ID
       AND PHA.PO_HEADER_ID = PDA.PO_HEADER_ID
       AND PLA.PO_LINE_ID = PDA.PO_LINE_ID
       AND PLL.LINE_LOCATION_ID = PDA.LINE_LOCATION_ID
       AND PHA.VENDOR_ID = PV.VENDOR_ID
       AND PHA.ORG_ID = OU.ORGANIZATION_ID
       AND PLL.SHIP_TO_ORGANIZATION_ID = OOD.ORGANIZATION_ID
       AND PDA.QUANTITY_CANCELLED = 0
       AND NVL (PLA.CANCEL_FLAG, 'N') = 'N'
       AND NVL (PLL.CANCEL_FLAG, 'N') = 'N'
       AND PLL.CANCEL_DATE IS NULL
--AND pha.segment1 = '25113004384'
--and pha.po_header_id=nvl(:p_po_number, pha.po_header_id)
--and pha.org_id=nvl(:p_org_id,pha.org_id)