select DISTINCT
ACTIVITIES_TYPE
from
XXVEH_ACTIVITIES
where 1=1
--and BLL_NO LIKE 'BRTA%'
order by ACTIVITIES_TYPE

IF :CTRL.BILL_TYPE IS NULL OR :CTRL.BILL_TYPE='MILE' THEN SET_BLOCK_PROPERTY('XXVEH_ACTIVITIES', DEFAULT_WHERE, '1=1');
ELSIF :CTRL.BILL_TYPE='CASE' THEN :XXVEH_ACTIVITIES.ACTIVITIES_TYPE:='CASE'; 
ELSIF :CTRL.BILL_TYPE='ACDT' THEN :XXVEH_ACTIVITIES.ACTIVITIES_TYPE:='ACCIDENT';
ELSIF :CTRL.BILL_TYPE='BRTA' THEN :XXVEH_ACTIVITIES.ACTIVITIES_TYPE:='ACCIDENT';
ELSIF :CTRL.BILL_TYPE='BRTA' THEN SET_BLOCK_PROPERTY('XXVEH_ACTIVITIES', DEFAULT_WHERE, 'ACTIVITIES_TYPE NOT IN'||'('||'''CASE'''||','||'''MILAGE'''||','||'''ACCIDENT'''||')');
END IF;

'CASE'
'FITNESS FEE'
'FITNESS INCOME TAX'
'LATE FEE'
'ROUTE PERMIT FEE'
'TAX TOKEN FEE'
