/* Formatted on 1/24/2021 10:44:59 AM (QP5 v5.354) */
SELECT OOD.ORGANIZATION_CODE,
       MMT.ORGANIZATION_ID           ORG_ID,
       MSI.INVENTORY_ITEM_ID         ITEM_ID,
       MIC.SEGMENT2                  AS ITEM_CATG,
       MIC.SEGMENT3                  AS ITEM_TYPE,
       MSI.CONCATENATED_SEGMENTS     ITEM_CODE,
       MSI.DESCRIPTION               ITEM_DESCRIPTION,
       MSI.PRIMARY_UOM_CODE          AS P_UOM,
       MMT.SECONDARY_UOM_CODE        AS S_UOM,
       MMT.TRANSACTION_SOURCE_NAME,
       MMT.TRANSACTION_SOURCE_ID,
       MMT.TRANSACTION_ID,
       GB.BATCH_NO,
       MMT.TRANSACTION_QUANTITY
  --,MTT.*
  FROM INV.MTL_MATERIAL_TRANSACTIONS      MMT,
       INV.MTL_TRANSACTION_TYPES          MTT,
       APPS.MTL_SYSTEM_ITEMS_B_KFV        MSI,
       APPS.MTL_ITEM_CATEGORIES_V         MIC,
       APPS.ORG_ORGANIZATION_DEFINITIONS  OOD,
       APPS.GME_BATCH_HEADER              GB
 WHERE     MMT.INVENTORY_ITEM_ID = MSI.INVENTORY_ITEM_ID
       AND MMT.ORGANIZATION_ID = MSI.ORGANIZATION_ID
       AND MSI.INVENTORY_ITEM_ID = MIC.INVENTORY_ITEM_ID
       AND MSI.ORGANIZATION_ID = MIC.ORGANIZATION_ID
       AND MMT.ORGANIZATION_ID = OOD.ORGANIZATION_ID
       AND MIC.CATEGORY_SET_ID = 1
       AND MMT.TRANSACTION_SOURCE_ID = GB.BATCH_ID(+)
       AND TO_CHAR (MMT.TRANSACTION_TYPE_ID) NOT IN (TO_CHAR ( :CP_TRX_TYPE))
       AND MMT.TRANSACTION_TYPE_ID = 35
       AND (LOGICAL_TRANSACTION = 2 OR LOGICAL_TRANSACTION IS NULL)
       --AND MMT.TRANSACTION_TYPE_ID NOT IN (80, 98, 99, 120, 52, 26, 64)
       AND MMT.ORGANIZATION_ID = NVL ( :P_ORG_ID, MMT.ORGANIZATION_ID)
       AND MMT.SUBINVENTORY_CODE = NVL ( :P_SUB_INV, MMT.SUBINVENTORY_CODE)
       AND MSI.CONCATENATED_SEGMENTS =
           NVL ( :P_ITEM, MSI.CONCATENATED_SEGMENTS)
       AND MIC.SEGMENT3 = NVL ( :P_ITEM_TYPE, MIC.SEGMENT3)
       AND MIC.SEGMENT2 = NVL ( :P_ITEM_CATEGORY, MIC.SEGMENT2)
       -- AND MSI.CONCATENATED_SEGMENTS = 'PAMCAR00000000000035'
       --AND MSI.PRIMARY_UOM_CODE = 'CON'
       AND MTT.TRANSACTION_TYPE_ID = MMT.TRANSACTION_TYPE_ID
       AND MTT.TRANSACTION_SOURCE_TYPE_ID = MMT.TRANSACTION_SOURCE_TYPE_ID
       AND MIC.CATEGORY_CONCAT_SEGS NOT LIKE 'ECO THREAD.SEMI FINISH GOODS%'
       --AND MMT.TRANSACTION_DATE BETWEEN '01-JAN-2010' AND :P_DATE_TO + .99999
       AND TRUNC (MMT.TRANSACTION_DATE) BETWEEN :P_DATE_FROM AND :P_DATE_TO;