SELECT   MATCH_OPTION,PHA.PO_HEADER_ID, PHA.SEGMENT1 PO_NUMBER,
         DECODE (INSPECTION_REQUIRED_FLAG, 'Y', '4-WAY') FOUR_WAY_MATCH,
         DECODE (RECEIPT_REQUIRED_FLAG, 'Y', '3-WAY') THREE_WAY_MATCH,
         DECODE (MATCH_OPTION, 'P', '2-WAY') TWO_WAY_MATCH
  FROM   PO_LINE_LOCATIONS_ALL PLLA
         ,PO_HEADERS_ALL PHA
 WHERE 1=1
 AND PLLA.PO_HEADER_ID = PHA.PO_HEADER_ID 
 AND (:P_PO_NO IS NULL OR (PHA.SEGMENT1 = :P_PO_NO))
 --AND PHA.PO_HEADER_ID in(1015,1016,2004,2007)