/* Formatted on 1/16/2020 9:20:17 AM (QP5 v5.287) */
SELECT APSA.ORG_ID,
       APS.VENDOR_ID,
       APS.SEGMENT1 SUPPLIER_NUMBER,
       APS.VENDOR_NAME SUPPLIER_NAME,
       TO_CHAR (APS.START_DATE_ACTIVE, 'DD-MON-YYYY HH24:MI:SS') SUPPLIER_CREATION_DATE,
       APS.ENABLED_FLAG,
       APSA.VENDOR_SITE_ID,
       APSA.VENDOR_SITE_CODE SUPPLIER_SITE,
       TO_CHAR (APS.START_DATE_ACTIVE, 'DD-MON-YYYY HH24:MI:SS') SITE_CREATION_DATE,
          APSA.ADDRESS_LINE1
       || ','
       || APSA.ADDRESS_LINE2
       || ','
       || APSA.ADDRESS_LINE3
          ADDRESS
  --,APS.*
  --,APSA.*
  FROM APPS.AP_SUPPLIERS APS, APPS.AP_SUPPLIER_SITES_ALL APSA
 WHERE     1 = 1
       AND APS.VENDOR_ID = APSA.VENDOR_ID(+)
       --AND APS.VENDOR_ID IN ('2550')
       --AND APSA.VENDOR_SITE_ID IN ('9879')
       AND ((:P_ORG_ID IS NULL) OR (APSA.ORG_ID = :P_ORG_ID))
       AND ((:SUPPLIER_ID IS NULL) OR (APS.SEGMENT1 = :SUPPLIER_ID))
       AND ((:P_SUPPLIER_NAME IS NULL) OR (UPPER (APS.VENDOR_NAME) LIKE UPPER ('%' || :P_SUPPLIER_NAME || '%')))