/* Formatted on 8/24/2021 10:49:14 AM (QP5 v5.354) */
  SELECT                                                            --DISTINCT
         PHA.PO_HEADER_ID,
         PHA.SEGMENT1             PO_NUM,
         PLA.LINE_NUM,
         PHA.TYPE_LOOKUP_CODE     PO_TYPE,
         PLA.ITEM_DESCRIPTION,
         PHA.CREATION_DATE,
         PHA.REVISION_NUM,
         PHAA.REVISION_NUM        ARCH_REVISION_NUM,
         PHA.REVISED_DATE
    --,PHA.*
    --,PLA.*
    --,PLL.*
    --,PHAA.*
    --,PLAL.*
    --,PLLAL.*
    --,PDAA.*
    --,PDA.*
    FROM PO.PO_HEADERS_ALL                 PHA,
         PO.PO_LINES_ALL                   PLA,
         PO_LINE_LOCATIONS_ALL             PLL,
         PO_HEADERS_ARCHIVE_ALL            PHAA,
         PO_LINES_ARCHIVE_ALL              PLAL,
         APPS.PO_LINE_LOCATIONS_ARCHIVE_ALL PLLAL,
         PO_DISTRIBUTIONS_ARCHIVE_ALL      PDAA,
         --GL_CODE_COMBINATIONS_KFV GCC,
         PO.PO_DISTRIBUTIONS_ALL           PDA
   WHERE     1 = 1
         AND PHA.PO_HEADER_ID = PLA.PO_HEADER_ID
         AND PLA.PO_LINE_ID = PDA.PO_LINE_ID
         AND PHA.PO_HEADER_ID = PLL.PO_HEADER_ID
         AND PLA.PO_LINE_ID = PLL.PO_LINE_ID
         AND PDA.LINE_LOCATION_ID = PLL.LINE_LOCATION_ID
         AND PHA.PO_HEADER_ID = PHAA.PO_HEADER_ID
         AND PHAA.PO_HEADER_ID = PLAL.PO_HEADER_ID
         AND PLA.PO_LINE_ID = PLAL.PO_LINE_ID
         AND (PLAL.CANCEL_FLAG IS NULL OR PLAL.CANCEL_FLAG = 'N')
         AND PHAA.PO_HEADER_ID = PLLAL.PO_HEADER_ID
         AND PLAL.PO_LINE_ID = PLLAL.PO_LINE_ID
         AND PLL.LINE_LOCATION_ID = PLLAL.LINE_LOCATION_ID
         AND (PLLAL.CANCEL_FLAG IS NULL OR PLLAL.CANCEL_FLAG = 'N')
         AND PLAL.PO_LINE_ID = PDAA.PO_LINE_ID
         AND PDA.PO_DISTRIBUTION_ID = PDAA.PO_DISTRIBUTION_ID
         AND PDAA.GL_CANCELLED_DATE IS NULL
         --AND PDA.PO_LINE_ID = PDAA.PO_LINE_ID
         --AND PDA.LINE_LOCATION_ID = PDAA.LINE_LOCATION_ID
         --AND PDA.LINE_LOCATION_ID = PLLAL.LINE_LOCATION_ID
         --AND PLL.LINE_LOCATION_ID = PLLAL.LINE_LOCATION_ID
         --AND PDA.CODE_COMBINATION_ID = GCC.CODE_COMBINATION_ID
         --AND PHA.REVISION_NUM = 1
         AND PHA.SEGMENT1 = '10523015504'
ORDER BY PHA.SEGMENT1,
         PLA.LINE_NUM,
         PHA.REVISION_NUM,
         PHAA.REVISION_NUM;