/* Formatted on 8/23/2021 12:08:55 PM (QP5 v5.354) */
  SELECT                                                            --DISTINCT
         PHA.PO_HEADER_ID,
         PHA.SEGMENT1
             PO_NUM,
         PLA.LINE_NUM,
         PHA.REVISION_NUM,
         PHAA.REVISION_NUM
             ARCH_REVISION_NUM,
         PHA.REVISED_DATE,
         PHA.CREATION_DATE,
         PHA.TYPE_LOOKUP_CODE
             PO_TYPE,
         DECODE (PLAL.AMOUNT, PLA.AMOUNT, NULL, PLAL.AMOUNT)
             FROM_UNIT_PRICE,
         DECODE (PLA.AMOUNT, PLAL.AMOUNT, NULL, PLA.AMOUNT)
             TO_UNIT_PRICE,
         DECODE (PLAL.RETAINAGE_RATE,
                 PLA.RETAINAGE_RATE, NULL,
                 PLAL.RETAINAGE_RATE)
             FROM_RETAINAGE_RATE,
         DECODE (PLA.RETAINAGE_RATE,
                 PLAL.RETAINAGE_RATE, NULL,
                 PLA.RETAINAGE_RATE)
             TO_RETAINAGE_RATE,
         DECODE (PLAL.RECOUPMENT_RATE,
                 PLA.RECOUPMENT_RATE, NULL,
                 PLAL.RECOUPMENT_RATE)
             FROM_RECOUPMENT_RATE,
         DECODE (PLA.RECOUPMENT_RATE,
                 PLAL.RECOUPMENT_RATE, NULL,
                 PLA.RECOUPMENT_RATE)
             TO_RECOUPMENT_RATE,
         DECODE (PLLAL.NEED_BY_DATE,
                 PLL.NEED_BY_DATE, NULL,
                 PLLAL.NEED_BY_DATE)
             FROM_NEED_BY_DATE,
         DECODE (PLL.NEED_BY_DATE, PLLAL.NEED_BY_DATE, NULL, PLL.NEED_BY_DATE)
             TO_NEED_BY_DATE,
         DECODE ((SELECT SUM (AMOUNT)
                    FROM PO_LINES_ARCHIVE_ALL
                   WHERE PO_HEADER_ID = PHA.PO_HEADER_ID),
                 (SELECT SUM (AMOUNT)
                    FROM PO_LINES_ALL
                   WHERE PO_HEADER_ID = PHA.PO_HEADER_ID), NULL,
                 (SELECT SUM (AMOUNT)
                    FROM PO_LINES_ARCHIVE_ALL
                   WHERE PO_HEADER_ID = PHA.PO_HEADER_ID))
             TOTAL_AMOUNT_CHANGED_FROM,
         DECODE ((SELECT SUM (AMOUNT)
                    FROM PO_LINES_ALL
                   WHERE PO_HEADER_ID = PHA.PO_HEADER_ID),
                 (SELECT SUM (AMOUNT)
                    FROM PO_LINES_ARCHIVE_ALL
                   WHERE PO_HEADER_ID = PHA.PO_HEADER_ID), NULL,
                 (SELECT SUM (AMOUNT)
                    FROM PO_LINES_ALL
                   WHERE PO_HEADER_ID = PHA.PO_HEADER_ID))
             TOTAL_AMOUNT_CHANGED_TO,
         DECODE ((SELECT CONCATENATED_SEGMENTS
                    FROM GL_CODE_COMBINATIONS_KFV
                   WHERE CODE_COMBINATION_ID = PDA.CODE_COMBINATION_ID),
                 (SELECT CONCATENATED_SEGMENTS
                    FROM GL_CODE_COMBINATIONS_KFV
                   WHERE CODE_COMBINATION_ID = PDAA.CODE_COMBINATION_ID), NULL,
                 (SELECT CONCATENATED_SEGMENTS
                    FROM GL_CODE_COMBINATIONS_KFV
                   WHERE CODE_COMBINATION_ID = PDA.CODE_COMBINATION_ID))
             FROM_CHARGE_ACCOUNT,
         DECODE ((SELECT CONCATENATED_SEGMENTS
                    FROM GL_CODE_COMBINATIONS_KFV
                   WHERE CODE_COMBINATION_ID = PDAA.CODE_COMBINATION_ID),
                 (SELECT CONCATENATED_SEGMENTS
                    FROM GL_CODE_COMBINATIONS_KFV
                   WHERE CODE_COMBINATION_ID = PDA.CODE_COMBINATION_ID), NULL,
                 (SELECT CONCATENATED_SEGMENTS
                    FROM GL_CODE_COMBINATIONS_KFV
                   WHERE CODE_COMBINATION_ID = PDAA.CODE_COMBINATION_ID))
             TO_CHARGE_ACCOUNT,
         PLA.ITEM_DESCRIPTION
    --,PHA.*
    --,PLA.*
    --,PLL.*
    --,PHAA.*
    --,PLAL.*
    --,PLLAL.*
    --,PDAA.*
    --,PDA.*
    FROM PO.PO_HEADERS_ALL                 PHA,
         PO.PO_LINES_ALL                   PLA,
         PO_LINE_LOCATIONS_ALL             PLL,
         PO_HEADERS_ARCHIVE_ALL            PHAA,
         PO_LINES_ARCHIVE_ALL              PLAL,
         APPS.PO_LINE_LOCATIONS_ARCHIVE_ALL PLLAL,
         PO_DISTRIBUTIONS_ARCHIVE_ALL      PDAA,
         --GL_CODE_COMBINATIONS_KFV GCC,
         PO.PO_DISTRIBUTIONS_ALL           PDA
   WHERE     1 = 1
         AND PHA.PO_HEADER_ID = PLA.PO_HEADER_ID
         AND PLA.PO_LINE_ID = PDA.PO_LINE_ID
         AND PHA.PO_HEADER_ID = PLL.PO_HEADER_ID
         AND PLA.PO_LINE_ID = PLL.PO_LINE_ID
         AND PDA.LINE_LOCATION_ID = PLL.LINE_LOCATION_ID
         AND PHA.PO_HEADER_ID = PHAA.PO_HEADER_ID
         AND PHAA.PO_HEADER_ID = PLAL.PO_HEADER_ID
         AND PLA.PO_LINE_ID = PLAL.PO_LINE_ID
         AND (PLAL.CANCEL_FLAG IS NULL OR PLAL.CANCEL_FLAG = 'N')
         AND PHAA.PO_HEADER_ID = PLLAL.PO_HEADER_ID
         AND PLAL.PO_LINE_ID = PLLAL.PO_LINE_ID
         AND PLL.LINE_LOCATION_ID = PLLAL.LINE_LOCATION_ID
         AND (PLLAL.CANCEL_FLAG IS NULL OR PLLAL.CANCEL_FLAG = 'N')
         AND PLAL.PO_LINE_ID = PDAA.PO_LINE_ID
         AND PDA.PO_DISTRIBUTION_ID = PDAA.PO_DISTRIBUTION_ID
         AND PDAA.GL_CANCELLED_DATE IS NULL
         --AND PDA.PO_LINE_ID = PDAA.PO_LINE_ID
         --AND PDA.LINE_LOCATION_ID = PDAA.LINE_LOCATION_ID
         --AND PDA.LINE_LOCATION_ID = PLLAL.LINE_LOCATION_ID
         --AND PLL.LINE_LOCATION_ID = PLLAL.LINE_LOCATION_ID
         --AND PDA.CODE_COMBINATION_ID = GCC.CODE_COMBINATION_ID
         --AND PHA.REVISION_NUM = 1
         AND PHA.SEGMENT1 = '10523015504'
ORDER BY PHA.SEGMENT1,
         PLA.LINE_NUM,
         PHA.REVISION_NUM,
         PHAA.REVISION_NUM;