SET DEFINE OFF;
Insert into XX_APEX.XX_APEX_MENU_LIST
   (APPLICATION_NAME, MENU_MODULE_ID, MENU_NAME, PAGE_NO, MENU_STATUS)
 Values
   ('DBL CnF Apps', 1, 'Home', 1, 1);
Insert into XX_APEX.XX_APEX_MENU_LIST
   (APPLICATION_NAME, MENU_MODULE_ID, MENU_NAME, PAGE_NO, MENU_STATUS)
 Values
   ('DBL CnF Apps', 1, 'CNF', 2, 1);
Insert into XX_APEX.XX_APEX_MENU_LIST
   (APPLICATION_NAME, MENU_MODULE_ID, MENU_NAME, PAGE_NO, PARENT_MENU_LIST_ID, 
    PARENT_MENU_NAME, MENU_STATUS)
 Values
   ('DBL CnF Apps', 1, 'CNF Expense List', 4, '42', 
    'CNF', 1);
Insert into XX_APEX.XX_APEX_MENU_LIST
   (APPLICATION_NAME, MENU_MODULE_ID, MENU_NAME, PAGE_NO, PARENT_MENU_LIST_ID, 
    PARENT_MENU_NAME, MENU_STATUS)
 Values
   ('DBL CnF Apps', 1, 'C & F Job Entry', 16, '42', 
    'CNF', 1);
Insert into XX_APEX.XX_APEX_MENU_LIST
   (APPLICATION_NAME, MENU_MODULE_ID, MENU_NAME, PAGE_NO, PARENT_MENU_LIST_ID, 
    PARENT_MENU_NAME, MENU_STATUS)
 Values
   ('DBL CnF Apps', 1, 'Job Approve (CTG)', 10, '42', 
    'CNF', 1);
Insert into XX_APEX.XX_APEX_MENU_LIST
   (APPLICATION_NAME, MENU_MODULE_ID, MENU_NAME, PAGE_NO, PARENT_MENU_LIST_ID, 
    PARENT_MENU_NAME, MENU_STATUS)
 Values
   ('DBL CnF Apps', 1, 'Job Approve (COR)', 7, '42', 
    'CNF', 1);
Insert into XX_APEX.XX_APEX_MENU_LIST
   (APPLICATION_NAME, MENU_MODULE_ID, MENU_NAME, PAGE_NO, PARENT_MENU_LIST_ID, 
    PARENT_MENU_NAME, MENU_STATUS)
 Values
   ('DBL CnF Apps', 1, 'Job Authorizer', 6, '42', 
    'CNF', 1);
Insert into XX_APEX.XX_APEX_MENU_LIST
   (APPLICATION_NAME, MENU_MODULE_ID, MENU_NAME, PAGE_NO, MENU_STATUS)
 Values
   ('DBL CnF Apps', 2, 'Security', 11, 1);
Insert into XX_APEX.XX_APEX_MENU_LIST
   (APPLICATION_NAME, MENU_MODULE_ID, MENU_NAME, PAGE_NO, PARENT_MENU_LIST_ID, 
    PARENT_MENU_NAME, MENU_STATUS)
 Values
   ('DBL CnF Apps', 2, 'Menu Create', 20, '48', 
    'Security', 1);
Insert into XX_APEX.XX_APEX_MENU_LIST
   (APPLICATION_NAME, MENU_MODULE_ID, MENU_NAME, PAGE_NO, PARENT_MENU_LIST_ID, 
    PARENT_MENU_NAME, MENU_STATUS)
 Values
   ('DBL CnF Apps', 2, 'Menu Permission', 19, '48', 
    'Security', 1);
COMMIT;
