/* Formatted on 11/14/2021 4:05:43 PM (QP5 v5.365) */
SELECT * FROM XX_APEX.XX_APEX_CNF_EXPENSE_LIST;

SELECT * FROM XX_APEX.XX_APEX_CNF_JOB_MASTER;

SELECT * FROM XX_APEX.XX_APEX_CNF_JOB_DETAILS;

SELECT * FROM XX_APEX.XX_APEX_MENU_LIST;

SELECT * FROM XX_APEX.XX_APEX_MENU_MODULE;

SELECT * FROM XX_APEX.XX_APEX_MENU_PERMISSION;