/* Formatted on 8/16/2021 10:20:54 AM (QP5 v5.287) */
SELECT DBMS_METADATA.get_ddl ('MATERIALIZED_VIEW', :P_MVIEW_NAME, :P_OWNER)
  FROM DUAL;

SELECT *
  FROM dba_mviews
 WHERE OWNER = :V_MVIEW_OWNER AND mview_name = :V_MVIEW_NAME