/* Formatted on 8/25/2020 9:53:27 AM (QP5 v5.287) */
-----------------------------****Customer****-------------------------------------------

  SELECT HOU.ORGANIZATION_ID,
         HOU.NAME ORGANIZATION,
         CA.ACCOUNT_NUMBER,
         CA.CUST_ACCOUNT_ID CUSTOMER_ID,
         HP.PARTY_NAME CUSTOMER_NAME,
         CA.STATUS ACCOUNT_STATUS,
         CSUA.STATUS CUSTOMER_SITE_STATUS,
         CA.CREATION_DATE "ACCOUNT CREATION DATE",
         CASA.CREATION_DATE "ACCOUNT SITE CREATION DATE",
         CSUA.SITE_USE_CODE,
         CSUA.SITE_USE_ID PARTY_SITE_NUMBER,
         CSUA.LOCATION,
         HP.CATEGORY_CODE,
         CSUA.PRIMARY_SALESREP_ID
         ,SAL.NAME SALESREP_NAME
         ,SAL.SALESREP_NUMBER SALESREP_NUMBER
         ,RSV.SOURCE_JOB_TITLE SALESREP_JOB_TITLE
         ,LOC.ADDRESS1||', '||LOC.ADDRESS2||', '||LOC.ADDRESS3 ADDRESS
         --,SAL.PERSON_ID
         --,paaf.SUPERVISOR_ID
         ,NVL (papf.employee_number, papf.NPW_NUMBER) SUPERVISOR_EMP_ID
    --,CA.*
    --,CASA.*
    --,CSUA.*
    --,HOU.*
    --,HP.*
    --,HPS.*
    --,LOC.*
    --,SAL.*
    --,RSV.*
    FROM APPS.HZ_CUST_ACCOUNTS CA,
         APPS.HZ_CUST_SITE_USES_ALL CSUA,
         APPS.HZ_CUST_ACCT_SITES_ALL CASA,
         APPS.HR_OPERATING_UNITS HOU,
         APPS.HZ_PARTIES HP,
         APPS.HZ_PARTY_SITES HPS,
         APPS.HZ_LOCATIONS LOC,
         JTF_RS_SALESREPS SAL,
         JTF_RS_DEFRESOURCES_V RSV,
         HR.PER_ALL_ASSIGNMENTS_F PAAF,
         HR.PER_ALL_PEOPLE_F PAPF
   WHERE     1 = 1
         AND ( :P_ORG_ID IS NULL OR CASA.ORG_ID = :P_ORG_ID)
         AND CSUA.CUST_ACCT_SITE_ID = CASA.CUST_ACCT_SITE_ID
         AND CA.CUST_ACCOUNT_ID = CASA.CUST_ACCOUNT_ID
         AND HOU.ORGANIZATION_ID = CASA.ORG_ID
         --AND CA.STATUS='A'
         --AND CSUA.STATUS='A'
         AND HP.PARTY_ID = CA.PARTY_ID
         AND HPS.PARTY_ID = HP.PARTY_ID
         AND HPS.LOCATION_ID = LOC.LOCATION_ID
         --AND HP.STATUS='A'
         --AND HPS.STATUS='A'
         AND HPS.IDENTIFYING_ADDRESS_FLAG='Y'
         --AND SITE_USE_CODE = 'BILL_TO'
         --AND CSUA.BILL_TO_SITE_USE_ID='37644'
         --AND CSUA.SITE_USE_ID='34777'
         --AND CSUA.LOCATION = '93215'
         AND SITE_USE_CODE = 'SHIP_TO'
         AND CSUA.PRIMARY_SALESREP_ID IS NOT NULL
         AND CSUA.PRIMARY_SALESREP_ID = sal.salesrep_id(+)
         AND SAL.RESOURCE_ID = RSV.RESOURCE_ID
         AND CASA.ORG_ID = SAL.ORG_ID(+)
         AND SYSDATE BETWEEN paaf.EFFECTIVE_START_DATE AND paaf.EFFECTIVE_END_DATE
         AND SAL.PERSON_ID = paaf.PERSON_ID(+)
         AND paaf.SUPERVISOR_ID = papf.PERSON_ID(+)
         --AND PRIMARY_FLAG='Y'
         --AND STATUS = 'A'
         --AND UPPER(CA.ACCOUNT_NAME) LIKE UPPER('%'||:P_CUST_NAME||'%')
         --AND ACCOUNT_NUMBER IN ('20072')
         --AND HP.CATEGORY_CODE IS NULL
         AND (   :P_CUSTOMER_NUMBER IS NULL
              OR (CA.ACCOUNT_NUMBER = :P_CUSTOMER_NUMBER))
         AND (   :P_CUST_NAME IS NULL
              OR (UPPER (HP.PARTY_NAME) LIKE UPPER ('%' || :P_CUST_NAME || '%')))
ORDER BY CA.ACCOUNT_NUMBER DESC