select
*
from
XXDBL.xxdbl_master_lc_headers;

CREATE OR REPLACE PUBLIC SYNONYM XXDBL_MASTER_LC_HEADERS FOR XXDBL.XXDBL_MASTER_LC_HEADERS;

ALTER TABLE XXDBL.xxdbl_master_lc_headers
   ADD ( LC_RCV_DATE DATE);
   
DROP PUBLIC SYNONYM XXDBL_MASTER_LC_HEADERS;