SELECT C.SEGMENT1 ITEM_CODE,
       RT.TRANSACTION_ID,
       POH.SEGMENT1 PO_NUMBER,
       PD.PO_HEADER_ID,
       PD.PO_DISTRIBUTION_ID,
       PD.PO_LINE_ID,
       PLL.ITEM_DESCRIPTION,
       PLL.UNIT_MEAS_LOOKUP_CODE UOM,
       MIC.SEGMENT2 ITEM_CATEGORY,
       MIC.SEGMENT3 ITEM_TYPE,
       NULL DEPARTMENT,
       RRSL.SOURCE_DOC_QUANTITY TRX_QUANTITY,
       --PLL.UNIT_PRICE * rrsl.SOURCE_DOC_QUANTITY TOTAL_COST,
       NVL (RRSL.ACCOUNTED_DR, 0) - NVL (RRSL.ACCOUNTED_CR, 0) TOTAL_COST,
       CC.SEGMENT1 "COMP_SEG",
       CC.SEGMENT2 "LOCATION",
       CC.SEGMENT3 "PROFIT",
       CC.SEGMENT4 "COST_CENTER",
       CC.SEGMENT5 "NATURAL_ACC",
       CC.SEGMENT6 "SUB",
       CC.SEGMENT7 "IC",
       CC.SEGMENT8 "EXPC_CATG",
       (SELECT DESCRIPTION
          FROM FND_FLEX_VALUES_VL
         WHERE FLEX_VALUE_SET_ID = 1017028 AND FLEX_VALUE = CC.SEGMENT1)
          COMPANY,
          CC.SEGMENT2
       || ' - '
       || (SELECT DESCRIPTION
             FROM FND_FLEX_VALUES_VL
            WHERE FLEX_VALUE_SET_ID = 1017031 AND FLEX_VALUE = CC.SEGMENT3)
          LOCATION_DESC,
          CC.SEGMENT3
       || ' - '
       || (SELECT DESCRIPTION
             FROM FND_FLEX_VALUES_VL
            WHERE FLEX_VALUE_SET_ID = 1017031 AND FLEX_VALUE = CC.SEGMENT3)
          PRODUCT_LINE_DESC,
          CC.SEGMENT4
       || ' - '
       || (SELECT DESCRIPTION
             FROM FND_FLEX_VALUES_VL
            WHERE FLEX_VALUE_SET_ID = 1017032 AND FLEX_VALUE = CC.SEGMENT4)
          COST_CENTER_DESC,
          CC.SEGMENT5
       || ' - '
       || (SELECT DESCRIPTION
             FROM FND_FLEX_VALUES_VL
            WHERE FLEX_VALUE_SET_ID = 1017040 AND FLEX_VALUE = CC.SEGMENT5)
          NATURAL_ACCOUNT_DESC,
          CC.SEGMENT6
       || ' - '
       || (SELECT DESCRIPTION
             FROM APPS.FND_FLEX_VALUES_TL
            WHERE FLEX_VALUE_ID =
                     (SELECT FLEX_VALUE_ID
                        FROM APPS.FND_FLEX_VALUES
                       WHERE     FLEX_VALUE_SET_ID =
                                    (SELECT FLEX_VALUE_SET_ID
                                       FROM APPS.FND_FLEX_VALUE_SETS
                                      WHERE FLEX_VALUE_SET_NAME =
                                               'XXDBL_SUB_ACCOUNT_COA')
                             AND FLEX_VALUE = CC.SEGMENT6
                             AND PARENT_FLEX_VALUE_LOW =
                                    (SELECT FLEX_VALUE
                                       FROM FND_FLEX_VALUES_VL B
                                      WHERE     FLEX_VALUE_SET_ID = 1017040
                                            AND B.FLEX_VALUE = CC.SEGMENT5)))
          SUB_ACCCOUNT_DESC,
          CC.SEGMENT8
       || ' - '
       || (SELECT DESCRIPTION
             FROM FND_FLEX_VALUES_VL
            WHERE FLEX_VALUE_SET_ID = 1017038 AND FLEX_VALUE = CC.SEGMENT8)
          EXP_CATEGORY_DESC,
       OOD.OPERATING_UNIT ORG_ID,
       OOD.ORGANIZATION_ID,
       OOD.ORGANIZATION_NAME,
       RT.TRANSACTION_DATE,
       RRSL.PERIOD_NAME
  FROM RCV_RECEIVING_SUB_LEDGER RRSL,
       RCV_TRANSACTIONS RT,
       PO_DISTRIBUTIONS_ALL PD,
       PO_LINES_ALL PLL,
       po_headers_all POH,
       GL_CODE_COMBINATIONS CC,
       MTL_SYSTEM_ITEMS_B_KFV C,
       MTL_ITEM_CATEGORIES_V MIC,
       ORG_ORGANIZATION_DEFINITIONS OOD
 WHERE     PD.PO_DISTRIBUTION_ID = RT.PO_DISTRIBUTION_ID
       AND RT.TRANSACTION_ID = RRSL.RCV_TRANSACTION_ID
       AND RT.PO_DISTRIBUTION_ID = RRSL.REFERENCE3
       AND PD.PO_LINE_ID = PLL.PO_LINE_ID
       AND PD.CODE_COMBINATION_ID = CC.CODE_COMBINATION_ID
       AND CC.CODE_COMBINATION_ID = RRSL.CODE_COMBINATION_ID
       AND MIC.INVENTORY_ITEM_ID = C.INVENTORY_ITEM_ID
       AND MIC.ORGANIZATION_ID = C.ORGANIZATION_ID
       AND RRSL.SET_OF_BOOKS_ID = OOD.SET_OF_BOOKS_ID
       AND OOD.ORGANIZATION_ID = RT.ORGANIZATION_ID
       AND C.ORGANIZATION_ID = RT.ORGANIZATION_ID
       AND C.INVENTORY_ITEM_ID = PLL.ITEM_ID
       AND PD.DESTINATION_ORGANIZATION_ID = C.ORGANIZATION_ID
       and PLL.PO_HEADER_ID=POH.PO_HEADER_ID
       --AND RRSL.REFERENCE4 = '10633000205'
       --AND ACCOUNTING_LINE_TYPE = 'Charge'
      -- AND RRSL.SET_OF_BOOKS_ID = :P_SET_OF_BOOKS_ID
       -- AND RRSL.SET_OF_BOOKS_ID in ('2027','2035','2039','2043','2031')
       AND ( :P_ORG_ID IS NULL OR RT.ORGANIZATION_ID = :P_ORG_ID)
       AND :P_REPORT_TYPE = 'Details'
       AND ( :P_ACCOUNT IS NULL OR CC.SEGMENT5 = :P_ACCOUNT)
       AND MIC.CATEGORY_SET_ID = 1
       AND TRUNC (RT.TRANSACTION_DATE) BETWEEN :P_DATE_FROM AND :P_DATE_TO
       
       
