/* Formatted on 1/9/2022 10:14:37 AM (QP5 v5.374) */
CREATE TABLE XXDBL.XXDBL_GL_ALOC_BASIS_9122
AS
    SELECT * FROM XXDBL.XXDBL_GL_ALOC_BASIS_UPLOAD_STG;


SELECT * FROM xxdbl.XXDBL_GL_ALOC_BASIS_9122;

SELECT * FROM XXDBL.XXDBL_GL_ALOC_BASIS_UPLOAD_STG;