/* Formatted on 6/24/2019 10:52:23 AM (QP5 v5.287) */
SELECT CT.ORG_ID,
       CL.SALES_ORDER,
       CL.SALES_ORDER_DATE,
       CL.INVENTORY_ITEM_ID,
       CL.DESCRIPTION,
       CL.UOM_CODE UOM,
       CL.QUANTITY_ORDERED,
       CL.QUANTITY_INVOICED,
       CT.TRX_NUMBER TRANSACTION_NUMBER,
       CT.TRX_DATE,
       CT.BILL_TO_CUSTOMER_ID,
       CT.BILL_TO_SITE_USE_ID,
       CT.SHIP_TO_CUSTOMER_ID,
       CT.SHIP_TO_SITE_USE_ID,
       CT.REMIT_TO_ADDRESS_ID,
       (SELECT    ADDRESS1
               || ','
               || ADDRESS2
               || ','
               || ADDRESS3
               || ','
               || ADDRESS4
          FROM APPS.HZ_LOCATIONS LOC
         WHERE LOC.LOCATION_ID = CT.REMIT_TO_ADDRESS_ID)
          ADDRESS,
       CT.SHIP_DATE_ACTUAL,
       CT.DOC_SEQUENCE_VALUE,
       --CL.ORG_ID,
       CL.UNIT_STANDARD_PRICE,
       CL.UNIT_SELLING_PRICE,
       CL.INTERFACE_LINE_ATTRIBUTE2 ORDER_TYPE,
       CL.REVENUE_AMOUNT,
       CL.WAREHOUSE_ID,
       DECODE (CL.LINE_TYPE,  'LINE', 'LINE_TOTAL',  'TAX', 'TOTAL_TAX')
          LINE_TYPE,
       DST.AMOUNT,
       DST.GL_DATE,
       DST.GL_POSTED_DATE,
       DST.ACCOUNT_CLASS,
       DST.ACCTD_AMOUNT,
       TT.NAME TRANSACTION_NAME,
       TT.DESCRIPTION TRANSACTION_DESCRIPTION,
       (SELECT DESCRIPTION
          FROM APPS.AR_LOOKUPS VAL
         WHERE LOOKUP_TYPE = 'TRANSACTION TYPE' AND LOOKUP_CODE = TT.TYPE)
          TRANSACTION_TYPE
  --,DECODE (TT.TYPE,
  --                 'CB', 'Chargeback',
  --                 'CM', 'Credit Memo',
  --                 'DM', 'Debit Memo',
  --                 'DEP', 'Deposit',
  --                 'GUAR', 'Guarantee',
  --                 'INV', 'Invoice',
  --                 'PMT', 'Receipt',
  --                 'Others'
  --                ) TRANSACTION_TYPE
  --,DST.ORG_ID
  --,CL.SHIP_TO_CUSTOMER_ID CUSTOMER_ID
  --,CL.SHIP_TO_SITE_USE_ID
  --,CL.*
  --,CT.*
  ,DST.*
  --,TT.*
  FROM APPS.RA_CUSTOMER_TRX_ALL CT,
       APPS.RA_CUSTOMER_TRX_LINES_ALL CL,
       APPS.RA_CUST_TRX_LINE_GL_DIST_ALL DST,
       APPS.RA_CUST_TRX_TYPES_ALL TT
 WHERE     1 = 1
       AND ((:P_ORG_ID IS NULL)  OR (CT.ORG_ID=:P_ORG_ID))
       AND (:P_ORDER_NUMBER IS NULL OR (CL.SALES_ORDER=:P_ORDER_NUMBER))
       AND (:P_VOUCHER_NUM IS NULL OR (CT.DOC_SEQUENCE_VALUE=:P_VOUCHER_NUM))
       AND CT.CUSTOMER_TRX_ID = CL.CUSTOMER_TRX_ID
       AND CT.CUSTOMER_TRX_ID = DST.CUSTOMER_TRX_ID
       AND DST.CUSTOMER_TRX_LINE_ID = CL.CUSTOMER_TRX_LINE_ID
       AND CT.CUST_TRX_TYPE_ID = TT.CUST_TRX_TYPE_ID
       AND TRUNC(DST.GL_DATE) BETWEEN NVL(:P_DATE_FROM,TRUNC(DST.GL_DATE)) AND NVL(:P_DATE_TO,TRUNC(DST.GL_DATE))
       AND TRUNC(DST.LAST_UPDATE_DATE) BETWEEN NVL(:P_UPDATE_FROM,TRUNC(DST.LAST_UPDATE_DATE)) AND NVL(:P_UPDATE_TO,TRUNC(DST.LAST_UPDATE_DATE))
       --AND DST.GL_DATE = TO_DATE ('10-OCT-2019', 'DD-MON-YYYY')
       ;

-------------------------------------------------------------------------------

SELECT  CR.RECEIPT_NUMBER
        ,CR.DOCUMENT_NUMBER
        ,CR.GL_DATE
        ,CR.REMIT_BANK_ACCOUNT_NUM
        ,CR.REMIT_BANK_ACCOUNT_NAME
        ,CR.REMIT_BANK_ACCOUNT_NUM ACCOUNT_NAME
        ,CR.REMIT_BANK_NAME
        ,NVL (CH.ACCTD_AMOUNT, CR.FUNCTIONAL_AMOUNT) AMOUNT
        ,CUST.ACCOUNT_NUMBER CUSTOMER_NO
        ,GCC.SEGMENT1||'.'||GCC.SEGMENT2||'.'||GCC.SEGMENT3||'.'||GCC.SEGMENT4||'.'||GCC.SEGMENT5 GL_ACC_CODE
        --,NVL (CH.GL_DATE, CR.GL_DATE) GL_DATE
        --CBA.SECONDARY_ACCOUNT_REFERENCE,
        --,CBA.*
        --,CH.*
        --,CR.*
        --,RA.*
        ,RA.LAST_UPDATE_DATE
 FROM APPS.XX_AR_CASH_RECEIPTS_V CR,
      APPS.AR_CASH_RECEIPT_HISTORY_ALL CH,
      APPS.CE_BANK_ACCOUNTS CBA,
      APPS.AR_RECEIVABLE_APPLICATIONS_ALL RA,
      APPS.HZ_CUST_ACCOUNTS CUST
      ,APPS.GL_CODE_COMBINATIONS GCC
 WHERE 1=1
      AND CR.CASH_RECEIPT_ID = CH.CASH_RECEIPT_ID
      AND CR.REMIT_BANK_ACCOUNT_ID = CBA.BANK_ACCOUNT_ID(+)
      AND CH.CASH_RECEIPT_HISTORY_ID=RA.CASH_RECEIPT_HISTORY_ID(+)
      AND CR.CASH_RECEIPT_ID = RA.CASH_RECEIPT_ID(+)
      AND CR.CUSTOMER_NUMBER = CUST.ACCOUNT_NUMBER(+)
      --AND CH.ACCOUNT_CODE_COMBINATION_ID=GCC.CODE_COMBINATION_ID(+)
      AND RA.CODE_COMBINATION_ID=GCC.CODE_COMBINATION_ID(+)
      AND ((:P_ORG_ID IS NULL AND CH.ORG_ID IN (83,84,85,605))  OR (CH.ORG_ID=:P_ORG_ID))
      --AND CR.BAL_SEG='2110'
      AND CR.DOCUMENT_NUMBER='BACDAK001089L'
      --AND GCC.SEGMENT3='1070201'
      --AND CR.LEGAL_ENTITY_ID='23279'
      --AND BB.BRANCH_PARTY_ID(+) = CBA.BANK_BRANCH_ID
      --AND NVL (CH.CURRENT_RECORD_FLAG, 'N') = 'Y'
      --and NVL (CH.GL_DATE, CR.GL_DATE)>='01-JUL-2017'
      --and NVL (CH.GL_DATE, CR.GL_DATE)<='30-JUN-2018'
      --AND NVL (STATE, 'AKG') <> 'REVERSED'
      --AND CR.CASH_RECEIPT_ID='2430286'
      --AND CR.RECEIPT_STATUS != 'REV'
      --AND CR.TYPE = 'CASH'
      --AND CH.gl_date = TO_DATE ('17-JUN-2019', 'DD-MON-YYYY')
      --AND CR.REMIT_BANK_NAME not in ('AP-AR  Netting Bank','CC-29902001914')
      --AND CR.REMIT_BANK_ACCOUNT_NUM = 'STD-2030155672041'--'CC-29902001914'
       AND TRUNC(RA.GL_DATE) BETWEEN NVL(:P_DATE_FROM,TRUNC(RA.GL_DATE)) AND NVL(:P_DATE_TO,TRUNC(RA.GL_DATE))
       AND TRUNC(RA.LAST_UPDATE_DATE) BETWEEN NVL(:P_UPDATE_FROM,TRUNC(RA.LAST_UPDATE_DATE)) AND NVL(:P_UPDATE_TO,TRUNC(RA.LAST_UPDATE_DATE))