/* Formatted on 5/27/2019 10:02:30 AM (QP5 v5.287) */
  SELECT DIS.MODIFIER_NAME,
         DIS.PRODUCT_ATTR_VALUE ITEM_NUMBER,
         DIS.MOD_LINE_NO MODIFIER_LINE_NO,
         DIS.GROUP_NO,
         QUALIFIER_ATTR_TYPE,
         DIS.ADJUST_RATE AMOUNT,  
         --TRUNC(DESC_ATTRIB_VALUE_FROM) ORDERED_DATE,
         DESC_ATTRIB_VALUE_FROM,
         DIS.OPERATOR,
         DESC_ATTRIB_VALUE_TO,
         DIS.AUTOMATIC_FLAG,
         DIS.ACCRUAL_FLAG,
         DIS.START_DATE,
         DIS.END_DATE
         --,DIS.*
    FROM APPS.XXAKG_QP_MODIFIER_DISCOUNT_V DIS
   WHERE 1 = 1 
         AND UPPER(DIS.MODIFIER_NAME) LIKE UPPER('%'||:P_MODIFIER_NAME||'%') 
         --AND MODIFIER_NAME = 'SCIL General Commission' 
         --AND DIS.MOD_LINE_NO='1293340'                     
         --AND QUALIFIER_ATTR_TYPE='Order Date'
         --AND TRUNC (DESC_ATTRIB_VALUE_FROM, 'DD-MON-RRRR') ='15-JUL-2018'
         --AND EXISTS(SELECT 1 FROM APPS.QP_QUALIFIERS QQ WHERE DIS.MOD_LINE_NO=QQ.LIST_LINE_ID AND DIS.GROUP_NO=QQ.QUALIFIER_GROUPING_NO AND TO_CHAR(CREATION_DATE,'YYYY/MON/DD HH24:MI:SS') BETWEEN '2019/MAR/07 00:00:00' AND '2019/MAR/07 23:59:59')--HH:MI:SS--12:00:00
         AND DIS.END_DATE IS NULL AND DIS.AUTOMATIC_FLAG = 'Y'
ORDER BY DIS.MOD_LINE_NO, DIS.GROUP_NO;

------------------------------------------------------------------------------------------------

  SELECT QLH.NAME DISCOUNT_NAME,
         QQ.QUALIFIER_CONTEXT QUALIFIER_TYPE,
         MSI.SEGMENT1 || '.' || MSI.SEGMENT2 || '.' || MSI.SEGMENT3 ITEM_CODE,
         MSI.DESCRIPTION,
         QPA.PRODUCT_UOM_CODE UOM,
         --QR.NAME MODIFIER_NAME,
         QPA.LIST_LINE_ID MODIFIER_LINE_NO,
         QQ.QUALIFIER_GROUPING_NO QUALIFIER_GROUP_NO,
         QQ.QUALIFIER_ATTR_VALUE QUALIFIER_ATTR_VALUE_FROM,
         QQ.COMPARISON_OPERATOR_CODE OPERATOR,
         QQ.QUALIFIER_ATTR_VALUE_TO,
         QQ.START_DATE_ACTIVE START_DATE,
         QQ.END_DATE_ACTIVE END_DATE,
         QLL.START_DATE_ACTIVE MODIFIER_LINE_START,
         QLL.END_DATE_ACTIVE MODIFIER_LINE_END,
         QLL.OPERAND VALUE
    --,QQ.*
    --,QPA.*
    --,QLH.*
    --,QLL.*
    FROM APPS.QP_QUALIFIERS QQ,
         APPS.QP_PRICING_ATTRIBUTES QPA,
         APPS.QP_LIST_HEADERS_VL QLH,
         APPS.QP_LIST_LINES QLL,
         APPS.MTL_SYSTEM_ITEMS_B MSI
   WHERE     1 = 1
         AND MSI.ORGANIZATION_ID='91'
         AND QLH.ORIG_ORG_ID=85
         AND QLL.LIST_HEADER_ID = QPA.LIST_HEADER_ID
         AND QLL.LIST_LINE_ID = QPA.LIST_LINE_ID
         AND QQ.LIST_HEADER_ID = QLH.LIST_HEADER_ID
         AND TO_CHAR (QPA.PRODUCT_ATTR_VALUE) = MSI.INVENTORY_ITEM_ID
         AND QQ.LIST_HEADER_ID = QPA.LIST_HEADER_ID
         AND QQ.LIST_LINE_ID = QPA.LIST_LINE_ID
         --AND QQ.LIST_LINE_ID='1293340'
         --AND TO_CHAR(QQ.CREATION_DATE,'YYYY/MON/DD HH24:MI:SS') BETWEEN '2019/FEB/24 00:00:00' AND '2019/FEB/24 23:59:59'--HH:MI:SS--12:00:00
         --AND MSI.SEGMENT1||'.'||MSI.SEGMENT2||'.'||MSI.SEGMENT3 IN ('CMNT.SBLK.0001')
         --AND QQ.END_DATE_ACTIVE IS NULL
         AND QLH.NAME = 'SCIL Inter Group Discount'
ORDER BY QPA.LIST_LINE_ID, QQ.QUALIFIER_GROUPING_NO