SELECT
*
FROM
XXDBL_TRANSPOTER_HEADERS TH
,XXDBL_TRANSPOTER_LINE TL
WHERE 1=1
AND TH.TRANSPOTER_HEADER_ID=TL.TRANSPOTER_HEADER_ID
AND TH.TRANSPOTER_CHALLAN_NUMBER='TRAN-009879'

--------------------------------------------------------------------------------
SELECT
*
FROM
XXDBL_TRANSPOTER_HEADERS;


SELECT
*
FROM
XXDBL_TRANSPOTER_LINE;
