SELECT
*
FROM
XXDBL.XXVEH_ACTIVITIES;

ALTER TABLE XXDBL.XXVEH_ACTIVITIES 
ADD (
  LEGAL_ENTITY_ID NUMBER,
  LEGAL_ENTITY_NAME VARCHAR2(200),
  LEDGER_NAME VARCHAR2(200),
  CHART_OF_ACCT_ID NUMBER
);



CREATE OR REPLACE SYNONYM APPSRO.XXVEH_ACTIVITIES FOR XXDBL.XXVEH_ACTIVITIES;


ALTER TABLE XXDBL.XXVEH_ACTIVITIES 
ADD (
  DR_CCID NUMBER,
  DR_CODE_COMB VARCHAR2(500)
);