

CREATE TABLE APPS.XXDBL_CERAMIC_GATE_PASS_DTL
(
  GATE_PASS_DTL_ID  NUMBER,
  GATE_PASS_HDR_ID  NUMBER,
  ITEM_DESCRIPTION     VARCHAR2(100 BYTE),
  UNIT                 VARCHAR2(50 BYTE),
  QUANTITY             NUMBER,
  REMARKS              VARCHAR2(200 BYTE),
  PURPOSE              VARCHAR2(200 BYTE)
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX APPS.XXDBL_CERAMIC_GATE_PASS_DTL_PK ON APPS.XXDBL_CERAMIC_GATE_PASS_DTL
(GATE_PASS_DTL_ID)
LOGGING
TABLESPACE APPS_TS_TX_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             128K
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE APPS.XXDBL_CERAMIC_GATE_PASS_DTL ADD (
  CONSTRAINT XXDBL_CERAMIC_GATE_PASS_DTL_PK
  PRIMARY KEY
  (GATE_PASS_DTL_ID)
  USING INDEX APPS.XXDBL_CERAMIC_GATE_PASS_DTL_PK
  ENABLE VALIDATE);

ALTER TABLE APPS.XXDBL_CERAMIC_GATE_PASS_DTL ADD (
  CONSTRAINT XXDBL_CERAMIC_GATE_PASS_DTL_FK 
  FOREIGN KEY (GATE_PASS_HDR_ID) 
  REFERENCES APPS.XXDBL_CERAMIC_GATE_PASS_HDR (GATE_PASS_HDR_ID)
  ENABLE VALIDATE);
