CREATE OR REPLACE PACKAGE APPS.xx_dbl_item_template AS
    gn_batch_id NUMBER := -1;
    PROCEDURE xxdbl_insert (
        p_new_at                       IN   VARCHAR2 DEFAULT NULL,
        p_item_code                    IN   VARCHAR2 DEFAULT NULL,
        p_item_description             IN   VARCHAR2 DEFAULT NULL,
        p_primary_uom                  IN   VARCHAR2 DEFAULT NULL,
        p_secondary_uom                IN   VARCHAR2 DEFAULT NULL,
        p_item_conversion_factor       IN   VARCHAR2 DEFAULT NULL,
        p_organization_code            IN   VARCHAR2 DEFAULT NULL,
        p_item_template                IN   VARCHAR2 DEFAULT NULL,
        p_inv_category_set             IN   VARCHAR2 DEFAULT NULL,
        p_item_category_segment1       IN   VARCHAR2 DEFAULT NULL,
        p_item_category_segment2       IN   VARCHAR2 DEFAULT NULL,
        p_item_category_segment3       IN   VARCHAR2 DEFAULT NULL,
        p_item_category_segment4       IN   VARCHAR2 DEFAULT NULL,
        p_sales_category_set           IN   VARCHAR2 DEFAULT NULL,
        p_sales_category_segment1      IN   VARCHAR2 DEFAULT NULL,
        p_sales_category_segment2      IN   VARCHAR2 DEFAULT NULL,
        p_cogs_account                 IN   VARCHAR2 DEFAULT NULL,
        p_sales_account                IN   VARCHAR2 DEFAULT NULL,
        p_rma_insp_reqd                IN   VARCHAR2 DEFAULT NULL,
        p_supply_sub_inv               IN   VARCHAR2 DEFAULT NULL,
        p_supply_loc                   IN   VARCHAR2 DEFAULT NULL,
        p_yield_sub_inv                IN   VARCHAR2 DEFAULT NULL,
        p_yield_loc                    IN   VARCHAR2 DEFAULT NULL,
        p_status                       IN   VARCHAR2 DEFAULT NULL,
        p_status_message               IN   VARCHAR2 DEFAULT NULL,
        p_attr_context                 IN   VARCHAR2 DEFAULT NULL,
        p_legacy_item_code             IN   VARCHAR2 DEFAULT NULL,
        p_product_line                 IN   VARCHAR2 DEFAULT NULL,
        p_set_proc_id                  IN   VARCHAR2 DEFAULT NULL,
        p_fixed_lead_time              IN   VARCHAR2 DEFAULT NULL,
        p_fixed_days_supply            IN   VARCHAR2 DEFAULT NULL,
        p_plan_cat_set                 IN   VARCHAR2 DEFAULT NULL,
        p_pln_item_category_segment1   IN   VARCHAR2 DEFAULT NULL,
        p_pln_item_category_segment2   IN   VARCHAR2 DEFAULT NULL,
        p_pln_item_category_segment3   IN   VARCHAR2 DEFAULT NULL,
        p_pln_item_category_segment4   IN   VARCHAR2 DEFAULT NULL,
        p_planner                      IN   VARCHAR2 DEFAULT NULL,
        p_item_type                    IN   VARCHAR2 DEFAULT NULL,
        p_long_description             IN   VARCHAR2 DEFAULT NULL,
        p_weight_uom_code              IN   VARCHAR2 DEFAULT NULL,
        p_unit_weight                  IN   VARCHAR2 DEFAULT NULL,
        p_catalog_1_item_type          IN   VARCHAR2 DEFAULT NULL,
        p_catalog_2_art                IN   VARCHAR2 DEFAULT NULL,
        p_catalog_3_length             IN   VARCHAR2 DEFAULT NULL,
        p_catalog_4_tkt                IN   VARCHAR2 DEFAULT NULL,
        p_catalog_5_shade              IN   VARCHAR2 DEFAULT NULL,
        p_brand_short_code             IN   VARCHAR2 DEFAULT NULL,
        p_tracking_uom_mode            IN   VARCHAR2 DEFAULT NULL,
        p_pricing_uom_mode             IN   VARCHAR2 DEFAULT NULL,
        p_dye_house_kg_per_pkg         IN   VARCHAR2 DEFAULT NULL,
        p_status_catalog               IN   VARCHAR2 DEFAULT NULL,
        p_status_message_catalog       IN   VARCHAR2 DEFAULT NULL,
        p_catalog_batch_number         IN   VARCHAR2 DEFAULT NULL,
        p_hs_code                      IN   VARCHAR2 DEFAULT NULL

    );

END xx_dbl_item_template;
/
