/* Formatted on 11/1/2021 5:12:05 PM (QP5 v5.365) */
ALTER TABLE XXDBL.XXDBL_INVOICE_TRACKING_SYSTEM
    ADD (MOBILE_NUMBER VARCHAR2 (100));


CREATE OR REPLACE SYNONYM APPS.XXDBL_INVOICE_TRACKING_SYSTEM FOR XXDBL.XXDBL_INVOICE_TRACKING_SYSTEM;

CREATE OR REPLACE SYNONYM APPSRO.XXDBL_INVOICE_TRACKING_SYSTEM FOR XXDBL.XXDBL_INVOICE_TRACKING_SYSTEM;

CREATE OR REPLACE SYNONYM SYS.XXDBL_INVOICE_TRACKING_SYSTEM FOR XXDBL.XXDBL_INVOICE_TRACKING_SYSTEM;

GRANT SELECT ON XXDBL.XXDBL_INVOICE_TRACKING_SYSTEM TO APPSRO;