SELECT PRH.SEGMENT1 "Requisition Number",
         PHA.SEGMENT1 "PO Number",
         PRH.REQUISITION_HEADER_ID,
         (SELECT PF.FIRST_NAME || ' ' || PF.MIDDLE_NAMES || ' ' || PF.LAST_NAME
            FROM PER_PEOPLE_F PF
           WHERE     PRL.SUGGESTED_BUYER_ID = PF.PERSON_ID
                 AND SYSDATE BETWEEN PF.EFFECTIVE_START_DATE
                                 AND PF.EFFECTIVE_END_DATE)
            BUYER,
         PRL.SUGGESTED_BUYER_ID,
         PRH.ORG_ID,
         TO_CHAR (PRH.CREATION_DATE, 'DD-MON-RRRR HH12:MI:SS PM') CREATION_DATE,
         PRH.AUTHORIZATION_STATUS,
         PRH.DESCRIPTION,
         PROJECT.PROJECT_NAME,
         TO_CHAR (PRH.APPROVED_DATE, 'DD-MON-RRRR HH12:MI:SS PM') APPROVED_DATE,
         PRH.ATTRIBUTE8 PURPOSE,
         PRH.ATTRIBUTE8 CATEGORIES,
         MSI.SEGMENT1,
         (SELECT DECODE (A.CURRENCY_CODE,
                         'BDT', A.UNIT_PRICE,
                         A.UNIT_PRICE * NVL (RATE, 1))
                    RATE
            FROM (SELECT PHA.SEGMENT1,
                         PHA.CURRENCY_CODE,
                         PLA.UNIT_PRICE,
                         PHA.RATE,
                         ROW_NUMBER ()
                         OVER (PARTITION BY MSI.SEGMENT1
                               ORDER BY PHA.APPROVED_DATE DESC)
                            CORR
                    FROM PO_HEADERS_ALL PHA,
                         PO_LINES_ALL PLA,
                         PO_LINE_LOCATIONS_ALL PLL,
                         MTL_SYSTEM_ITEMS_B MSI,
                         ORG_ORGANIZATION_DEFINITIONS ORG,
                         HR_OPERATING_UNITS HOU
                   WHERE     PHA.PO_HEADER_ID = PLA.PO_HEADER_ID
                         AND PHA.ORG_ID = PLA.ORG_ID
                         AND PHA.ORG_ID = HOU.ORGANIZATION_ID
                         AND PHA.PO_HEADER_ID = PLL.PO_HEADER_ID
                         AND PLA.PO_LINE_ID = PLL.PO_LINE_ID
                         AND PLA.ITEM_ID = MSI.INVENTORY_ITEM_ID
                         AND PLL.SHIP_TO_ORGANIZATION_ID = MSI.ORGANIZATION_ID
                         AND PLL.SHIP_TO_ORGANIZATION_ID = ORG.ORGANIZATION_ID
                         AND TYPE_LOOKUP_CODE = 'STANDARD'
                         AND MSI.SEGMENT1 = MSI.SEGMENT1
                         AND MSI.INVENTORY_ITEM_ID = PRL.ITEM_ID
                         AND PHA.AUTHORIZATION_STATUS = 'APPROVED'
                         --AND PHA.VENDOR_ID!='1517'
                         --AND ORG.OPERATING_UNIT!=135
                         ) A
           WHERE CORR = 1)
            LAST_PRICE,
         (/* Formatted on 1/15/2020 5:58:43 PM (QP5 v5.287) */
SELECT A.VENDOR_NAME || '(' || A.SEGMENT1 || ')' SUPPLIER
  FROM (SELECT PHA.SEGMENT1,
               SUP.VENDOR_NAME,
               ROW_NUMBER ()
               OVER (PARTITION BY MSI.SEGMENT1
                     ORDER BY PHA.APPROVED_DATE DESC)
                  CORR
          FROM PO_HEADERS_ALL PHA,
               PO_LINES_ALL PLA,
               AP_SUPPLIERS SUP,
               PO_LINE_LOCATIONS_ALL PLL,
               MTL_SYSTEM_ITEMS_B MSI,
               ORG_ORGANIZATION_DEFINITIONS ORG,
               HR_OPERATING_UNITS HOU
         WHERE     PHA.PO_HEADER_ID = PLA.PO_HEADER_ID
               AND PHA.ORG_ID = PLA.ORG_ID
               AND PHA.VENDOR_ID = SUP.VENDOR_ID
               AND PHA.ORG_ID = HOU.ORGANIZATION_ID
               AND PHA.PO_HEADER_ID = PLL.PO_HEADER_ID
               AND PLA.PO_LINE_ID = PLL.PO_LINE_ID
               AND PLA.ITEM_ID = MSI.INVENTORY_ITEM_ID
               AND PLL.SHIP_TO_ORGANIZATION_ID = MSI.ORGANIZATION_ID
               AND PLL.SHIP_TO_ORGANIZATION_ID = ORG.ORGANIZATION_ID
               AND TYPE_LOOKUP_CODE = 'STANDARD'
               -- and MSI.SEGMENT1='SPRECONS000000035426'
               AND MSI.INVENTORY_ITEM_ID = PRL.ITEM_ID
               AND PHA.AUTHORIZATION_STATUS = 'APPROVED'
               --AND PHA.VENDOR_ID!='1517'
               --AND ORG.OPERATING_UNIT!=135
               ) A
 WHERE CORR = 1)
            LAST_SUPPLIER,
         NVL (MSI.DESCRIPTION, PRL.ITEM_DESCRIPTION) DESCRIPTION,
         PRL.UNIT_MEAS_LOOKUP_CODE UOM,
         PRL.LINE_NUM,
         PRL.QUANTITY,
         PRL.ATTRIBUTE1 BRAND,
         PRL.ATTRIBUTE2 ORGIN,
         PRL.ATTRIBUTE3 MAKE,
         PRL.ATTRIBUTE7 USE_OF_AREA,
         NVL (SUB.DESCRIPTION, SECONDARY_INVENTORY_NAME) SUBINV,
         --  prl.attribute5 buyer_id,
         -- prl.attribute6 Order_no,
         PRL.ITEM_ID,
         MOQ.ON_HAND,
         PRL.NEED_BY_DATE,
         LTRIM (
            RTRIM (
                  PPF.FIRST_NAME
               || ' '
               || PPF.MIDDLE_NAMES
               || ' '
               || PPF.LAST_NAME))
            GLOBAL_NAME,
         PRL.DESTINATION_SUBINVENTORY SUBINVENTORY,
         NVL (HRL.DESCRIPTION, HRL.LOCATION_CODE) LOCATION,
         PRL.ATTRIBUTE6 REMARKS,
         DECODE (PRL.ATTRIBUTE_CATEGORY,
                 'Item Details', PRL.ATTRIBUTE4,
                 PRL.ATTRIBUTE4)
            BUYER_ID,
         PRL.ATTRIBUTE5 ORDER_NO,
         PDA.REQ_DISTRIBUTION_ID
    FROM PO_REQUISITION_HEADERS_ALL PRH,
         PO_REQUISITION_LINES_ALL PRL,
         MTL_SYSTEM_ITEMS_B MSI,
         ALL_PROJECT_INFO_MASTER PROJECT,
         HR_LOCATIONS_ALL HRL,
         FND_USER FU,
         PER_PEOPLE_F PPF,
         (  SELECT INVENTORY_ITEM_ID,
                   ORGANIZATION_ID,
                   SUM (NVL (TRANSACTION_QUANTITY, 0)) ON_HAND
              FROM MTL_ONHAND_QUANTITIES
          GROUP BY INVENTORY_ITEM_ID, ORGANIZATION_ID) MOQ,
         APPS.PO_REQ_DISTRIBUTIONS_ALL PROD,
         APPS.PO_DISTRIBUTIONS_ALL PDA,
         APPS.PO_LINES_ALL PLA,
         APPS.PO_LINE_LOCATIONS_ALL PLL,
         APPS.PO_HEADERS_ALL PHA,
         MTL_SECONDARY_INVENTORIES SUB
   WHERE     PRH.REQUISITION_HEADER_ID = PRL.REQUISITION_HEADER_ID
         AND PRL.ITEM_ID = MSI.INVENTORY_ITEM_ID(+)
         AND PRL.DESTINATION_ORGANIZATION_ID = MSI.ORGANIZATION_ID(+)
         AND PRL.ITEM_ID = MOQ.INVENTORY_ITEM_ID(+)
         AND PRL.DESTINATION_ORGANIZATION_ID = MOQ.ORGANIZATION_ID(+)
         AND PRH.ATTRIBUTE4 = PROJECT.PROJECT_ID(+)
         AND PRL.DELIVER_TO_LOCATION_ID = HRL.LOCATION_ID
         AND PRH.CREATED_BY = FU.USER_ID(+)
         AND PRL.REQUISITION_LINE_ID = PROD.REQUISITION_LINE_ID
         AND PROD.DISTRIBUTION_ID = PDA.REQ_DISTRIBUTION_ID(+)
         AND PDA.PO_LINE_ID = PLA.PO_LINE_ID(+)
         AND PDA.LINE_LOCATION_ID = PLL.LINE_LOCATION_ID(+)
         AND PLL.PO_LINE_ID = PLA.PO_LINE_ID(+)
         AND PLL.PO_HEADER_ID = PHA.PO_HEADER_ID(+)
         AND PDA.PO_HEADER_ID = PHA.PO_HEADER_ID(+)
         AND PLL.PO_LINE_ID = PLA.PO_LINE_ID(+)
         AND FU.EMPLOYEE_ID = PPF.PERSON_ID(+)
         AND PRL.DESTINATION_SUBINVENTORY = SUB.SECONDARY_INVENTORY_NAME(+) ---DESTINATION_SUBINVENTORY
         AND PRL.DESTINATION_ORGANIZATION_ID = SUB.ORGANIZATION_ID(+)
         AND SYSDATE BETWEEN PPF.EFFECTIVE_START_DATE
                         AND PPF.EFFECTIVE_END_DATE
         AND PRL.CANCEL_DATE IS NULL
         AND PRH.ORG_ID = :P_ORG_ID
         AND PRL.DESTINATION_ORGANIZATION_ID =
                NVL ( :P_DEST_ORG_ID, PRL.DESTINATION_ORGANIZATION_ID)
         AND (   :P_REQUISITION_FROM IS NULL
              OR PRH.REQUISITION_HEADER_ID BETWEEN :P_REQUISITION_FROM
                                               AND :P_REQUISITION_TO)
         AND PRH.AUTHORIZATION_STATUS =
                NVL ( :P_AUTHORIZATION_STATUS, PRH.AUTHORIZATION_STATUS)
         AND (   :P_FROM_CREATION_DATE IS NULL
              OR TRUNC (PRH.CREATION_DATE) BETWEEN :P_FROM_CREATION_DATE
                                               AND :P_TO_CREATION_DATE)
ORDER BY PRL.LINE_NUM