/* Formatted on 2/6/2021 11:42:06 AM (QP5 v5.287) */
CREATE TABLE XXDBL.XXDBL_CER_MONTHLY_TARGET
(
   SL_NO            INTEGER
                       GENERATED ALWAYS AS IDENTITY (       START WITH 1 INCREMENT BY 1)
                       NOT NULL,
   CREATION_DATE    DATE,
   CREATED_BY       NUMBER,
   RANK_NO          NUMBER,
   DEALER_NUMBER    VARCHAR2 (100 BYTE),
   DEALER_NAME      VARCHAR2 (240 BYTE),
   AREA_NAME        VARCHAR2 (240 BYTE),
   REGION_NO        VARCHAR2 (240 BYTE),
   EXECUTIVE_NAME   VARCHAR2 (240 BYTE),
   AM_NAME          VARCHAR2 (240 BYTE),
   BASE_TARGET      NUMBER,
   PERIOD_NAME      VARCHAR2 (100 BYTE),
   MTD              NUMBER,
   LMTD             NUMBER,
   ACHIEVEMENT      NUMBER,
   CONSTRAINT CER_TARGET_PK PRIMARY KEY (SL_NO)
);

CREATE OR REPLACE SYNONYM appsro.XXDBL_CER_MONTHLY_TARGET FOR xxdbl.XXDBL_CER_MONTHLY_TARGET;

CREATE OR REPLACE SYNONYM apps.XXDBL_CER_MONTHLY_TARGET FOR xxdbl.XXDBL_CER_MONTHLY_TARGET;

DROP TABLE XXDBL.XXDBL_CER_MONTHLY_TARGET;


SELECT
*
FROM
XXDBL.XXDBL_CER_MONTHLY_TARGET;