/* Formatted on 6/21/2021 2:10:23 PM (QP5 v5.287) */
  SELECT MSI.SEGMENT1 ITEM_CODE,
         MIC.SEGMENT2 ITEM_CATEGORY,
         MIC.SEGMENT3 ITM_TYPE,
         MSI.DESCRIPTION ITEM_DESCRIPTION,
         ORG.ORGANIZATION_CODE,
         ORG.ORGANIZATION_NAME,
         MMT.SUBINVENTORY_CODE,
         MMT.INVENTORY_ITEM_ID,
         MMT.ORGANIZATION_ID,
         MSI.PRIMARY_UOM_CODE,
         MSI.SECONDARY_UOM_CODE,
         --PRIMARY_QUANTITY ON_HAND,
         SUM (PRIMARY_QUANTITY) ON_HAND,
         MMT.TRANSACTION_DATE
    FROM MTL_MATERIAL_TRANSACTIONS MMT,
         ORG_ORGANIZATION_DEFINITIONS ORG,
         MTL_SYSTEM_ITEMS_B MSI,
         MTL_ITEM_CATEGORIES_V MIC,
         MTL_SECONDARY_INVENTORIES SI,
         XXDBL_COMPANY_LE_MAPPING_V OU,
         HR_OPERATING_UNITS HOU
   WHERE     1 = 1
         AND MMT.ORGANIZATION_ID = ORG.ORGANIZATION_ID
         AND HOU.ORGANIZATION_ID = ORG.OPERATING_UNIT
         AND ORG.OPERATING_UNIT = OU.ORG_ID
         AND MMT.ORGANIZATION_ID = MSI.ORGANIZATION_ID
         AND MMT.INVENTORY_ITEM_ID = MSI.INVENTORY_ITEM_ID
         AND MMT.ORGANIZATION_ID = MIC.ORGANIZATION_ID
         AND MMT.INVENTORY_ITEM_ID = MIC.INVENTORY_ITEM_ID
         AND MIC.CATEGORY_SET_ID = 1
         AND MSI.SEGMENT1 = 'DYES0000100001000037'
         AND SI.DISABLE_DATE IS NULL
GROUP BY MMT.INVENTORY_ITEM_ID,
         MMT.ORGANIZATION_ID,
         ORG.ORGANIZATION_CODE,
         ORG.ORGANIZATION_NAME,
         MMT.SUBINVENTORY_CODE,
         MSI.PRIMARY_UOM_CODE,
         MSI.SECONDARY_UOM_CODE,
         MSI.SEGMENT1,
         MSI.DESCRIPTION,
         MIC.SEGMENT2,
         MIC.SEGMENT3,
         MMT.TRANSACTION_DATE
  HAVING SUM (PRIMARY_QUANTITY) <> 0;