SELECT OOD.OPERATING_UNIT,
         OOD.ORGANIZATION_NAME,
         OOD.ORGANIZATION_CODE,
         OOD.ORGANIZATION_ID,
         OHQD.SUBINVENTORY_CODE,
         OHQD.LOT_NUMBER,
         MSIB.SEGMENT1 ITEM_CODE,
         MSIB.DESCRIPTION,
         CAT.SEGMENT2 MAJOR_CATEGORY,
         CAT.SEGMENT3 MINOR_CATEGORY,
         OHQD.INVENTORY_ITEM_ID,
         SUM (OHQD.PRIMARY_TRANSACTION_QUANTITY) AS ONHAND_QTY,
         OHQD.TRANSACTION_UOM_CODE UOM_CODE
    FROM APPS.MTL_ONHAND_QUANTITIES_DETAIL OHQD,
         APPS.ORG_ORGANIZATION_DEFINITIONS OOD,
         APPS.MTL_SYSTEM_ITEMS_B MSIB,
         APPS.MTL_ITEM_CATEGORIES_V CAT
   WHERE     1 = 1
         AND MSIB.ORGANIZATION_ID = OOD.ORGANIZATION_ID
         AND OHQD.ORGANIZATION_ID = OOD.ORGANIZATION_ID
         AND OHQD.INVENTORY_ITEM_ID = MSIB.INVENTORY_ITEM_ID
         AND MSIB.INVENTORY_ITEM_ID = CAT.INVENTORY_ITEM_ID
         AND MSIB.ORGANIZATION_ID = CAT.ORGANIZATION_ID
         AND CAT.CATEGORY_SET_ID = 1
GROUP BY OOD.OPERATING_UNIT,
         MSIB.SEGMENT1,
         MSIB.DESCRIPTION,
         OHQD.INVENTORY_ITEM_ID,
         OHQD.LOT_NUMBER,
         OHQD.SUBINVENTORY_CODE,
         OHQD.TRANSACTION_UOM_CODE,
         OOD.ORGANIZATION_ID,
         OOD.ORGANIZATION_CODE,
         CAT.SEGMENT2,
         CAT.SEGMENT3,
         OOD.ORGANIZATION_NAME
ORDER BY ORGANIZATION_CODE;