/* Formatted on 6/27/2020 10:04:28 AM (QP5 v5.287) */
CREATE TABLE apps.ra_interface_table_stg
(
   SL_NO                  NUMBER ,
   ORGANIZATION_CODE      VARCHAR2 (10 BYTE),
   TRX_TYPE               VARCHAR2 (500 BYTE),
   CUST_TRX_TYPE_ID       NUMBER (35),
   BATCH_SOURCE_NAME      NUMBER (35),
   LINE_NUMBER            NUMBER (35),
   TRX_DATE               DATE,
   GL_DATE                DATE,
   CURRENCY_CODE          VARCHAR2 (3 BYTE),
   CUSTOMER_NUMBER        VARCHAR2 (10 BYTE),
   SALES_ORDER            NUMBER (35),
   ITEM_CODE              VARCHAR2 (50 BYTE),
   QUANTITY               NUMBER (35),
   UNIT_SELLING_PRICE     NUMBER (35),
   FLAG                   VARCHAR2 (3 BYTE),
   OPERATING_UNIT         NUMBER (35),
   ORGANIZATION_ID        NUMBER (35),
   SET_OF_BOOKS           NUMBER (35),
   LEGAL_ENTITY_ID        NUMBER (35),
   ITEM_ID                NUMBER (35),
   UOM_CODE               VARCHAR2 (10 BYTE),
   AMOUNT                 NUMBER (35),
   CUSTOMER_ID            NUMBER (35),
   BILL_TO_SITE_ID        NUMBER (35),
   SHIP_TO_SITE_ID        NUMBER (35),
   TERM_ID                NUMBER (35),
   ORD_HEADER_ID          NUMBER (35),
   FREIGHT_TERMS_CODE     VARCHAR2 (50 BYTE),
   FREIGHT_CARRIER_CODE   VARCHAR2 (50 BYTE),
   SALESREP_ID            NUMBER (35),
   ORD_LINE_ID            NUMBER (35),
   ORDER_DATE             DATE,
   ORD_LINE_NUMBER        NUMBER (35),
   UNIT_LIST_PRICE        FLOAT,
   ACTUAL_SHIP_DATE       DATE,
   TERRITORY_ID           NUMBER (35),
   T_SEGMENT1             VARCHAR2 (500 BYTE),
   T_SEGMENT2             VARCHAR2 (500 BYTE),
   T_SEGMENT3             VARCHAR2 (500 BYTE),
   T_SEGMENT4             VARCHAR2 (500 BYTE)
);

SELECT --SL_NO,
       --       ORGANIZATION_CODE,
       --       BATCH_SOURCE_NAME,
       --       LINE_NUMBER,
       --       TRX_DATE,
       --       GL_DATE,
       --       CURRENCY_CODE,
       --       CUSTOMER_NUMBER,
       --       SALES_ORDER,
       --       ITEM_CODE,
       --       QUANTITY,
       --       UNIT_SELLING_PRICE,
       --       FLAG,
       --       OPERATING_UNIT,
       --       ORGANIZATION_ID,
       --       SET_OF_BOOKS,
       --       LEGAL_ENTITY_ID,
       --       --
       --       ITEM_ID,
       --       UOM_CODE,
       --       AMOUNT,
       --       --
       --       CUSTOMER_ID,
       --       BILL_TO_SITE_ID,
       --       SHIP_TO_SITE_ID,
       --       TERM_ID,
       --       ---
       --       ORD_HEADER_ID,
       --       TRANSACTIONAL_CURR_CODE,
       --       FREIGHT_TERMS_CODE,
       --       FREIGHT_CARRIER_CODE,
       --       SALESREP_ID,
       --       ORD_LINE_ID,
       --       ORDERED_QUANTITY
       STG.*
  FROM apps.ra_interface_table_stg STG;


DROP TABLE APPS.ra_interface_table_stg CASCADE CONSTRAINTS;