CREATE TABLE w_tblProduction(
    PId NUMBER IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
    PDate DATE NULL,
    [PUnit] [varchar](10) NULL,
    [PShift] [varchar](15) NULL,
    [PCount] [decimal](18, 2) NULL,
    [PYarnLot] [varchar](50) NULL,
    [PProcessType] [varchar](50) NULL,
    [PCountDes] [varchar](100) NULL,
    [PTpi] [decimal](18, 2) NULL,
    [PWorkH] [decimal](18, 2) NULL,
    [TargetEffi] [decimal](18, 0) NULL,
    [PSpeed] [int] NULL,
    [PMachineNo] [decimal](18, 2) NULL,
    [PProd] [decimal](18, 2) NULL,
    [PEffi] [decimal](18, 2) NULL,
    [PType] [varchar](100) NULL,
    [PRemarks] [varchar](200) NULL,
    [PCreatedBy] [varchar](50) NULL,
    [PUpdatedBy] [varchar](50) NULL,
    [PDeletedBy] [varchar](50) NULL,
 CONSTRAINT [PK_tblProduction] PRIMARY KEY CLUSTERED