/* Formatted on 3/2/2020 7:26:28 PM (QP5 v5.287) */
CREATE TABLE XXDBL_CUST_SUP_COMB
(
   cust_sup_id     NUMBER GENERATED ALWAYS AS IDENTITY,
   customer_no     NUMBER,
   customer_name   VARCHAR2 (200),
   supplier_no     NUMBER,
   supplier_name   VARCHAR2 (200),
   CONSTRAINT cust_sup_PK PRIMARY KEY (cust_sup_id)
);

ALTER TABLE APPS.XXDBL_CUST_SUP_COMB
 DROP PRIMARY KEY CASCADE;

DROP TABLE APPS.XXDBL_CUST_SUP_COMB CASCADE CONSTRAINTS;

CREATE TABLE APPS.XXDBL_CUST_SUP_COMB
(
  CUST_SUP_ID    NUMBER Generated as Identity ( START WITH 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 NOORDER NOKEEP) NOT NULL,
  CUSTOMER_NO    NUMBER,
  CUSTOMER_NAME  VARCHAR2(200 BYTE),
  SUPPLIER_NO    NUMBER,
  SUPPLIER_NAME  VARCHAR2(200 BYTE)
)
TABLESPACE APPS_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX APPS.CUST_SUP_PK ON APPS.XXDBL_CUST_SUP_COMB
(CUST_SUP_ID)
LOGGING
TABLESPACE APPS_TS_TX_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE APPS.XXDBL_CUST_SUP_COMB ADD (
  CONSTRAINT CUST_SUP_PK
  PRIMARY KEY
  (CUST_SUP_ID)
  USING INDEX APPS.CUST_SUP_PK
  ENABLE VALIDATE);
