/* Formatted on 10/6/2021 5:51:34 PM (QP5 v5.365) */
SELECT DISTINCT
       CATEGORY_CONCAT_SEGS     AS DISPLAY_VALUE,
       CATEGORY_CONCAT_SEGS     AS RETURN_VALUE
  FROM APPS.MTL_ITEM_CATEGORIES_V
 WHERE ORGANIZATION_ID = 152 AND CATEGORY_SET_ID = 1100000061;


SELECT DISTINCT MC.SEGMENT2 AS DISPLAY_VALUE, MC.SEGMENT2 AS RETURN_VALUE
  FROM INV.MTL_CATEGORIES_B MC, APPS.MTL_CATEGORY_SETS MCS
 WHERE     1 = 1
       AND MC.STRUCTURE_ID = MCS.STRUCTURE_ID
       AND MCS.CATEGORY_SET_ID = 1;


SELECT DISTINCT MC.SEGMENT3 AS DISPLAY_VALUE, MC.SEGMENT3 AS RETURN_VALUE
  FROM INV.MTL_CATEGORIES_B MC, APPS.MTL_CATEGORY_SETS MCS
 WHERE     1 = 1
       AND MC.STRUCTURE_ID = MCS.STRUCTURE_ID
       AND MCS.CATEGORY_SET_ID = 1;



SELECT MC.SEGMENT2 AS DISPLAY_VALUE, MC.SEGMENT2 AS RETURN_VALUE
  FROM INV.MTL_CATEGORIES_B MC
 WHERE MC.SEGMENT2 IS NOT NULL;


SELECT MC.SEGMENT3 AS DISPLAY_VALUE, MC.SEGMENT3 AS RETURN_VALUE
  FROM INV.MTL_CATEGORIES_B MC
 WHERE MC.SEGMENT2 IS NOT NULL;

SELECT OOD.ORGANIZATION_CODE     AS DISPLAY_VALUE,
       OOD.ORGANIZATION_ID       AS RETURN_VALUE
  FROM APPS.ORG_ORGANIZATION_DEFINITIONS OOD, INV.MTL_PARAMETERS MP
 WHERE     MP.ORGANIZATION_ID = OOD.ORGANIZATION_ID
       AND PROCESS_ENABLED_FLAG = 'Y';

SELECT DISTINCT
       OU.LEGAL_ENTITY_NAME     AS DISPLAY_VALUE,
       OU.LEGAL_ENTITY_ID       AS RETURN_VALUE
  FROM APPS.XXDBL_COMPANY_LE_MAPPING_V    OU,
       APPS.ORG_ORGANIZATION_DEFINITIONS  OOD,
       INV.MTL_PARAMETERS                 MP
 WHERE     MP.ORGANIZATION_ID = OOD.ORGANIZATION_ID
       AND OOD.OPERATING_UNIT = OU.ORG_ID
       AND PROCESS_ENABLED_FLAG = 'Y';

SELECT DISTINCT
       OU.LEGAL_ENTITY_NAME     AS DISPLAY_VALUE,
       OU.LEGAL_ENTITY_ID       AS RETURN_VALUE
  FROM APPS.XXDBL_COMPANY_LE_MAPPING_V OU;

SELECT MSI.SEGMENT1 AS DISPLAY_VALUE, MSI.INVENTORY_ITEM_ID AS RETURN_VALUE
  FROM APPS.MTL_SYSTEM_ITEMS_B            MSI,
       APPS.ORG_ORGANIZATION_DEFINITIONS  OOD,
       APPS.MTL_ITEM_CATEGORIES_V         CAT
 WHERE     1 = 1
       AND MSI.ORGANIZATION_ID = OOD.ORGANIZATION_ID
       AND MSI.INVENTORY_ITEM_ID = CAT.INVENTORY_ITEM_ID
       AND MSI.ORGANIZATION_ID = CAT.ORGANIZATION_ID
       AND (   :P2_LEGAL_ENTITY IS NULL
            OR (OOD.LEGAL_ENTITY = :P2_LEGAL_ENTITY))
       AND ( :P2_ORG_ID IS NULL OR (OOD.ORGANIZATION_ID = :P2_ORG_ID))
       AND ( :P2_MJR_CAT IS NULL OR (CAT.SEGMENT2 = :P2_MJR_CAT))
       AND ( :P2_MNR_CAT IS NULL OR (CAT.SEGMENT3 = :P2_MNR_CAT))
       AND ( :P2_ITEM_CODE IS NULL OR (MSI.SEGMENT1 = :P2_ITEM_CODE));


SELECT OOD.ORGANIZATION_CODE     AS DISPLAY_VALUE,
       OOD.ORGANIZATION_ID       AS RETURN_VALUE
  FROM APPS.ORG_ORGANIZATION_DEFINITIONS  OOD,
       INV.MTL_PARAMETERS                 MP,
       APPS.XXDBL_COMPANY_LE_MAPPING_V    OU
 WHERE     MP.ORGANIZATION_ID = OOD.ORGANIZATION_ID
       AND PROCESS_ENABLED_FLAG = 'Y'
       AND OOD.OPERATING_UNIT = OU.ORG_ID
       AND OOD.LEGAL_ENTITY = :P2_LEGAL_ENTITY;