/* Formatted on 1/27/2022 10:08:26 AM (QP5 v5.374) */
SELECT PHA.SEGMENT1     AS DISPLAY_VALUE,
       PHA.SEGMENT1     AS RETURN_VALUE,
       CREATION_DATE
  FROM PO.PO_HEADERS_ALL PHA
 WHERE     PHA.ORG_ID = :P3_UNIT_NAME
       AND NOT EXISTS
               (SELECT 1
                  FROM XX_APEX.XXAPEX_PO_GRN_HDR PGH
                 WHERE PGH.PO_NUMBER = PHA.SEGMENT1);


SELECT PHA.SEGMENT1                     AS DISPLAY_VALUE,
       PHA.SEGMENT1                     AS RETURN_VALUE,
       PHA.CREATION_DATE,
       TO_CHAR (LC.LC_NUMBER)           LC_NO,
       TO_CHAR (LC.LC_OPENING_DATE)     LC_OPENING_DATE,
       LC.PROFORMA_INVOICE_NUM          PI_NUMBER
  FROM APPS.PO_HEADERS_ALL PHA, XXDBL.XX_LC_DETAILS LC
 WHERE     1 = 1
       AND PHA.PO_HEADER_ID = LC.PO_HEADER_ID
       AND PHA.ORG_ID = :P3_UNIT_NAME
       AND PHA.SEGMENT1 = LC.PO_NUMBER
       AND NOT EXISTS
               (SELECT 1
                  FROM XX_APEX.XXAPEX_PO_GRN_HDR PGH
                 WHERE PGH.PO_NUMBER = PHA.SEGMENT1);

SELECT LC.LC_NUMBER
  FROM XXDBL.XX_LC_DETAILS LC