select
*
from
XXDBL.xxdbl_master_lc_headers;



ALTER TABLE XXDBL.xxdbl_master_lc_headers
   ADD ( CUST_ACCEPT_DATE DATE);
   
DROP PUBLIC SYNONYM XXDBL_MASTER_LC_HEADERS;


CREATE OR REPLACE PUBLIC SYNONYM XXDBL_MASTER_LC_HEADERS FOR XXDBL.XXDBL_MASTER_LC_HEADERS;