SELECT MMTT.TRANSACTION_SOURCE_ID,
       CASE
          WHEN MMTT.TRANSACTION_SOURCE_TYPE_ID = 1
          THEN
             (SELECT 'RSH_NUMBER: ' || RCV.SHIPMENT_NUM
                FROM RCV_SHIPMENT_HEADERS RCV, RCV_TRANSACTIONS RCVT
               WHERE RCV.SHIPMENT_HEADER_ID = RCVT.SHIPMENT_HEADER_ID
                     AND RCVT.TRANSACTION_ID = MMTT.TRANSACTION_SOURCE_ID)
          WHEN MMTT.TRANSACTION_SOURCE_TYPE_ID = 2
          THEN
             (SELECT 'SO_NUMBER: ' || SEGMENT1
                FROM MTL_SALES_ORDERS
               WHERE SALES_ORDER_ID = MMTT.TRANSACTION_SOURCE_ID)
          WHEN MMTT.TRANSACTION_SOURCE_TYPE_ID = 4
          THEN
             (SELECT 'MO_NUMBER: ' || REQUEST_NUMBER
                FROM MTL_TXN_REQUEST_HEADERS
               WHERE REQUEST_NUMBER = TO_CHAR (MMTT.TRANSACTION_SOURCE_ID))
          WHEN MMTT.TRANSACTION_SOURCE_TYPE_ID = 5
          THEN
             (SELECT 'WIP_NUMBER: ' || WIP_ENTITY_NAME
                FROM WIP_ENTITIES
               WHERE WIP_ENTITY_ID = MMTT.TRANSACTION_SOURCE_ID)
          WHEN MMTT.TRANSACTION_SOURCE_TYPE_ID = 7
          THEN
             (SELECT 'INT_REQ_NUMBER: ' || RCV.SHIPMENT_NUM
                FROM RCV_SHIPMENT_HEADERS RCV, RCV_TRANSACTIONS RCVT
               WHERE RCV.SHIPMENT_HEADER_ID = RCVT.SHIPMENT_HEADER_ID
                     AND RCVT.TRANSACTION_ID = MMTT.TRANSACTION_SOURCE_ID)
          WHEN MMTT.TRANSACTION_SOURCE_TYPE_ID = 8
          THEN
             (SELECT 'INT_SO_NUMBER: ' || SEGMENT1
                FROM MTL_SALES_ORDERS
               WHERE SALES_ORDER_ID = MMTT.TRANSACTION_SOURCE_ID)
          WHEN MMTT.TRANSACTION_SOURCE_TYPE_ID = 10
          THEN
             (SELECT 'PHY_NAME: ' || PHYSICAL_INVENTORY_NAME
                FROM MTL_PHYSICAL_INVENTORIES
               WHERE PHYSICAL_INVENTORY_ID = MMTT.TRANSACTION_SOURCE_ID)
          WHEN MMTT.TRANSACTION_SOURCE_TYPE_ID = 13
          THEN
             (SELECT 'WIP_NUMBER: ' || WIP_ENTITY_NAME
                FROM WIP_ENTITIES
               WHERE WIP_ENTITY_ID = MMTT.TRANSACTION_SOURCE_ID)
          ELSE
             'NULL'
       END
          SRC_NUMBER
  FROM MTL_MATERIAL_TRANSACTIONS_TEMP MMTT;