SELECT
*
FROM
MTL_INTERORG_PARAMETERS 

SELECT
*
FROM
ORG_ORGANIZATION_DEFINITIONS

SELECT
*
FROM
INV_ORGANIZATION_NAME_V
--------------------------------------------------------------------------------

SELECT HOU.ORGANIZATION_ID ORGANIZATION_ID,
          HOU.BUSINESS_GROUP_ID,
          MP.ORGANIZATION_CODE ORGANIZATION_CODE,
          HOU.NAME ORGANIZATION_NAME,
          HOU.DATE_FROM USER_DEFINITION_ENABLE_DATE,
          HOU.DATE_TO DISABLE_DATE
          --,HOU.*
          ,HOI1.*
     FROM HR_ORGANIZATION_UNITS HOU,
          HR_ORGANIZATION_INFORMATION HOI1,
          MTL_PARAMETERS MP
    WHERE     HOU.ORGANIZATION_ID = HOI1.ORGANIZATION_ID
          AND HOI1.ORG_INFORMATION1 = 'INV'
          AND HOI1.ORG_INFORMATION2 = 'Y'
          AND HOI1.ORG_INFORMATION_CONTEXT = 'CLASS'
          AND HOI1.ORGANIZATION_ID = MP.ORGANIZATION_ID;
          
          
--------------------------------------------------------------------------------

SELECT
*
FROM
INVBV_INVENTORY_ORGANIZATIONS