/* Formatted on 10/15/2020 11:14:56 AM (QP5 v5.287) */
---------------------------------DBL MOVE Order---------------------------------

  SELECT 
         OOD.OPERATING_UNIT               ORG_ID,
         HOU.NAME                         UNIT_NAME,
         OOD.ORGANIZATION_CODE            ORG_CODE,
         HOU.DEFAULT_LEGAL_CONTEXT_ID     LEGAL_ENTITY,
         OU.LEGAL_ENTITY_NAME,   
         TRX.TRANSACTION_TYPE_NAME,
         TRX.MOVE_ORDER_TYPE_NAME,
         H.REQUEST_NUMBER MOVE_ORDER,
         --H.ORGANIZATION_ID,
         --H.FROM_SUBINVENTORY_CODE,
         --H.TO_SUBINVENTORY_CODE,
         TRX.HEADER_STATUS_NAME MO_STATUS,
         TRX.STATUS_DATE,
         --XX_COM_PKG.GET_USER_NAME(H.CREATED_BY) ||'-'||XX_COM_PKG.GET_EMP_NAME_FROM_USER_ID (H.CREATED_BY) MO_CREATED_BY,
         NVL(PAPF.EMPLOYEE_NUMBER,PAPF.NPW_NUMBER) ||'-'|| (PAPF.FIRST_NAME || ' ' || PAPF.MIDDLE_NAMES || ' ' || PAPF.LAST_NAME)
          AS MO_ACTIONED_BY,
         MOAH.APPROVER_ACTION APPROVER_ACTION_NAME,
         MOAH.CREATION_DATE ACTION_DATE
    --,H.*
    --,TRX.*
    --,MOAH.*
    FROM APPS.MTL_TXN_REQUEST_HEADERS H,
         APPS.MTL_TXN_REQUEST_HEADERS_V TRX,
         XXDBL_MOV_ORD_APPR_HIST MOAH,
         HR_OPERATING_UNITS            HOU,
         ORG_ORGANIZATION_DEFINITIONS  OOD,
         XXDBL_COMPANY_LE_MAPPING_V    OU,
         APPS.PER_ALL_PEOPLE_F PAPF
   WHERE     1 = 1
         AND H.REQUEST_NUMBER = TRX.REQUEST_NUMBER
         --AND TRX.HEADER_STATUS_NAME = 'Approved'
         --AND H.REQUEST_NUMBER IN ( '712054')
         AND ( :P_MOVE_ORD_NO IS NULL OR (H.REQUEST_NUMBER = :P_MOVE_ORD_NO))
         AND H.HEADER_ID = MOAH.MO_HEADER_ID(+)
         AND MOAH.FUNCMODE='RUN'
         AND MOAH.APPROVER_EMP_ID=PAPF.PERSON_ID(+)
         AND TRUNC (SYSDATE) BETWEEN TRUNC (PAPF.EFFECTIVE_START_DATE) AND TRUNC (PAPF.EFFECTIVE_END_DATE)
         AND H.ORGANIZATION_ID = OOD.ORGANIZATION_ID
         AND HOU.ORGANIZATION_ID = OOD.OPERATING_UNIT
         AND (   :P_OPERATING_UNIT IS NULL OR (OOD.OPERATING_UNIT = :P_OPERATING_UNIT))
         AND (   :P_OU_NAME IS NULL OR (HOU.NAME = :P_OU_NAME))
         AND (   :P_ORGANIZATION_CODE IS NULL OR (OOD.ORGANIZATION_CODE = :P_ORGANIZATION_CODE))
         AND (   :P_LEGAL_ENTITY IS NULL OR (HOU.DEFAULT_LEGAL_CONTEXT_ID = :P_LEGAL_ENTITY))
         AND OOD.OPERATING_UNIT = OU.ORG_ID
ORDER BY H.REQUEST_NUMBER,MOAH.APPROVAL_SEQ_NUM;


--------------------------------------------------------------------------------

SELECT
*
FROM
XXDBL_MOV_ORD_APPR_HIST MOAH
WHERE ( :P_MOVE_ORD_NO IS NULL OR (MOAH.MO_HEADER_ID = :P_MOVE_ORD_NO));



---------------------------------DBL MOVE Order Approval------------------------

  SELECT TRX.TRANSACTION_TYPE_NAME,
         TRX.MOVE_ORDER_TYPE_NAME,
         H.REQUEST_NUMBER          MOVE_ORDER,
         TRX.HEADER_STATUS_NAME    MO_STATUS,
         TRX.STATUS_DATE,
            NVL (PAPF.EMPLOYEE_NUMBER, PAPF.NPW_NUMBER)
         || '-'
         || (   PAPF.FIRST_NAME
             || ' '
             || PAPF.MIDDLE_NAMES
             || ' '
             || PAPF.LAST_NAME)    AS MO_ACTIONED_BY,
         MOAH.APPROVER_ACTION      APPROVER_ACTION_NAME,
         MOAH.CREATION_DATE        ACTION_DATE
    --,H.*
    --,TRX.*
    --,MOAH.*
    FROM APPS.MTL_TXN_REQUEST_HEADERS  H,
         APPS.MTL_TXN_REQUEST_HEADERS_V TRX,
         XXDBL_MOV_ORD_APPR_HIST       MOAH,
         APPS.PER_ALL_PEOPLE_F         PAPF
   WHERE     1 = 1
         AND H.REQUEST_NUMBER = TRX.REQUEST_NUMBER
         --AND TRX.HEADER_STATUS_NAME = 'Approved'
         AND H.REQUEST_NUMBER IN ( '829302')
         AND H.HEADER_ID = MOAH.MO_HEADER_ID(+)
         AND MOAH.FUNCMODE = 'RUN'
         AND MOAH.APPROVER_EMP_ID = PAPF.PERSON_ID(+)
         AND TRUNC (SYSDATE) BETWEEN TRUNC (PAPF.EFFECTIVE_START_DATE)
                                 AND TRUNC (PAPF.EFFECTIVE_END_DATE)
ORDER BY H.REQUEST_NUMBER, MOAH.APPROVAL_SEQ_NUM;