/* Formatted on 10/5/2020 9:29:27 AM (QP5 v5.354) */
---------------------------------DBL MOVE Order----------------------------------------------

  SELECT OOD.OPERATING_UNIT               ORG_ID,
         HOU.NAME                         OPERATING_UNIT_NAME,
         OOD.ORGANIZATION_CODE            WAREHOUSE_ORG_CODE,
         HOU.DEFAULT_LEGAL_CONTEXT_ID     LEGAL_ENTITY,
         OU.LEGAL_ENTITY_NAME,
         TRX.TRANSACTION_TYPE_NAME,
         TRX.MOVE_ORDER_TYPE_NAME,
         --H.HEADER_ID MOV_ORD_HDR_ID,
         H.REQUEST_NUMBER                 MOVE_ORDER,
         H.CREATION_DATE,
         H.ORGANIZATION_ID,
         H.FROM_SUBINVENTORY_CODE,
         H.TO_SUBINVENTORY_CODE,
         H.ATTRIBUTE1                     VEHICLE_NO,
         H.ATTRIBUTE2                     PRODUCT_TYPE,
         L.INVENTORY_ITEM_ID,
         MSI.DESCRIPTION                  ITEM_NAME,
         MIC.SEGMENT2                     ITEM_CATEGORY,
         MIC.SEGMENT3                     ITEM_TYPE,
         L.UOM_CODE,
         L.QUANTITY,
         L.QUANTITY_DELIVERED,
         L.REASON_ID,
         TRX.HEADER_STATUS_NAME,
         TRX.STATUS_DATE
    --,H.*
    --,L.*
    --,TRX.*
    --,MMT.*
    --,MTT.*
    --,MSI.*
    --,MIC.*
    FROM APPS.MTL_TXN_REQUEST_HEADERS  H,
         APPS.MTL_TXN_REQUEST_LINES    L,
         APPS.MTL_TXN_REQUEST_HEADERS_V TRX,
         --,APPS.MTL_MATERIAL_TRANSACTIONS MMT
         --,INV.MTL_TRANSACTION_TYPES MTT
         HR_OPERATING_UNITS            HOU,
         ORG_ORGANIZATION_DEFINITIONS  OOD,
         XXDBL_COMPANY_LE_MAPPING_V    OU,
         APPS.MTL_SYSTEM_ITEMS_B       MSI,
         APPS.MTL_ITEM_CATEGORIES_V    MIC
   WHERE     1 = 1
         AND MSI.INVENTORY_ITEM_ID = L.INVENTORY_ITEM_ID
         AND MSI.ORGANIZATION_ID = L.ORGANIZATION_ID
         AND MIC.CATEGORY_SET_ID = 1
         AND MSI.INVENTORY_ITEM_ID = MIC.INVENTORY_ITEM_ID
         AND MSI.ORGANIZATION_ID = MIC.ORGANIZATION_ID
         --AND MTT.TRANSACTION_TYPE_ID=MMT.TRANSACTION_TYPE_ID
         --AND MTT.TRANSACTION_SOURCE_TYPE_ID = MMT.TRANSACTION_SOURCE_TYPE_ID
         --AND H.HEADER_ID = MMT.TRANSACTION_SOURCE_ID
         --AND L.LINE_ID=MMT.MOVE_ORDER_LINE_ID
         ----AND H.REQUEST_NUMBER=MMT.TRANSACTION_SOURCE_ID
         --AND TO_CHAR (MMT.TRANSACTION_DATE, 'MON-RR') = 'APR-18'
         --AND TO_CHAR (MMT.TRANSACTION_DATE, 'RRRR') = '2018'
         --AND TO_CHAR (MMT.TRANSACTION_DATE, 'DD-MON-RR') = '27-MAY-17'
         AND H.REQUEST_NUMBER = TRX.REQUEST_NUMBER
         AND H.HEADER_ID = L.HEADER_ID
         AND H.ORGANIZATION_ID = L.ORGANIZATION_ID
         --AND TRX.HEADER_STATUS_NAME = 'Approved'
         --and TO_CHAR(H.DATE_REQUIRED,'RRRR')='2018'
         --and to_char(H.DATE_REQUIRED,'DD-MON-RR')='05-MAY-18'
         --and h.FROM_SUBINVENTORY_CODE='AKC-GEN ST'
         --AND H.ORGANIZATION_ID=193
         --AND L.INVENTORY_ITEM_ID='511077'
         --AND TRX.MOVE_ORDER_TYPE_NAME='Requisition'
         --AND TRX.TRANSACTION_TYPE_NAME='Move Order Issue'
         --AND H.REQUEST_NUMBER = '1144849'                             --9642353
         --AND L.LINE_ID='31251259'
         --AND H.HEADER_ID='15129101'
         AND ( :P_MOVE_ORD_NO IS NULL OR (H.REQUEST_NUMBER = :P_MOVE_ORD_NO))
         AND (   :P_OPERATING_UNIT IS NULL OR (OOD.OPERATING_UNIT = :P_OPERATING_UNIT))
         AND (   :P_OU_NAME IS NULL OR (HOU.NAME = :P_OU_NAME))
         AND (   :P_ORGANIZATION_CODE IS NULL OR (OOD.ORGANIZATION_CODE = :P_ORGANIZATION_CODE))
         AND (   :P_LEGAL_ENTITY IS NULL OR (HOU.DEFAULT_LEGAL_CONTEXT_ID = :P_LEGAL_ENTITY))
         AND MSI.ORGANIZATION_ID = OOD.ORGANIZATION_ID
         AND HOU.ORGANIZATION_ID = OOD.OPERATING_UNIT
         AND OOD.OPERATING_UNIT = OU.ORG_ID
ORDER BY H.REQUEST_NUMBER DESC