/* Formatted on 4/28/2020 12:51:25 PM (QP5 v5.287) */
SELECT DISTINCT CAT.ROW_WID,
       PROD_NAME,
       PROD.INTEGRATION_ID ITEM_ID,
       PROD.PROD_CAT1_WID,
       CAT.INTEGRATION_ID CATEGORY_ID,
       CAT.TOP_LVL_PRODCAT_NAME,
       CAT.L8ANC_PRODCAT_NAME,
       CAT.L7ANC_PRODCAT_NAME,
       CAT.L6ANC_PRODCAT_NAME
       --,PROD.*
  FROM W_PROD_CAT_DH CAT, W_PRODUCT_D PROD
 WHERE     CAT.ROW_WID = PROD.PROD_CAT1_WID
       --AND TOP_LVL_PRODCAT_NAME='IT'
       AND PROD.STATUS_CODE='Active'
       --AND PROD.INTEGRATION_ID='12491'
       /*AND PROD.INTEGRATION_ID IN ()*/