/* Formatted on 10/19/2021 5:31:58 PM (QP5 v5.365) */
  SELECT INTERFACE_TRANSACTION_ID,
         GROUP_ID,
         LAST_UPDATE_DATE,
         LAST_UPDATED_BY,
         CREATION_DATE,
         CREATED_BY,
         LAST_UPDATE_LOGIN,
         TRANSACTION_TYPE,
         TRANSACTION_DATE,
         PROCESSING_STATUS_CODE,
         PROCESSING_MODE_CODE,
         TRANSACTION_STATUS_CODE,
         INTERFACE_SOURCE_CODE,
         AUTO_TRANSACT_CODE,
         RECEIPT_SOURCE_CODE,
         TO_ORGANIZATION_ID,
         SOURCE_DOCUMENT_CODE,
         PO_HEADER_ID,
         PO_LINE_ID,
         HEADER_INTERFACE_ID,
         DOCUMENT_NUM,
         DOCUMENT_LINE_NUM,
         VALIDATION_FLAG,
         AMOUNT
    --,RTI.*
    FROM RCV_TRANSACTIONS_INTERFACE RTI
   WHERE 1 = 1
ORDER BY CREATION_DATE DESC;


  SELECT HEADER_INTERFACE_ID,
         GROUP_ID,
         PROCESSING_STATUS_CODE,
         RECEIPT_SOURCE_CODE,
         TRANSACTION_TYPE,
         AUTO_TRANSACT_CODE,
         LAST_UPDATE_DATE,
         LAST_UPDATED_BY,
         LAST_UPDATE_LOGIN,
         CREATION_DATE,
         CREATED_BY,
         VENDOR_ID,
         VENDOR_SITE_ID,
         SHIP_TO_ORGANIZATION_ID,
         EXPECTED_RECEIPT_DATE,
         EMPLOYEE_ID,
         VALIDATION_FLAG,
         ORG_ID
    FROM RCV_HEADERS_INTERFACE RHI
   WHERE 1 = 1
ORDER BY CREATION_DATE DESC;