/* Formatted on 6/14/2021 2:15:40 PM (QP5 v5.287) */
  SELECT *
    FROM xxdbl.xxdbl_cer_ar_intrf_stg
--where flag is null
ORDER BY SL_NO DESC;

--truncate table xxdbl.xxdbl_cer_ra_interface_stg;


--> Interface Tables:

SELECT *
  FROM RA_INTERFACE_LINES_ALL
 WHERE TRUNC (CREATION_DATE) = TRUNC (SYSDATE)
 ;

--DELETE RA_INTERFACE_LINES_ALL where TRUNC(CREATION_DATE) = TRUNC(SYSDATE);
--COMMIT;

SELECT *
  FROM RA_INTERFACE_DISTRIBUTIONS_ALL
 WHERE TRUNC (CREATION_DATE) = TRUNC (SYSDATE);
 
 
 SELECT
 *
 FROM
 RA_INTERFACE_SALESCREDITS_ALL

--DELETE RA_INTERFACE_DISTRIBUTIONS_ALL where TRUNC(CREATION_DATE) = TRUNC(SYSDATE);
--COMMIT;
--> Error Table:

  SELECT *
    FROM RA_INTERFACE_ERRORS_ALL
ORDER BY INTERFACE_LINE_ID DESC;

  SELECT ra.creation_date, ra.*
    FROM RA_INTERFACE_LINES_ALL ra
   WHERE 1 = 1 AND ORG_ID = 126 
   --AND TRUNC (CREATION_DATE) BETWEEN TO_DATE ('14-JUN-2021') AND TO_DATE ('14-JUN-2021')
   --AND CUSTOMER_TRX_ID=959769
   --AND SALES_ORDER_SOURCE='ORDER ENTRY'
   --AND LINE_TYPE='LINE'
         --AND BATCH_SOURCE_NAME = 'DBL CL Imported Invoice'
ORDER BY ra.creation_date DESC;

  SELECT rda.creation_date, rda.*
    FROM ra_interface_distributions_all rda
   WHERE 1 = 1 AND ORG_ID = 126
--AND TRUNC (CREATION_DATE) BETWEEN TO_DATE ('01-APR-2021') AND TO_DATE ('04-APR-2021')
ORDER BY rda.creation_date DESC;

--   delete RA_INTERFACE_LINES_ALL ra where interface_line_id in (1951117);--,
----1941081);
--
--update
--RA_INTERFACE_LINES_ALL ra set line_number=2 where interface_line_id in (1941118);--,
----1941081);

  SELECT *
    FROM RA_CUSTOMER_TRX_ALL
   WHERE     1 = 1
         --AND TRUNC (CREATION_DATE) BETWEEN TO_DATE ('01-APR-2021') AND TO_DATE ('04-APR-2021')
         --AND trx_number = '419047423'--'421116207'
         AND ORG_ID = 126
--AND INVOICE_CURRENCY_CODE='BDT'
ORDER BY CREATION_DATE DESC;

SELECT OOD.OPERATING_UNIT,
       OOD.ORGANIZATION_ID,
       OU.SET_OF_BOOKS_ID,
       OU.DEFAULT_LEGAL_CONTEXT_ID
  --           INTO L_OPERATING_UNIT,
  --                L_ORGANIZATION_ID,
  --                L_SET_OF_BOOKS,
  --                L_LEGAL_ENTITY_ID
  FROM ORG_ORGANIZATION_DEFINITIONS OOD, HR_OPERATING_UNITS OU
 WHERE     1 = 1
       AND OOD.OPERATING_UNIT = OU.ORGANIZATION_ID
       AND OOD.ORGANIZATION_CODE = :P_ORGANIZATION_CODE;

SELECT HCA.CUST_ACCOUNT_ID, HCAS.CUST_ACCT_SITE_ID
  FROM HZ_PARTIES HP,
       HZ_PARTY_SITES HPS,
       HZ_CUST_ACCOUNTS HCA,
       HZ_CUST_ACCT_SITES_ALL HCAS,
       HZ_CUST_SITE_USES_ALL HCSU
 WHERE     HCA.PARTY_ID = HP.PARTY_ID
       AND HP.PARTY_ID = HPS.PARTY_ID
       AND HCA.CUST_ACCOUNT_ID = HCAS.CUST_ACCOUNT_ID
       AND HCAS.CUST_ACCT_SITE_ID = HCSU.CUST_ACCT_SITE_ID
       AND HCAS.PARTY_SITE_ID = HPS.PARTY_SITE_ID
       AND HCSU.SITE_USE_CODE = 'BILL_TO'
       AND HCSU.PRIMARY_FLAG = 'Y'
       AND HCA.ACCOUNT_NUMBER = :P_CUSTOMER_NUMBER
       AND HCAS.ORG_ID = :L_OPERATING_UNIT;


SELECT HCAS.CUST_ACCT_SITE_ID,
       TER.TERRITORY_ID,
       TER.SEGMENT1,
       TER.SEGMENT2,
       TER.SEGMENT3,
       TER.SEGMENT4,
       HCSU.PRIMARY_SALESREP_ID
  --              INTO L_SHIP_TO_SITE_ID,
  --                   L_TERRITORY_ID,
  --                   L_T_SEGMENT1,
  --                   L_T_SEGMENT2,
  --                   L_T_SEGMENT3,
  --                   L_T_SEGMENT4
  FROM HZ_PARTIES HP,
       HZ_PARTY_SITES HPS,
       HZ_CUST_ACCOUNTS HCA,
       HZ_CUST_ACCT_SITES_ALL HCAS,
       HZ_CUST_SITE_USES_ALL HCSU,
       ra_territories ter
 WHERE     HP.PARTY_ID = HPS.PARTY_ID
       AND HCA.PARTY_ID = HP.PARTY_ID
       AND HCA.CUST_ACCOUNT_ID = HCAS.CUST_ACCOUNT_ID
       AND HCAS.CUST_ACCT_SITE_ID = HCSU.CUST_ACCT_SITE_ID
       AND HPS.PARTY_SITE_ID = HCAS.PARTY_SITE_ID
       AND HCSU.TERRITORY_ID = TER.TERRITORY_ID(+)
       AND HCSU.SITE_USE_CODE = 'SHIP_TO'
       AND HCSU.PRIMARY_FLAG = 'Y'
       AND HCA.ACCOUNT_NUMBER = :P_CUSTOMER_NUMBER
       AND HCAS.ORG_ID = :L_OPERATING_UNIT;

SELECT OOH.HEADER_ID,
       OOH.TRANSACTIONAL_CURR_CODE,
       INITCAP (OOH.FREIGHT_TERMS_CODE),
       OOH.FREIGHT_CARRIER_CODE,
       OOH.SALESREP_ID,
       OOL.LINE_ID,
       OOL.INVENTORY_ITEM_ID,
       OOL.UNIT_SELLING_PRICE,
       OOL.ORDERED_QUANTITY,
       OOH.ORDERED_DATE,
       OOL.LINE_NUMBER,
       OOL.UNIT_LIST_PRICE,
       OOL.ACTUAL_SHIPMENT_DATE
  --              INTO L_HEADER_ID,
  --                   L_TRANSACTIONAL_CURR_CODE,
  --                   L_FREIGHT_TERMS_CODE,
  --                   L_FREIGHT_CARRIER_CODE,
  --                   L_SALESREP_ID,
  --                   L_LINE_ID,
  --                   L_INVENTORY_ITEM_ID,
  --                   L_UNIT_SELLING_PRICE,
  --                   L_ORDERED_QUANTITY,
  --                   L_ORDERED_DATE,
  --                   L_LINE_NUMBER,
  --                   L_UNIT_LIST_PRICE,
  --                   L_ACTUAL_SHIP_DATE
  FROM OE_ORDER_HEADERS_ALL OOH, OE_ORDER_LINES_ALL OOL
 WHERE     1 = 1
       AND OOH.HEADER_ID = OOL.HEADER_ID
       AND ORDER_NUMBER = :P_SALES_ORDER
       AND LINE_NUMBER = :LINE_NUMBER;


SELECT (  NVL ( :P_QUANTITY, :L_ORDERED_QUANTITY)
        * NVL ( :P_UNIT_SELLING_PRICE, :L_UNIT_SELLING_PRICE))
  --INTO L_AMOUNT
  FROM DUAL;

SELECT ( :P_QUANTITY * :P_UNIT_SELLING_PRICE)
  --INTO L_AMOUNT
  FROM DUAL;



SELECT CTT.NAME, CUST_TRX_TYPE_ID
  --INTO L_CUST_TRX_TYPE_ID
  FROM RA_CUST_TRX_TYPES_ALL CTT
 WHERE     (   :P_CUST_TRX_TYPE IS NULL
            OR (UPPER (NAME) LIKE UPPER ('%' || :P_CUST_TRX_TYPE || '%')))
       AND CUST_TRX_TYPE_ID = 17162
--and CTT.NAME = :P_CUST_TRX_TYPE
;

SELECT NAME, batch_source_id, org_id
  --INTO v_batch_source_id
  FROM ra_batch_sources_all
 WHERE     1 = 1
       AND UPPER (NAME) LIKE UPPER ('%' || :P_BATCH_SOURCE || '%')
       AND org_id = :p_org_id;

SELECT MSI.INVENTORY_ITEM_ID, MSI.PRIMARY_UOM_CODE
  --INTO L_INVENTORY_ITEM_ID, L_UOM_CODE
  FROM APPS.MTL_SYSTEM_ITEMS_B MSI
 WHERE     SEGMENT1 = :P_ITEM_CODE
       AND ORGANIZATION_ID = :L_ORGANIZATION_ID
       AND ENABLED_FLAG = 'Y';



   --DELETE FROM ra_interface_table_stg;

SELECT *
  FROM xxdbl_ra_interface_upload_stg
 WHERE 1 = 1 AND FLAG IS NULL;


EXECUTE apps.xxdbl_ar_interface_upload_pkg.import_data_to_ar_interface(' ',' ');

EXECUTE APPS.xxdbl_cer_ar_intf_upld_pkg.upload_data_to_ar_int_stg ('6','DBL CL Imported Invoice','Invoice','For Dealer','1','05-JUN-2021','05-JUN-2021','BDT','2620','W2540-022BRL','1','3000','User','1');