/* Formatted on 5/16/2021 10:12:13 AM (QP5 v5.287) */
SPOOL C:\Users\user\Desktop\MIS\select_query.out
SET LINES 150 PAGES 150
SET LONG 10000
SET AUTOTRACE ON

SELECT "A"."TRANSACTION_ID" "TRANSACTION_ID",
       "C"."SEGMENT1" "ITEM_CODE",
       "C"."DESCRIPTION" "ITEM_DESCRIPTION",
       "C"."PRIMARY_UOM_CODE" "UOM",
       "MIC"."SEGMENT2" "ITEM_CATEGORY",
       "MIC"."SEGMENT3" "ITEM_TYPE",
       "A"."PRIMARY_QUANTITY" "TRX_QUANTITY"
  FROM "INV"."MTL_MATERIAL_TRANSACTIONS" "A",
       "INV"."MTL_TXN_REQUEST_HEADERS" "B",
       "APPS"."MTL_TXN_REQUEST_LINES_V" "MTRL",
       "APPS"."MTL_SYSTEM_ITEMS_B_KFV" "C",
       "APPS"."MTL_ITEM_CATEGORIES_V" "MIC",
       "GL"."GL_CODE_COMBINATIONS" "CC",
       "INV"."MTL_PARAMETERS" "MP",
       "APPS"."ORG_ORGANIZATION_DEFINITIONS" "OOD",
       "APPS"."HR_OPERATING_UNITS" "HOU",
       "INV"."ORG_ACCT_PERIODS" "PRD",
       "APPLSYS"."FND_USER" "FNU"
 WHERE     "A"."ORGANIZATION_ID" = "MP"."ORGANIZATION_ID"
       AND "MP"."ORGANIZATION_ID" = "OOD"."ORGANIZATION_ID"
       AND "OOD"."OPERATING_UNIT" = "HOU"."ORGANIZATION_ID"
       AND "A"."INVENTORY_ITEM_ID" = "C"."INVENTORY_ITEM_ID"
       AND "A"."ORGANIZATION_ID" = "C"."ORGANIZATION_ID"
       AND "A"."INVENTORY_ITEM_ID" = "MIC"."INVENTORY_ITEM_ID"
       AND "A"."ORGANIZATION_ID" = "MIC"."ORGANIZATION_ID"
       AND "A"."TRANSACTION_SOURCE_ID" = "B"."HEADER_ID"
       AND "B"."HEADER_ID" = "MTRL"."HEADER_ID"
       AND "B"."CREATED_BY" = "FNU"."USER_ID"
       AND "A"."DISTRIBUTION_ACCOUNT_ID" = "CC"."CODE_COMBINATION_ID"
       AND "A"."ACCT_PERIOD_ID" = "PRD"."ACCT_PERIOD_ID"
       AND "A"."TRANSACTION_QUANTITY" < 0
       AND "A"."ORGANIZATION_ID" = "PRD"."ORGANIZATION_ID"
       AND "MTRL"."INVENTORY_ITEM_ID" = "A"."INVENTORY_ITEM_ID"
       AND "MTRL"."ORGANIZATION_ID" = "A"."ORGANIZATION_ID"
       AND "MTRL"."LINE_ID" = "A"."TRX_SOURCE_LINE_ID"
       AND "A"."TRANSACTION_SOURCE_ID" = "B"."HEADER_ID";