/* Formatted on 1/7/2021 10:20:59 AM (QP5 v5.287) */
--CCL2 Debtor MANAGEMENT MIGRATION TO Production INSTANCE-Technical Script
------------------------Manual PI----------------------------------
--Step1: CREATE XXDBL_MANUAL_PI_HEADER TABLE

CREATE TABLE XXDBL.XXDBL_MANUAL_PI_HEADER
(
   MANUAL_PI_ID        INTEGER NOT NULL,
   CREATED_BY          NUMBER,
   CREATION_DATE       DATE,
   LAST_UPDATE_LOGIN   NUMBER,
   LAST_UPDATED_BY     NUMBER,
   LAST_UPDATE_DATE    DATE,
   OPERATING_UNIT      NUMBER,
   LEGAL_ENTITY_ID     NUMBER,
   ORGANIZATION_ID     VARCHAR2 (50 BYTE),
   MANUAL_PI_NUMBER    VARCHAR2 (50 BYTE),
   MANUAL_PI_DATE      DATE,
   STATUS              VARCHAR2 (50 BYTE),
   CUSTOMER_NO         VARCHAR2 (50 BYTE),
   CUSTOMER_NAME       VARCHAR2 (50 BYTE),
   PO_NUMBER           VARCHAR2 (50 BYTE),
   STYLE               VARCHAR2 (50 BYTE),
   MERCHANDISER_NAME   VARCHAR2 (50 BYTE),
   MANUAL_BS_NUMBER    VARCHAR2 (50 BYTE),
   MANUAL_BS_DATE      DATE,
   BUYER               VARCHAR2 (30 BYTE),
   PAYMENT_TERMS       VARCHAR2 (240 BYTE),
   BANK_NAME           VARCHAR2 (500 BYTE),
   CONSTRAINT MANUAL_PI_PK PRIMARY KEY (MANUAL_PI_ID)
);

CREATE OR REPLACE SYNONYM APPS.XXDBL_MANUAL_PI_HEADER FOR XXDBL.XXDBL_MANUAL_PI_HEADER;

CREATE OR REPLACE SYNONYM APPSRO.XXDBL_MANUAL_PI_HEADER FOR XXDBL.XXDBL_MANUAL_PI_HEADER;

--Step2: CREATE XXDBL_MANUAL_PI_LINE TABLE

CREATE TABLE XXDBL.XXDBL_MANUAL_PI_LINE
(
   MANUAL_PI_LINE_ID   INTEGER NOT NULL,
   MANUAL_PI_ID        INTEGER NOT NULL,
   CREATED_BY          NUMBER,
   CREATION_DATE       DATE,
   LAST_UPDATE_LOGIN   NUMBER,
   LAST_UPDATED_BY     NUMBER,
   LAST_UPDATE_DATE    DATE,
   ARTICLE_NAME        VARCHAR2 (50 BYTE),
   INVENTORY_ITEM_ID   NUMBER,
   ITEM_CODE           VARCHAR2 (50 BYTE),
   ITEM_DESCRIPTION    VARCHAR2 (500 BYTE),
   UNIT_OF_MEASURE     VARCHAR2 (50 BYTE),
   QUANTITY            NUMBER,
   GROSS_WEIGHT        NUMBER,
   NET_WEIGHT          NUMBER,
   UNIT_PRICE          NUMBER,
   NET_VALUE           NUMBER,
   CONSTRAINT MANUAL_PI_LN_PK PRIMARY KEY (MANUAL_PI_LINE_ID)
);

CREATE OR REPLACE SYNONYM APPS.XXDBL_MANUAL_PI_LINE FOR XXDBL.XXDBL_MANUAL_PI_LINE;

CREATE OR REPLACE SYNONYM APPSRO.XXDBL_MANUAL_PI_LINE FOR XXDBL.XXDBL_MANUAL_PI_LINE;

--Step3: CREATE XXDBL_MANUAL_PI_S SEQUENCE

CREATE SEQUENCE XXDBL.XXDBL_MANUAL_PI_S START WITH 1000001
                                        MAXVALUE 9999999999999999999999999999
                                        MINVALUE 0
                                        NOCYCLE
                                        NOCACHE
                                        NOORDER
                                        NOKEEP
                                        GLOBAL;

  CREATE OR REPLACE SYNONYM APPS.XXDBL_MANUAL_PI_S FOR XXDBL.XXDBL_MANUAL_PI_S;

------------------------Bill Statement----------------------------------
--Step4: Add Column to XXDBL_BILL_STAT_HEADERS table

ALTER TABLE XXDBL.XXDBL_BILL_STAT_HEADERS
   ADD (CORRECTED_DATE DATE, CORRECTION_VERSION NUMBER);

CREATE OR REPLACE SYNONYM APPS.XXDBL_BILL_STAT_HEADERS FOR XXDBL.XXDBL_BILL_STAT_HEADERS;

CREATE OR REPLACE PUBLIC SYNONYM XXDBL_BILL_STAT_HEADERS FOR XXDBL.XXDBL_BILL_STAT_HEADERS;


------------------------Pro-Forma Invoice----------------------------------

--Step5: Add Column to XXDBL_PROFORMA_HEADERS table

ALTER TABLE XXDBL.XXDBL_PROFORMA_HEADERS
   ADD (CORRECTED_DATE DATE,
        CORRECTION_VERSION NUMBER,
        MANUAL_PI_NO VARCHAR2 (50),
        LC_REQ_MON DATE);

CREATE OR REPLACE PUBLIC SYNONYM XXDBL_PROFORMA_HEADERS FOR XXDBL.XXDBL_PROFORMA_HEADERS;



------------------------Master LC----------------------------------
--Step6: Add Column to XXDBL_MASTER_LC_HEADERS table

ALTER TABLE XXDBL.XXDBL_MASTER_LC_HEADERS
   ADD (CUST_ACCEPT_DATE DATE,
        MPI_NUMBER VARCHAR2 (100 BYTE),
        LC_RCV_DATE DATE,
        LC_TYPE VARCHAR2 (100 BYTE),
        CH_REQ_DATE DATE,
        LC_RCV_FRM_BANK_DT DATE,
        EXP_EXPIRE_DATE DATE,
        UP_NUMBER VARCHAR2 (100 BYTE),
        UP_DATE DATE,
        UD_IP_NO VARCHAR2 (100 BYTE),
        UD_IP_RCV_DT DATE,
        UD_IP_HND_OVR_DT DATE,
        UD_IP_ISSUE_DT DATE,
        UD_IP_EXP_DT DATE,
        UD_ISSUE_DT DATE,
        BILL_ENTRY_NO VARCHAR2 (100 BYTE),
        BILL_ENTRY_DT DATE,
        INFO_REMARKS VARCHAR2 (500 BYTE));

CREATE OR REPLACE PUBLIC SYNONYM XXDBL_MASTER_LC_HEADERS FOR XXDBL.XXDBL_MASTER_LC_HEADERS;

------------------------Commercial Invoice----------------------------------
--Step7: Add Column to XXDBL_COMM_INV_HEADERS table

ALTER TABLE XXDBL.XXDBL_COMM_INV_HEADERS
   ADD (MAN_COM_INV_NO VARCHAR2 (100 BYTE),
        CH_RCV_DT DATE,
        DT_TO_SALES_SEVC DATE,
        DT_TO_SALES_SEVC_DEL VARCHAR2 (500 BYTE),
        DT_TO_CUST DATE,
        DT_TO_CUST_DEL_RES VARCHAR2 (500 BYTE),
        DT_FROM_CUST DATE,
        CUST_ACCT_SIGN_DT DATE,
        DOC_HOVER_GRP_COM DATE,
        DT_TO_BANK DATE,
        BANK_REF_NO VARCHAR2 (100 BYTE),
        DISCOUNT_DATE DATE,
        DIS_AMNT NUMBER,
        B2B_ACCT_DT DATE,
        MATURITY_DT DATE,
        REALIZED_DT DATE,
        DECREPENCY_AMNT NUMBER,
        DECREPENCY_DETL VARCHAR2 (500 BYTE),
        RESN_DEL_BANK VARCHAR2 (500 BYTE),
        INFO_REMARKS VARCHAR2 (500 BYTE));

CREATE OR REPLACE SYNONYM APPS.XXDBL_COMM_INV_HEADERS FOR XXDBL.XXDBL_COMM_INV_HEADERS;


CREATE OR REPLACE PUBLIC SYNONYM XXDBL_COMM_INV_HEADERS FOR XXDBL.XXDBL_COMM_INV_HEADERS;