SELECT 
    JE_CATEGORY
    ,LEDGER_ID
    ,GL_VOUCHER_NUMBER
    ,PARTY_NAME||'-'||PARTY_CODE SUPPLIER
    ,PO_NUMBER
    ,ORGANIZATION_ID
    ,ORGANIZATION_CODE
    ,ORGANIZATION_NAME
    ,GOODS_RECEIPT_NUM
    ,INVENTORY_ITEM_ID
    ,ITEM_CODE_SEGMENT1||'.'||ITEM_CODE_SEGMENT2||'.'||ITEM_CODE_SEGMENT3 ITEM_CODE
    ,INVENTORY_ITEM_NAME
    ,ITEM_CATEGORY_SEGMENT1||'|'||ITEM_CATEGORY_SEGMENT2 ITEM_CATEGORY
    ,TRANSACTION_TYPE
    ,TRANSACTION_ID
    ,VOUCHER_NUMBER
    ,VOUCHER_DATE
    ,COMPANY||'.'||COST_CENTER||'.'||ACCOUNT||'.'||INTER_PROJECT||'.'||FUTURE ACCOUNT
    ,ACCTDESC
    ,ENTERED_DEBITS
    ,ENTERED_CREDITS
    ,DEBITS
    ,CREDITS
    ,CHEQUE_DATE
FROM 
    (
    SELECT 13 UNION_PART,
       707 APPLICATION_ID,
       'CST' JE_SOURCE,
       CAT.NAME JE_CATEGORY,
       CC.SEGMENT1 COMPANY,
       CC.SEGMENT2 COST_CENTER,
       CC.SEGMENT3 ACCOUNT,
       CC.SEGMENT4 INTER_PROJECT,
       CC.SEGMENT5 FUTURE,
       FLEX.DESCRIPTION ACCTDESC,
       RCVT.TRANSACTION_ID VOUCHER_NUMBER,
       GJH.DOC_SEQUENCE_VALUE GL_VOUCHER_NUMBER,
       GJL.JE_LINE_NUM GL_JE_LINE_NUM,
       XAL.ACCOUNTING_DATE VOUCHER_DATE,
       CAST (NULL AS VARCHAR2 (100)) PARTICULARS,
       XAL.ENTERED_DR ENTERED_DEBITS,
       XAL.ENTERED_CR ENTERED_CREDITS,
       XAL.ACCOUNTED_DR DEBITS,
       XAL.ACCOUNTED_CR CREDITS,
       CAST (NULL AS VARCHAR2 (100)) CHEQUE_NUMBER,
       TRUNC (SYSDATE) CHEQUE_DATE,
       APS.SEGMENT1 PARTY_CODE,
       APS.VENDOR_NAME PARTY_NAME,
       XAE.EVENT_TYPE_CODE TRANSACTION_TYPE,
       CC.CHART_OF_ACCOUNTS_ID,
       GJH.LEDGER_ID,
       CAST (NULL AS VARCHAR2 (100)) DFF_CONTEXT,
       CAST (NULL AS VARCHAR2 (100)) ATTRIBUTE1,
       CAST (NULL AS VARCHAR2 (100)) ATTRIBUTE2,
       CAST (NULL AS VARCHAR2 (100)) ATTRIBUTE3,
       CAST (NULL AS VARCHAR2 (100)) ATTRIBUTE4,
       CAST (NULL AS VARCHAR2 (100)) ATTRIBUTE5,
       ORG.ORGANIZATION_ID,
       ORG.ORGANIZATION_CODE,
       ORG.ORGANIZATION_NAME,
       MST.INVENTORY_ITEM_ID,
       MST.SEGMENT1 ITEM_CODE_SEGMENT1,
       MST.SEGMENT2 ITEM_CODE_SEGMENT2,
       MST.SEGMENT3 ITEM_CODE_SEGMENT3,
       MST.DESCRIPTION INVENTORY_ITEM_NAME,
       MCB.SEGMENT1 ITEM_CATEGORY_SEGMENT1,
       MCB.SEGMENT2 ITEM_CATEGORY_SEGMENT2,
       RCVH.RECEIPT_NUM GOODS_RECEIPT_NUM,
       RCVT.TRANSACTION_ID,
       POH.SEGMENT1 PO_NUMBER
  FROM AP.AP_SUPPLIERS APS,
       PO.PO_HEADERS_ALL POH,
       PO.PO_LINES_ALL POL,
       PO.RCV_SHIPMENT_HEADERS RCVH,
       PO.RCV_TRANSACTIONS RCVT,
       XLA.XLA_TRANSACTION_ENTITIES XATE, --XLA.XLA_TRANSACTION_ENTITIES_UPG XATE,
       XLA.XLA_EVENTS XAE,
       XLA.XLA_DISTRIBUTION_LINKS XDL,
       XLA.XLA_AE_LINES XAL,
       XLA.XLA_AE_HEADERS XAH,
       GL.gl_import_references GIR,
       GL.gl_je_lines GJL,
       GL.gl_je_headers GJH,
       GL.gl_code_combinations cc,
       APPLSYS.FND_DOC_SEQUENCE_CATEGORIES CAT,
       APPLSYS.FND_FLEX_VALUES_TL FLEX,
       INV.MTL_SYSTEM_ITEMS_B MST,
       --APPS.XXAKG_ORG_DEF_T ORG,           
       ORG_ORGANIZATION_DEFINITIONS ORG,
       INV.MTL_CATEGORIES_B MCB,
       INV.MTL_ITEM_CATEGORIES MIC                                         --,
 --DATABASE_PROPERTIES DB
 WHERE     APS.VENDOR_ID = RCVH.VENDOR_ID
       AND POL.PO_LINE_ID = RCVT.PO_LINE_ID
       AND POH.PO_HEADER_ID = POL.PO_HEADER_ID
       AND RCVH.SHIPMENT_HEADER_ID = RCVT.SHIPMENT_HEADER_ID
       AND RCVT.TRANSACTION_ID = XATE.SOURCE_ID_INT_1
       AND XATE.ENTITY_ID = XAE.ENTITY_ID
       AND XDL.EVENT_ID = XAE.EVENT_ID
       AND XDL.source_distribution_type = 'RCV_RECEIVING_SUB_LEDGER'
       AND XDL.APPLICATION_ID = XAH.APPLICATION_ID
       AND XDL.APPLICATION_ID = 707
       AND XDL.AE_HEADER_ID = XAH.AE_HEADER_ID
       AND XDL.AE_LINE_NUM = XAL.AE_LINE_NUM
       AND XAL.AE_HEADER_ID = XAH.AE_HEADER_ID
       AND XAL.gl_sl_link_id = GIR.gl_sl_link_id
       AND GIR.gl_sl_link_table IN ('APECL', 'XLAJEL')
       AND GIR.je_header_id = GJL.je_header_id
       AND GIR.je_line_num = GJL.je_line_num
       AND GIR.je_header_id = GJH.je_header_id
       AND GJH.JE_HEADER_ID = GJL.JE_HEADER_ID
       AND GJL.code_combination_id = cc.code_combination_id
       AND GJH.JE_CATEGORY = CAT.CODE
       AND CAT.APPLICATION_ID = 101
       AND CC.SEGMENT3 = FLEX.FLEX_VALUE_MEANING
--       AND CC.SEGMENT1||'.'||CC.SEGMENT2||'.'||CC.SEGMENT3||'.'||CC.SEGMENT4||'.'||CC.SEGMENT5 = '2300.COMM.2050110.9999.00'
       AND RCVT.ORGANIZATION_ID = MST.ORGANIZATION_ID
       AND POL.ITEM_ID = MST.INVENTORY_ITEM_ID
       AND RCVT.ORGANIZATION_ID = ORG.ORGANIZATION_ID
       AND MCB.STRUCTURE_ID = 101
       AND MCB.CATEGORY_ID = MIC.CATEGORY_ID
       AND MIC.INVENTORY_ITEM_ID = MST.INVENTORY_ITEM_ID
       AND MIC.ORGANIZATION_ID = MST.ORGANIZATION_ID
       AND GJH.ACTUAL_FLAG = 'A'
       AND GJL.STATUS = 'P'
       AND (NVL (XAL.ACCOUNTED_DR, 0) <> 0 OR NVL (XAL.ACCOUNTED_CR, 0) <> 0)
       AND FLEX.LANGUAGE = USERENV ('LANG')
--       AND RCVH.RECEIPT_NUM in (1456)
--       AND ORG.ORGANIZATION_ID in (362)
     UNION ALL
SELECT 13 UNION_PART,
       707 APPLICATION_ID,
       'CST' JE_SOURCE,
       CAT.NAME JE_CATEGORY,
       CC.SEGMENT1 COMPANY,
       CC.SEGMENT2 COST_CENTER,
       CC.SEGMENT3 ACCOUNT,
       CC.SEGMENT4 INTER_PROJECT,
       CC.SEGMENT5 FUTURE,
       FLEX.DESCRIPTION ACCTDESC,
       MMT.TRANSACTION_ID VOUCHER_NUMBER,
       GJH.DOC_SEQUENCE_VALUE GL_VOUCHER_NUMBER,
       GJL.JE_LINE_NUM GL_JE_LINE_NUM,
       XAL.ACCOUNTING_DATE VOUCHER_DATE,
       CAST (NULL AS VARCHAR2 (100)) PARTICULARS,
       XAL.ENTERED_DR ENTERED_DEBITS,
       XAL.ENTERED_CR ENTERED_CREDITS,
       XAL.ACCOUNTED_DR DEBITS,
       XAL.ACCOUNTED_CR CREDITS,
       CAST (NULL AS VARCHAR2 (100)) CHEQUE_NUMBER,
       TRUNC (SYSDATE) CHEQUE_DATE,
       APS.SEGMENT1 PARTY_CODE,
       APS.VENDOR_NAME PARTY_NAME,
       rcvt.TRANSACTION_TYPE,
       CC.CHART_OF_ACCOUNTS_ID,
       GJH.LEDGER_ID,
       CAST (NULL AS VARCHAR2 (100)) DFF_CONTEXT,
       CAST (NULL AS VARCHAR2 (100)) ATTRIBUTE1,
       CAST (NULL AS VARCHAR2 (100)) ATTRIBUTE2,
       CAST (NULL AS VARCHAR2 (100)) ATTRIBUTE3,
       CAST (NULL AS VARCHAR2 (100)) ATTRIBUTE4,
       CAST (NULL AS VARCHAR2 (100)) ATTRIBUTE5,
       ORG.ORGANIZATION_ID,
       ORG.ORGANIZATION_CODE,
       ORG.ORGANIZATION_NAME,
       MST.INVENTORY_ITEM_ID,
       MST.SEGMENT1 ITEM_CODE_SEGMENT1,
       MST.SEGMENT2 ITEM_CODE_SEGMENT2,
       MST.SEGMENT3 ITEM_CODE_SEGMENT3,
       MST.DESCRIPTION INVENTORY_ITEM_NAME,
       MCB.SEGMENT1 ITEM_CATEGORY_SEGMENT1,
       MCB.SEGMENT2 ITEM_CATEGORY_SEGMENT2,
       RCVH.RECEIPT_NUM GOODS_RECEIPT_NUM,
       RCVT.TRANSACTION_ID,
       POH.SEGMENT1 PO_NUMBER
  FROM 
       AP.AP_SUPPLIERS APS,
       XLA.XLA_EVENTS XAE,
       XLA.XLA_DISTRIBUTION_LINKS XDL,
       XLA.XLA_AE_LINES XAL,
       XLA.XLA_AE_HEADERS XAH,
       GL.gl_import_references GIR,
       GL.gl_je_lines GJL,
       GL.gl_je_headers GJH,
       GL.gl_code_combinations cc,
       APPLSYS.FND_DOC_SEQUENCE_CATEGORIES CAT,
       APPLSYS.FND_FLEX_VALUES_TL FLEX,
       APPS.MTL_TRANSACTION_ACCOUNTS MTA,
       APPS.MTL_MATERIAL_TRANSACTIONS MMT,
--       APPS.MTL_TXN_REQUEST_HEADERS MTRH,
       PO.PO_HEADERS_ALL POH,
       PO.PO_LINES_ALL POL,
       PO.RCV_SHIPMENT_HEADERS RCVH,
       PO.RCV_TRANSACTIONS RCVT,
       INV.MTL_SYSTEM_ITEMS_B MST,
       --APPS.XXAKG_ORG_DEF_T ORG,   
       ORG_ORGANIZATION_DEFINITIONS ORG,       
       INV.MTL_CATEGORIES_B MCB,
       INV.MTL_ITEM_CATEGORIES MIC
 WHERE 1=1
       AND APS.VENDOR_ID = RCVH.VENDOR_ID
       AND POL.PO_LINE_ID = RCVT.PO_LINE_ID
       AND POH.PO_HEADER_ID = POL.PO_HEADER_ID
--       AND GJH.DOC_SEQUENCE_VALUE = '113002710'
       AND XDL.EVENT_ID = XAE.EVENT_ID
       AND XDL.source_distribution_type = 'MTL_TRANSACTION_ACCOUNTS'
       AND XDL.APPLICATION_ID = XAH.APPLICATION_ID
       AND XDL.APPLICATION_ID = 707
       AND XDL.AE_HEADER_ID = XAH.AE_HEADER_ID
       AND XDL.AE_LINE_NUM = XAL.AE_LINE_NUM
       AND XAL.AE_HEADER_ID = XAH.AE_HEADER_ID
       AND XAL.gl_sl_link_id = GIR.gl_sl_link_id
       AND GIR.gl_sl_link_table IN ('APECL', 'XLAJEL')
       AND GIR.je_header_id = GJL.je_header_id
       AND GIR.je_line_num = GJL.je_line_num
       AND GIR.je_header_id = GJH.je_header_id
       AND GJH.JE_HEADER_ID = GJL.JE_HEADER_ID
       AND GJL.code_combination_id = cc.code_combination_id
       AND GJH.JE_CATEGORY = CAT.CODE
       AND CAT.APPLICATION_ID = 101
       AND RCVH.SHIPMENT_HEADER_ID = RCVT.SHIPMENT_HEADER_ID
       AND RCVT.ORGANIZATION_ID = ORG.ORGANIZATION_ID
       AND CC.SEGMENT3 = FLEX.FLEX_VALUE_MEANING
--       AND CC.SEGMENT1||'.'||CC.SEGMENT2||'.'||CC.SEGMENT3||'.'||CC.SEGMENT4||'.'||CC.SEGMENT5 = '2300.COMM.2050110.9999.00'
       AND XDL.SOURCE_DISTRIBUTION_ID_NUM_1 = MTA.INV_SUB_LEDGER_ID
       AND MTA.TRANSACTION_ID = MMT.TRANSACTION_ID
       AND MMT.RCV_TRANSACTION_ID = RCVT.TRANSACTION_ID
       AND MMT.TRANSACTION_SOURCE_ID = MTA.TRANSACTION_SOURCE_ID
--       AND MMT.TRANSACTION_SOURCE_ID = MTRH.HEADER_ID
       AND RCVH.SHIPMENT_HEADER_ID = RCVT.SHIPMENT_HEADER_ID
       AND MMT.ORGANIZATION_ID = MST.ORGANIZATION_ID
       AND MMT.INVENTORY_ITEM_ID = MST.INVENTORY_ITEM_ID
       AND MMT.ORGANIZATION_ID = ORG.ORGANIZATION_ID
       AND POL.ITEM_ID = MST.INVENTORY_ITEM_ID
       AND MCB.STRUCTURE_ID = 101
       AND MCB.CATEGORY_ID = MIC.CATEGORY_ID
       AND MIC.INVENTORY_ITEM_ID = MST.INVENTORY_ITEM_ID
       AND MIC.ORGANIZATION_ID = MST.ORGANIZATION_ID
       AND GJH.ACTUAL_FLAG = 'A'
       AND GJL.STATUS = 'P'
       AND (NVL (XAL.ACCOUNTED_DR, 0) <> 0 OR NVL (XAL.ACCOUNTED_CR, 0) <> 0)
       AND FLEX.LANGUAGE = USERENV ('LANG')
--       AND RCVH.RECEIPT_NUM in (1456)
--       AND ORG.ORGANIZATION_ID in (362)
--       AND RCVT.TRANSACTION_ID in ('300279')
    )
    WHERE 1=1
    AND PO_NUMBER in ('15243000014')
--    AND GOODS_RECEIPT_NUM in ('9189')
    ORDER BY PO_NUMBER,GOODS_RECEIPT_NUM,INVENTORY_ITEM_ID,TRANSACTION_ID