CREATE TABLE customers  
( customer_id number(10) NOT NULL,  
  customer_name varchar2(50) NOT NULL,  
  city varchar2(50),  
  CONSTRAINT customers_pk PRIMARY KEY (customer_id)  
); 

CREATE TABLE W_MTL_TRANSACTION_TYPES  
( TRANSACTION_TYPE_ID number NOT NULL,  
  TRANSACTION_TYPE_NAME varchar2(50) NOT NULL,
  CONSTRAINT TRX_TYPES_PK PRIMARY KEY (TRANSACTION_TYPE_ID)  
);


CREATE TABLE W_MTL_SYSTEM_ITEMS_B  
( INVENTORY_ITEM_ID number NOT NULL,  
  ORGANIZATION_ID varchar2(50) NOT NULL,
  ITEM_CODE varchar2(50),
  DESCRIPTION varchar2(100),
  CONSTRAINT MTL_ITEMS_PK PRIMARY KEY (INVENTORY_ITEM_ID)  
);

ALTER TABLE W_MTL_SYSTEM_ITEMS_B
DROP CONSTRAINT MTL_ITEMS_PK;

alter table
   W_MTL_SYSTEM_ITEMS_B
modify
(
   ORGANIZATION_ID    number
);


CREATE TABLE W_MTL_TRANSACTION_LOT_NUMBERS  
( INVENTORY_ITEM_ID number,  
  ORGANIZATION_ID varchar2(50),
  TRANSACTION_ID number,
  LOT_NUMBER varchar2(100),
  ATTRIBUTE1 varchar2(100),
  CONSTRAINT MTL_LOT_TRX_PK PRIMARY KEY (TRANSACTION_ID)  
);

alter table
   W_MTL_TRANSACTION_LOT_NUMBERS
modify
(
   ORGANIZATION_ID    number
);


CREATE TABLE W_ORG_ORGANIZATION_DEFINITIONS  
( ORGANIZATION_ID number,
  ORGANIZATION_NAME varchar2(100),
  ORGANIZATION_CODE varchar2(30),
  CONSTRAINT ORG_DEF_PK PRIMARY KEY (ORGANIZATION_ID)  
);

ALTER TABLE W_ORG_ORGANIZATION_DEFINITIONS
ADD CONSTRAINT ORG_DEF_PK PRIMARY KEY (ORGANIZATION_ID);

ALTER TABLE W_ORG_ORGANIZATION_DEFINITIONS
DROP CONSTRAINT ORG_DEF_PK;


CREATE TABLE W_MTL_ITEM_CATEGORIES_V  
( ORGANIZATION_ID number,
  INVENTORY_ITEM_ID number,
  CATEGORY_SET_ID number,
  SEGMENT2 varchar2(50),
  SEGMENT3 varchar2(50) 
);


DROP TABLE W_MTL_MATERIAL_TRANSACTIONS;

CREATE TABLE W_MTL_MATERIAL_TRANSACTIONS
(
  TRANSACTION_ID NUMBER,
  SUBINVENTORY_CODE  VARCHAR2(80),
  TRANSACTION_UOM    VARCHAR2(5),
  TRANSACTION_DATE   DATE,
  SOURCE_CODE        VARCHAR2(30),
  PRIMARY_QUANTITY   NUMBER,
  NEW_COST           NUMBER,
  INVENTORY_ITEM_ID  NUMBER,
  ORGANIZATION_ID NUMBER,
  TRANSACTION_TYPE_ID NUMBER,
  ATTRIBUTE_CATEGORY VARCHAR2(100),
  ATTRIBUTE2 VARCHAR2(100),
  CONSTRAINT MTL_TRX_PK PRIMARY KEY (TRANSACTION_ID) 
);

TRUNCATE TABLE W_MTL_MATERIAL_TRANSACTIONS;

ALTER TABLE W_MTL_MATERIAL_TRANSACTIONS 
ADD (
  LOT_NUMBER varchar2(100),
  ATTRIBUTE1 varchar2(100),
  ORIGINATION_DATE DATE
);