/* Formatted on 2/4/2020 10:52:11 AM (QP5 v5.287) */
SELECT MMT.SUBINVENTORY_CODE,
       MMT.TRANSACTION_UOM,
       MMT.TRANSACTION_DATE,
       MMT.SOURCE_CODE,
       MMT.PRIMARY_QUANTITY,
       MMT.PRIMARY_QUANTITY,
       MMT.NEW_COST
  FROM MTL_MATERIAL_TRANSACTIONS MMT
 WHERE ATTRIBUTE_CATEGORY = 'Grey Yarn Issue for Knitting';