/* Formatted on 7/7/2021 10:36:43 AM (QP5 v5.354) */
SELECT ICRM.SET_OF_BOOKS_ID,
       ICRM.ORGANIZATION_ID,
       ICRM.ORGANIZATION_NAME,
       ICRM.TR_TYPE,
       ICRM.TRANSACTION_ID,
       ICRM.TRANSACTION_DATE,
       ICRM.MO_NO,
       ICRM.ITEM_CODE,
       ICRM.ITEM_DESCRIPTION,
       ICRM.UOM,
       ICRM.ITEM_CATEGORY,
       ICRM.ITEM_TYPE,
       ICRM.USE_AREA,
       ICRM.LOCATION_DESC,
       ICRM.PRODUCT_LINE_DESC,
          ICRM.COST_CENTER_DESC
       || ' - '
       || (SELECT DESCRIPTION
             FROM FND_FLEX_VALUES_VL
            WHERE     FLEX_VALUE_SET_ID = 1017032
                  AND FLEX_VALUE = ICRM.COST_CENTER_DESC)
           COST_CENTER_DESC,
          ICRM.NATURAL_ACCOUNT_DESC
       || ' - '
       || (SELECT DESCRIPTION
             FROM FND_FLEX_VALUES_VL
            WHERE     FLEX_VALUE_SET_ID = 1017040
                  AND FLEX_VALUE = ICRM.NATURAL_ACCOUNT_DESC)
           NATURAL_ACCOUNT_DESC,
          ICRM.SUB_ACCCOUNT_DESC
       || ' - '
       || (SELECT DESCRIPTION
             FROM APPS.FND_FLEX_VALUES_TL
            WHERE FLEX_VALUE_ID =
                  (SELECT FLEX_VALUE_ID
                     FROM APPS.FND_FLEX_VALUES
                    WHERE     FLEX_VALUE_SET_ID =
                              (SELECT FLEX_VALUE_SET_ID
                                 FROM APPS.FND_FLEX_VALUE_SETS
                                WHERE FLEX_VALUE_SET_NAME =
                                      'XXDBL_SUB_ACCOUNT_COA')
                          AND FLEX_VALUE = ICRM.SUB_ACCCOUNT_DESC
                          AND PARENT_FLEX_VALUE_LOW =
                              (SELECT FLEX_VALUE
                                 FROM FND_FLEX_VALUES_VL B
                                WHERE     FLEX_VALUE_SET_ID = 1017040
                                      AND B.FLEX_VALUE =
                                          ICRM.NATURAL_ACCOUNT_DESC)))
           SUB_ACCCOUNT_DESC,
       ICRM.INTER_COMPANY,
       ICRM.EXP_CATEGORY_DESC,
       ICRM.CODE_COMBINATION,
       ICRM.QTY,
       ICRM.UNIT_COST,
       ICRM.TOTAL_COST,
       ICRM.BUYER_NAME,
       ICRM.CUSTOMER_NAME,
       APPS.XX_COM_PKG.GET_EMP_NAME_FROM_USER_ID (ICRM.CREATED_BY)
           CREATED_BY,
       APPS.XX_COM_PKG.GET_DEPT_FROM_USER_NAME_ID (NULL, ICRM.CREATED_BY)
           DEPARTMENT,
       (SELECT DESCRIPTION
          FROM FA_ADDITIONS
         WHERE     ASSET_NUMBER = ICRM.ASSET
               AND ICRM.ASSET_CATEGORY = 'DBL Fixed Asset List')
           ASSET_DESCRIPTION,
       ICRM.NATURAL_ACC,
       ICRM.COMPANY_CODE
  FROM APPS.XXDBL_INV_CON_RPT_MV ICRM
 WHERE     (   :P_SET_OF_BOOKS_ID IS NULL
            OR ICRM.SET_OF_BOOKS_ID = :P_SET_OF_BOOKS_ID)
       AND ( :P_COMPANY IS NULL OR ICRM.COMPANY_CODE = :P_COMPANY)
       AND ( :P_ORG_ID IS NULL OR ICRM.ORGANIZATION_ID = :P_ORG_ID)
       AND ( :P_ACCOUNT IS NULL OR ICRM.NATURAL_ACC = :P_ACCOUNT)
       AND :P_REPORT_TYPE = 'Rawdata'
       AND TRUNC (ICRM.TRANSACTION_DATE) BETWEEN :P_DATE_FROM AND :P_DATE_TO;