
ALTER TABLE XX_APEX.XX_APEX_CNF_JOB_MASTER
    DROP ( ATTRIBUTE1 , ATTRIBUTE2 , ATTRIBUTE3 , ATTRIBUTE4 , ATTRIBUTE5 , ATTRIBUTE6 , ATTRIBUTE7 , ATTRIBUTE8 , ATTRIBUTE9 , ATTRIBUTE10 );


ALTER TABLE XX_APEX.XX_APEX_CNF_JOB_MASTER
    ADD (ASSESSMENT_BY VARCHAR2 (20 BYTE),
         ASSESSMENT_BY_NAME VARCHAR2 (255 BYTE),
         ASSESSMENT_DATE DATE,
         ASSESSMENT_AMOUNT NUMBER,
         DELIVERY_ORDER_BY VARCHAR2 (20 BYTE),
         DELIVERY_ORDER_BY_NAME VARCHAR2 (255 BYTE),
         DELIVERY_ORDER_DATE DATE,
         DELIVERY_ORDER_AMOUNT NUMBER,
         DELIVERY_BY VARCHAR2 (20 BYTE),
         DELIVERY_BY_NAME VARCHAR2 (255 BYTE),
         DELIVERY_DATE DATE,
         DELIVERY_AMOUNT NUMBER,
         ON_CHASSIS_DELIVERY VARCHAR2 (1 BYTE));