/* Formatted on 12/29/2019 3:31:52 PM (QP5 v5.287) */
SELECT OPH.SHIP_HEADER_ID,
       ALLOC.ADJUSTMENT_NUM,
       OPH.ORGANIZATION_ID,
       OPL.INVENTORY_ITEM_ID,
       OPL.PRIMARY_QTY,
       OPL.PRIMARY_UOM_CODE,
       OPL.SHIP_LINE_GROUP_ID,
       OPL.SHIP_LINE_ID,
       OPL.SHIP_LINE_NUM,
       ASSOC.ASSOCIATION_ID,
       ASSOC.FROM_PARENT_TABLE_NAME ASSOC_FROM_PARENT_TABLE_NAME,
       ASSOC.FROM_PARENT_TABLE_ID ASSOC_FROM_PARENT_TABLE_ID,
       DECODE (ALLOC.TO_PARENT_TABLE_NAME,
               'INL_CHARGE_LINES', ALLOC.TO_PARENT_TABLE_ID,
               NULL)
          CHARGE_LINE_ID,
       DECODE (ALLOC.TO_PARENT_TABLE_NAME,
               'INL_TAX_LINES', ALLOC.TO_PARENT_TABLE_ID,
               NULL)
          TAX_LINE_ID,
       ALLOC.ALLOCATION_ID,
       ALLOC.ALLOCATION_AMT,
       ALLOC.LANDED_COST_FLAG
       --,oph.*
       --,opl.*
       --,assoc.*
       ,alloc.*
  FROM INL_SHIP_HEADERS_ALL OPH,
       INL_SHIP_LINES_ALL OPL,
       INL_ASSOCIATIONS ASSOC,
       INL_ALLOCATIONS ALLOC
 WHERE     OPH.SHIP_HEADER_ID = OPL.SHIP_HEADER_ID
       AND OPH.SHIP_HEADER_ID = ALLOC.SHIP_HEADER_ID
       AND OPL.SHIP_LINE_ID(+) = ALLOC.SHIP_LINE_ID
       AND ASSOC.ASSOCIATION_ID(+) = ALLOC.ASSOCIATION_ID;