/* Formatted on 10/17/2021 10:20:44 AM (QP5 v5.365) */
SELECT *
  FROM GME.GME_BATCH_HEADER GBH
 WHERE 1 = 1 AND GBH.BATCH_NO = :P_BATCH_NO AND ORGANIZATION_ID = 158;


SELECT *
  FROM APPS.GME_BATCH_HEADER GBH, APPS.GME_BATCH_STEPS GBS
 WHERE     1 = 1
       AND GBH.BATCH_ID = GBS.BATCH_ID
       AND GBH.BATCH_NO = :P_BATCH_NO                                 --414587
       AND GBS.BATCHSTEP_ID = 1490025