/* Formatted on 6/23/2021 3:32:27 PM (QP5 v5.287) */
  SELECT 1 SL,
         GCC.SEGMENT5 ACCOUNT,
         (SELECT DESCRIPTION
            FROM FND_FLEX_VALUES_VL A
           WHERE A.FLEX_VALUE_SET_ID = 1017040 AND A.FLEX_VALUE = GCC.SEGMENT5)
            ACCOUNT_NAME,
         NULL EXPENSE_CATEGORY,
         NULL JE_SOURCE,
         NULL GL_DATE,
         NULL UNIT_NAME,
         'Balance B/F' DESCRIPTION,
         NULL MONTH_NAME,
         NULL GL_VOUCHER_NUMBER,
            GCC.SEGMENT6
         || ' - '
         || (SELECT DESCRIPTION
               FROM FND_FLEX_VALUES_VL A
              WHERE     A.FLEX_VALUE_SET_ID = 1017041
                    AND A.FLEX_VALUE = GCC.SEGMENT6
                    AND PARENT_FLEX_VALUE_LOW =
                           (SELECT FLEX_VALUE
                              FROM FND_FLEX_VALUES_VL B
                             WHERE     FLEX_VALUE_SET_ID = 1017040
                                   AND B.FLEX_VALUE = GCC.SEGMENT5))
            AS SUB_ACCOUNT,
         GCC.SEGMENT4 COST_CENTER,
         (SELECT DESCRIPTION
            FROM FND_FLEX_VALUES_VL A
           WHERE A.FLEX_VALUE_SET_ID = 1017032 AND A.FLEX_VALUE = GCC.SEGMENT4)
            CC_DESC,
         BAL.CURRENCY_CODE CURRENCY,
         NULL AMOUNT,
         NULL CONVERSION_RATE,
         NULL DR_AMOUNT,
         NULL CR_AMOUNT,
         SUM (NVL (BEGIN_BALANCE_DR, 0) - NVL (BEGIN_BALANCE_CR, 0))
            BALANCE_BDT,
         NULL JE_CATEGORY,
         (SELECT DESCRIPTION
            FROM FND_FLEX_VALUES_VL A
           WHERE A.FLEX_VALUE_SET_ID = 1017036 AND A.FLEX_VALUE = GCC.SEGMENT7)
            INTER_COM_CODE,
         (SELECT DESCRIPTION
            FROM FND_FLEX_VALUES_VL A
           WHERE A.FLEX_VALUE_SET_ID = 1017038 AND A.FLEX_VALUE = GCC.SEGMENT8)
            CATEGORY,
         NULL PARTY_NAME,
         NULL POSTED_BY,
         NULL REVERSAL_TYPE,
         NULL REVERSE_PERIOD,
         NULL VOUCHER_NUMBER,
         NULL INVOICE_NUM,
         NULL BANK_REFERENCE,
            GCC.SEGMENT1
         || '.'
         || GCC.SEGMENT2
         || '.'
         || GCC.SEGMENT3
         || '.'
         || GCC.SEGMENT4
         || '.'
         || GCC.SEGMENT5
         || '.'
         || GCC.SEGMENT6
         || '.'
         || GCC.SEGMENT7
         || '.'
         || GCC.SEGMENT8
         || '.'
         || GCC.SEGMENT9
            GL_COMBINATION
    FROM GL_BALANCES BAL, GL_CODE_COMBINATIONS GCC     --FND_FLEX_VALUES_VL NA
   WHERE     BAL.CODE_COMBINATION_ID = GCC.CODE_COMBINATION_ID
         AND BAL.ACTUAL_FLAG = 'A'
         AND GCC.SUMMARY_FLAG = 'N'
         AND GCC.TEMPLATE_ID IS NULL
         AND NVL (BAL.TRANSLATED_FLAG, 'X') <> 'R'
         AND BAL.LEDGER_ID = :P_LEDGER_ID
         AND BAL.PERIOD_NAME = :P_PERIOD_FROM
         AND ( :P_LOCATION IS NULL OR GCC.SEGMENT2 = :P_LOCATION)
         AND ( :P_PRODUCT_LINE IS NULL OR GCC.SEGMENT3 = :P_PRODUCT_LINE)
         AND ( :P_COST_CENTER IS NULL OR GCC.SEGMENT4 = :P_COST_CENTER)
         AND ( :P_ACCOUNT_FROM IS NULL OR GCC.SEGMENT5 >= :P_ACCOUNT_FROM)
         AND ( :P_ACCOUNT_TO IS NULL OR GCC.SEGMENT5 <= :P_ACCOUNT_TO)
         AND ( :P_SUB_ACCOUNT IS NULL OR GCC.SEGMENT6 = :P_SUB_ACCOUNT)
         AND ( :P_INTER_COMPANY IS NULL OR GCC.SEGMENT7 = :P_INTER_COMPANY)
         AND (   :P_EXPENSE_CATEGORY IS NULL
              OR GCC.SEGMENT8 <= :P_EXPENSE_CATEGORY)
GROUP BY GCC.SEGMENT1,
         GCC.SEGMENT2,
         GCC.SEGMENT3,
         GCC.SEGMENT6,
         GCC.SEGMENT5,
         GCC.SEGMENT4,
         BAL.CURRENCY_CODE,
         GCC.SEGMENT7,
         GCC.SEGMENT8,
         GCC.SEGMENT9
UNION ALL
SELECT 2 SL,
       ACCOUNT,
       ACCTDESC ACCOUNT_NAME,
       EXPENSE_CATEGORY,
       JE_SOURCE,
       VOUCHER_DATE GL_DATE,
       UNIT_NAME,
       DESCRIPTION,
       TO_CHAR (VOUCHER_DATE, 'MON-YY') MONTH_NAME,
       GL_VOUCHER_NUMBER,
       SUB_ACCOUNT || ' - ' || SUBACCDESC SUB_ACCOUNT,
       COST_CENTER,
       (SELECT DESCRIPTION
          FROM FND_FLEX_VALUES_VL A
         WHERE A.FLEX_VALUE_SET_ID = 1017032 AND A.FLEX_VALUE = COST_CENTER)
          CC_DESC,
       CURRENCY_CODE CURRENCY,
       NVL (ENTERED_DEBITS, 0) - NVL (ENTERED_CREDITS, 0) AMOUNT,
       CONVERSION_RATE,
       NVL (DEBITS, 0) DR_AMOUNT,
       NVL (CREDITS, 0) CR_AMOUNT,
       NVL (DEBITS, 0) - NVL (CREDITS, 0) BALANCE_BDT,
       JE_CATEGORY REFERENCE,
       (SELECT DESCRIPTION
          FROM FND_FLEX_VALUES_VL A
         WHERE A.FLEX_VALUE_SET_ID = 1017036 AND A.FLEX_VALUE = INTER_COMPANY)
          INTER_COM_CODE,
       (SELECT DESCRIPTION
          FROM FND_FLEX_VALUES_VL A
         WHERE     A.FLEX_VALUE_SET_ID = 1017038
               AND A.FLEX_VALUE = EXPENSE_CATEGORY)
          CATEGORY,
       PARTY_NAME,
       CREATED_BY POSTED_BY,
       REVERSAL_TYPE,
       REVERSE_PERIOD,
       VOUCHER_NUMBER,
       CHEQUE_NUMBER INVOICE_NUM,
       (CASE
           WHEN DFF_CONTEXT = 'Merchandise Name' THEN NULL
           ELSE (NVL (ATTRIBUTE1, ATTRIBUTE4))
        END)
          BANK_REFERENCE,
          COMPANY
       || '.'
       || LOCATION
       || '.'
       || PRODUCT_LINE
       || '.'
       || COST_CENTER
       || '.'
       || ACCOUNT
       || '.'
       || SUB_ACCOUNT
       || '.'
       || INTER_COMPANY
       || '.'
       || EXPENSE_CATEGORY
       || '.'
       || FUTURE
          GL_COMBINATION
  FROM XX_GL_DETAILS_STATEMENT_V
 WHERE     LEDGER_ID = :P_LEDGER_ID
       AND VOUCHER_DATE BETWEEN :P_DATE_FROM AND :P_DATE_TO
       AND ( :P_LOCATION IS NULL OR LOCATION = :P_LOCATION)
       AND ( :P_PRODUCT_LINE IS NULL OR PRODUCT_LINE = :P_PRODUCT_LINE)
       AND ( :P_COST_CENTER IS NULL OR COST_CENTER = :P_COST_CENTER)
       AND ( :P_ACCOUNT_FROM IS NULL OR ACCOUNT >= :P_ACCOUNT_FROM)
       AND ( :P_ACCOUNT_TO IS NULL OR ACCOUNT <= :P_ACCOUNT_TO)
       AND ( :P_SUB_ACCOUNT IS NULL OR SUB_ACCOUNT = :P_SUB_ACCOUNT)
       AND ( :P_INTER_COMPANY IS NULL OR INTER_COMPANY = :P_INTER_COMPANY)
       AND (   :P_EXPENSE_CATEGORY IS NULL
            OR EXPENSE_CATEGORY <= :P_EXPENSE_CATEGORY)
       AND ( :P_SOURCE_CODE IS NULL OR JE_SOURCE = :P_SOURCE_CODE)
-- AND VOUCHER_NUMBER IN ('421151827', '421165578')
ORDER BY 1, 6