/* Formatted on 29/Jan/20 2:53:51 PM (QP5 v5.227.12220.39754) */
  SELECT OOD.ORGANIZATION_CODE,
         OOD.ORGANIZATION_NAME,
         MMT.ORGANIZATION_ID,
         MSI.INVENTORY_ITEM_ID ITEM_ID,
         MSI.CONCATENATED_SEGMENTS AS ITEM_CODE,
         MSI.DESCRIPTION AS DESCRIPTION,
         MMT.TRANSACTION_UOM,
         MSI.PRIMARY_UOM_CODE AS P_UOM,
         MMT.SECONDARY_UOM_CODE AS S_UOM,
         MIC.SEGMENT2 AS ITEM_CATG,
         MIC.SEGMENT3 AS ITEM_TYPE,
         MMT.SUBINVENTORY_CODE,
         MTL.ATTRIBUTE1 AS BRAND,
         MTL.LOT_NUMBER,
         SUM (NVL (MTLN.PRIMARY_QUANTITY, MMT.PRIMARY_QUANTITY)) AS ON_HAND
    FROM INV.MTL_MATERIAL_TRANSACTIONS MMT,
         APPS.MTL_SYSTEM_ITEMS_B_KFV MSI,
         APPS.MTL_ITEM_CATEGORIES_V MIC,
         APPS.MTL_TRANSACTION_LOT_NUMBERS MTLN,
         APPS.MTL_LOT_NUMBERS MTL,
         APPS.ORG_ORGANIZATION_DEFINITIONS OOD
   WHERE     MMT.INVENTORY_ITEM_ID = MSI.INVENTORY_ITEM_ID
         AND MMT.ORGANIZATION_ID = MSI.ORGANIZATION_ID
         AND MSI.INVENTORY_ITEM_ID = MIC.INVENTORY_ITEM_ID
         AND MSI.ORGANIZATION_ID = MIC.ORGANIZATION_ID
         AND MMT.TRANSACTION_ID = MTLN.TRANSACTION_ID(+)
         AND MTLN.INVENTORY_ITEM_ID = MTL.INVENTORY_ITEM_ID(+)
         AND MTLN.ORGANIZATION_ID = MTL.ORGANIZATION_ID(+)
         AND MTLN.LOT_NUMBER = MTL.LOT_NUMBER(+)
         AND MMT.ORGANIZATION_ID = OOD.ORGANIZATION_ID
         AND MIC.CATEGORY_SET_ID = 1
         AND MMT.TRANSACTION_TYPE_ID <> 98
         AND MMT.TRANSACTION_ACTION_ID != 24
         AND (MMT.LOGICAL_TRANSACTION = 2 OR MMT.LOGICAL_TRANSACTION IS NULL)
         AND MIC.SEGMENT3 = 'YARN'
         AND MMT.SUBINVENTORY_CODE NOT LIKE 'DYR%'
         AND OOD.ORGANIZATION_CODE IN
                ('113', '133', '143', '152', '163', '183')
         AND MMT.TRANSACTION_DATE <= NVL (:P_DATE_TO, SYSDATE) + .99999
GROUP BY OOD.ORGANIZATION_CODE,
         OOD.ORGANIZATION_NAME,
         MMT.SUBINVENTORY_CODE,
         MMT.ORGANIZATION_ID,
         MSI.INVENTORY_ITEM_ID,
         MSI.CONCATENATED_SEGMENTS,
         MSI.DESCRIPTION,
         MMT.TRANSACTION_UOM,
         MSI.PRIMARY_UOM_CODE,
         MMT.SECONDARY_UOM_CODE,
         MIC.SEGMENT2,
         MIC.SEGMENT3,
         MMT.SUBINVENTORY_CODE,
         MTL.ATTRIBUTE1,
         MTL.LOT_NUMBER
  HAVING SUM (MTLN.PRIMARY_QUANTITY) <> 0
ORDER BY OOD.ORGANIZATION_NAME, MSI.SEGMENT1