/* Formatted on 9/27/2020 11:30:15 AM (QP5 v5.287) */
SELECT 'APPROVED' STSTUS FROM DUAL;

SELECT IOU_NUMBER FROM XXDBL.XXDBL_IOU_REQ_DTL IRD WHERE STATUS = 'APPROVED';


SELECT IOU_NUMBER, IOU_DATE IOU_FROM_DATE, IOU_DATE IOU_TO_DATE
  FROM XXDBL.XXDBL_IOU_REQ_DTL IRD
 WHERE 1 = 1
 AND STATUS IN ('APPROVED','PAID','ADJUSTED');
 
 SELECT
'CREATED' STSTUS
FROM DUAL
UNION ALL
SELECT
'APPROVED' STSTUS
FROM DUAL
UNION ALL
SELECT
'PAID' STSTUS
FROM DUAL
UNION ALL
SELECT
'ADJUSTED' STSTUS
FROM DUAL