/* Formatted on 7/14/2020 9:50:27 AM (QP5 v5.287) */
  SELECT PHA.ORG_ID,
         HOU.NAME,
         OU.LEDGER_NAME,
         OU.LEGAL_ENTITY_NAME,
         MAX (PHA.SEGMENT1) "Last PO Number",
         PHA.AUTHORIZATION_STATUS PO_STATUS,
         MAX (PHA.CREATION_DATE) PO_CREATION_DATE,
         NVL(PPF.EMPLOYEE_NUMBER,PPF.NPW_NUMBER) CREATOR_ID,
         (PPF.FIRST_NAME || ' ' || PPF.MIDDLE_NAMES || ' ' || PPF.LAST_NAME) PO_CREATOR_NAME
    --,PHA.*
    --,PPF.*
    --,OOD.*
    FROM APPS.PO_HEADERS_ALL PHA,
         APPS.HR_OPERATING_UNITS HOU,
         --ORG_ORGANIZATION_DEFINITIONS OOD,
         XXDBL_COMPANY_LE_MAPPING_V OU,
         APPLSYS.FND_USER FU,
         APPS.PER_ALL_PEOPLE_F PPF
   WHERE     1 = 1
         AND HOU.ORGANIZATION_ID = PHA.ORG_ID
         AND HOU.ORGANIZATION_ID = OU.ORG_ID
         AND PHA.CREATED_BY = FU.USER_ID(+)
         AND FU.EMPLOYEE_ID = PPF.PERSON_ID(+)
         --AND FU.USER_NAME = TO_CHAR (PPF.EMPLOYEE_NUMBER)(+)
         --AND PHA.PREPARER_ID = PPF.PERSON_ID(+)
         --AND ( ( :P_ORG_ID IS NULL) OR (PHA.ORG_ID = :P_ORG_ID))
         --AND ( :P_REQ_NO IS NULL OR (PHA.SEGMENT1 = :P_REQ_NO))
         --AND ( ( :P_EMP_ID IS NULL) OR (PPF.EMPLOYEE_NUMBER = :P_EMP_ID))
         AND PHA.AUTHORIZATION_STATUS = 'APPROVED'
GROUP BY PHA.ORG_ID,
         HOU.NAME,
         OU.LEDGER_NAME,
         OU.LEGAL_ENTITY_NAME,
         --PHA.SEGMENT1,
         PHA.AUTHORIZATION_STATUS,
         --PHA.CREATION_DATE,
         (PPF.FIRST_NAME || ' ' || PPF.MIDDLE_NAMES || ' ' || PPF.LAST_NAME),
         NVL(PPF.EMPLOYEE_NUMBER,PPF.NPW_NUMBER);