/* Formatted on 12/23/2020 4:37:35 PM (QP5 v5.287) */
ALTER TABLE XXDBL.XXDBL_MASTER_LC_HEADERS
   ADD (LC_RCV_FRM_BANK_DT DATE, UP_NUMBER VARCHAR2 (100 BYTE), UP_DATE DATE);

CREATE OR REPLACE PUBLIC SYNONYM XXDBL_MASTER_LC_HEADERS FOR XXDBL.XXDBL_MASTER_LC_HEADERS;