ALTER TABLE XXDBL.XXDBL_IOU_REQ_DTL
 DROP PRIMARY KEY CASCADE;

DROP TABLE XXDBL.XXDBL_IOU_REQ_DTL CASCADE CONSTRAINTS;

CREATE TABLE XXDBL.XXDBL_IOU_REQ_DTL
(
  IOU_REQ_ID           NUMBER                   NOT NULL,
  IOU_NUMBER           VARCHAR2(100 BYTE),
  IOU_DATE             DATE,
  LEGAL_ENTITY_ID      NUMBER,
  OPERATING_UNIT       NUMBER,
  OU_NAME              VARCHAR2(240 BYTE),
  LOCATION_ID          NUMBER,
  LOCATION_NAME        VARCHAR2(500 BYTE),
  EMPLOYEE_NO          VARCHAR2(100 BYTE),
  ADVANCE_AMOUNT       NUMBER,
  REASON_FOR_ADVANCE   VARCHAR2(500 BYTE),
  RETURN_DAYS          NUMBER,
  STATUS               VARCHAR2(50 BYTE),
  CREATED_BY           NUMBER,
  CREATION_DATE        DATE,
  LAST_UPDATE_LOGIN    NUMBER,
  LAST_UPDATED_BY      NUMBER,
  LAST_UPDATE_DATE     DATE,
  PAYMENT_AMOUNT       NUMBER,
  PAYMENT_DATE         DATE,
  ADJUST_AMOUNT        NUMBER,
  ADJUST_DATE          DATE,
  LEGAL_ENTITY         VARCHAR2(240 BYTE),
  BILL_AMOUNT          NUMBER,
  APPROVED_BY          VARCHAR2(100 BYTE),
  PAID_BY              VARCHAR2(100 BYTE),
  ADJUSTED_BY          VARCHAR2(100 BYTE),
  FIRST_APPROVER       VARCHAR2(100 BYTE),
  SECOND_APPROVER      VARCHAR2(100 BYTE),
  APPROVED_DATE        DATE,
  FINAL_APPROVER       VARCHAR2(100 BYTE),
  FINAL_APPROVED_DATE  DATE,
  FINAL_APPROVE        VARCHAR2(50 BYTE)
)
TABLESPACE XXDBL_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX XXDBL.IOU_REQ_PK ON XXDBL.XXDBL_IOU_REQ_DTL
(IOU_REQ_ID)
LOGGING
TABLESPACE XXDBL_TS_TX_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE OR REPLACE SYNONYM APPS.XXDBL_IOU_REQ_DTL FOR XXDBL.XXDBL_IOU_REQ_DTL;


CREATE OR REPLACE SYNONYM APPSRO.XXDBL_IOU_REQ_DTL FOR XXDBL.XXDBL_IOU_REQ_DTL;


ALTER TABLE XXDBL.XXDBL_IOU_REQ_DTL ADD (
  CONSTRAINT IOU_REQ_PK
  PRIMARY KEY
  (IOU_REQ_ID)
  USING INDEX XXDBL.IOU_REQ_PK
  ENABLE VALIDATE);

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, READ, DEBUG, FLASHBACK ON XXDBL.XXDBL_IOU_REQ_DTL TO APPS WITH GRANT OPTION;

GRANT INSERT, SELECT, UPDATE ON XXDBL.XXDBL_IOU_REQ_DTL TO APPSDBL;

GRANT SELECT ON XXDBL.XXDBL_IOU_REQ_DTL TO APPSRO;
