/* Formatted on 10/4/2021 3:51:35 PM (QP5 v5.365) */
SELECT * FROM XX_APEX.XXAPEX_PO_GRN_HDR ORDER BY PO_GRN_TRACK_ID DESC;

SELECT * FROM XX_APEX.XXAPEX_PO_GRN_DTL ORDER BY PO_GRN_TRACK_ID DESC;

SELECT * FROM XX_APEX.XXAPEX_ORD_GRN_TRACKING;

--DROP TABLE XX_APEX.XXAPEX_ORD_GRN_TRACK;

--DROP TABLE XX_APEX.XXAPEX_ORD_GRN_TRACKING;

SELECT PHA.SEGMENT1 AS DISPLAY_VALUE, PHA.SEGMENT1 AS RETURN_VALUE
  FROM PO.PO_HEADERS_ALL PHA
 WHERE     PHA.ORG_ID = :P3_UNIT_NAME
       AND NOT EXISTS
               (SELECT 1
                  FROM XX_APEX.XXAPEX_PO_GRN_HDR PGH
                 WHERE PGH.PO_NUMBER = PHA.SEGMENT1);

SELECT PHA.SEGMENT1 AS DISPLAY_VALUE, PHA.SEGMENT1 AS RETURN_VALUE
  FROM PO.PO_HEADERS_ALL PHA
 WHERE PHA.ORG_ID = :P3_UNIT_NAME;

SELECT HOU.NAME AS DISPLAY_VALUE, HOU.ORGANIZATION_ID AS RETURN_VALUE
  FROM APPS.HR_OPERATING_UNITS HOU;

GRANT SELECT ON APPS.HR_OPERATING_UNITS TO XX_APEX;

CREATE OR REPLACE SYNONYM XX_APEX.HR_OPERATING_UNITS FOR APPS.HR_OPERATING_UNITS;

CREATE OR REPLACE SYNONYM XX_APEX.HR_OPERATING_UNITS FOR APPS.HR_OPERATING_UNITS;