/* Formatted on 11/4/2020 12:47:12 PM (QP5 v5.287) */
ALTER TABLE xxdbl.xxdbl_bill_stat_headers
   ADD (corrected_date DATE, correction_version NUMBER);

DROP SYNONYM XXDBL_BILL_STAT_HEADERS;

CREATE OR REPLACE SYNONYM APPS.XXDBL_BILL_STAT_HEADERS FOR XXDBL.XXDBL_BILL_STAT_HEADERS;

CREATE OR REPLACE PUBLIC SYNONYM XXDBL_BILL_STAT_HEADERS FOR XXDBL.XXDBL_BILL_STAT_HEADERS;

Column Name:
Corrected Date CORRECTED_DATE

Correction Version CORRECTION_VERSION

