/* Formatted on 12/29/2020 1:43:48 PM (QP5 v5.287) */
CREATE TABLE XXDBL.XXDBL_IOU_REQ_DTL
(
   IOU_REQ_ID            NUMBER NOT NULL,
   IOU_NUMBER            VARCHAR2 (100 BYTE),
   IOU_DATE              DATE,
   LEGAL_ENTITY_ID       NUMBER,
   LEGAL_ENTITY          VARCHAR2 (240 BYTE),
   OPERATING_UNIT        NUMBER,
   OU_NAME               VARCHAR2 (240 BYTE),
   LOCATION_ID           NUMBER,
   LOCATION_NAME         VARCHAR2 (500 BYTE),
   EMPLOYEE_NO           VARCHAR2 (100 BYTE),
   EMPLOYEE_NAME         VARCHAR2 (500 BYTE),
   ADVANCE_AMOUNT        NUMBER,
   REASON_FOR_ADVANCE    VARCHAR2 (500 BYTE),
   RETURN_DAYS           NUMBER,
   STATUS                VARCHAR2 (50 BYTE),
   FIRST_APPROVER        VARCHAR2 (100 BYTE),
   FST_APPROVER_NAME     VARCHAR2 (500 BYTE),
   SECOND_APPROVER       VARCHAR2 (100 BYTE),
   SND_APPROVER_NAME     VARCHAR2 (500 BYTE),
   CREATED_BY            NUMBER,
   CREATION_DATE         DATE,
   LAST_UPDATE_LOGIN     NUMBER,
   LAST_UPDATED_BY       NUMBER,
   LAST_UPDATE_DATE      DATE,
   APPROVED_BY           VARCHAR2 (100 BYTE),
   APPROVED_DATE         DATE,
   FINAL_APPROVER        VARCHAR2 (100 BYTE),
   FINAL_APPROVED_DATE   DATE,
   PAID_BY               VARCHAR2 (100 BYTE),
   PAYMENT_DATE          DATE,
   ADJUSTED_BY           VARCHAR2 (100 BYTE),
   ADJUST_AMOUNT         NUMBER,
   BILL_AMOUNT           NUMBER,
   ADJUST_DATE           DATE,
   REJECTED_BY           VARCHAR2 (100 BYTE),
   REJECTED_DATE         DATE,
   REJECT_REASON         VARCHAR2 (500 BYTE),
   CONSTRAINT IOU_REQ_PK PRIMARY KEY (IOU_REQ_ID)
);

CREATE OR REPLACE SYNONYM APPS.XXDBL_IOU_REQ_DTL FOR XXDBL.XXDBL_IOU_REQ_DTL;
CREATE OR REPLACE SYNONYM APPSRO.XXDBL_IOU_REQ_DTL FOR XXDBL.XXDBL_IOU_REQ_DTL;
GRANT SELECT ON XXDBL.XXDBL_IOU_REQ_DTL TO APPSRO;