/* Formatted on 12/12/2021 4:08:36 PM (QP5 v5.374) */
SELECT * FROM XX_APEX.XX_APEX_CNF_EXPENSE_LIST;

SELECT * FROM XX_APEX.XX_APEX_CNF_JOB_MASTER;

SELECT * FROM XX_APEX.XX_APEX_CNF_JOB_DETAILS;

SELECT * FROM XX_APEX.XX_APEX_MENU_LIST;

SELECT * FROM XX_APEX.XX_APEX_MENU_MODULE;

SELECT * FROM XX_APEX.XX_APEX_MENU_PERMISSION;