CREATE TABLE XX_APEX.XX_APEX_MENU_MODULE
(
  MENU_MODULE_ID      NUMBER GENERATED ALWAYS AS IDENTITY ( START WITH 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCYCLE CACHE 20 NOORDER NOKEEP NOSCALE) NOT NULL,
  MENU_MODULE_NAME    VARCHAR2(200 BYTE),
  MENU_MODULE_SL_NO   NUMBER,
  MENU_MODULE_STATUS  NUMBER,
  CREATED_BY          VARCHAR2(100 BYTE),
  CREATION_DATE       DATE,
  LAST_UPDATED_BY     VARCHAR2(100 BYTE),
  LAST_UPDATE_DATE    DATE
);


CREATE UNIQUE INDEX XX_APEX.XX_APEX_MENU_MODULE_PK ON XX_APEX.XX_APEX_MENU_MODULE
(MENU_MODULE_ID);

ALTER TABLE XX_APEX.XX_APEX_MENU_MODULE ADD (
  CONSTRAINT XX_APEX_MENU_MODULE_PK
  PRIMARY KEY
  (MENU_MODULE_ID)
  USING INDEX XX_APEX.XX_APEX_MENU_MODULE_PK
  ENABLE VALIDATE);


CREATE OR REPLACE PUBLIC SYNONYM XX_APEX_MENU_MODULE FOR XX_APEX.XX_APEX_MENU_MODULE;


GRANT DELETE, INSERT, SELECT, UPDATE ON XX_APEX.XX_APEX_MENU_MODULE TO APPSRO;
