/* Formatted on 1/26/2022 5:25:01 PM (QP5 v5.374) */
SELECT * FROM XX_APEX.XXAPEX_PO_GRN_HDR;

ALTER TABLE XX_APEX.XXAPEX_PO_GRN_HDR
    ADD (LC_NUMBER VARCHAR2 (30),
         LC_OPENING_DATE DATE,
         PI_NUMBER VARCHAR2 (30));