/* Formatted on 3/15/2020 4:04:43 PM (QP5 v5.287) */
CREATE TABLE W_XX_AR_BILLS_LINE_DETAILS_ALL
(
   BILL_LINE_DETAIL_ID NUMBER,
   INVENTORY_ITEM_ID NUMBER,
   ITEM_CODE VARCHAR2(50 BYTE),
   ITEM_DESCRIPTION VARCHAR2(240 BYTE),
   UOM VARCHAR2(3 BYTE),
   FINISHING_WEIGHT NUMBER,
   GREY_WEIGHT NUMBER,
   UNIT_SELLING_PRICE NUMBER,
   TOTAL_PRICE NUMBER,
   REMARKS VARCHAR2(240 BYTE),
   FABRIC_TYPE VARCHAR2(30 BYTE),
   DISCOUNT NUMBER,
   ORDER_NUMBER  VARCHAR2(30 BYTE),
   BUYER_NAME VARCHAR2(360 BYTE),
   BUYER_ID NUMBER,
   BUYER_NUMBER NUMBER,
   PI_NUMBER  VARCHAR2(80 BYTE),
   PI_DATE  VARCHAR2(30 BYTE),
   PO_HEADER_ID NUMBER,
   PO_NUMBER  VARCHAR2(50 BYTE)
);


ALTER TABLE W_XX_AR_BILLS_LINE_DETAILS_ALL 
ADD (
  BILL_LINE_ID NUMBER
);