CREATE TABLE W_XX_AR_BILLS_LINES_ALL
(
  BILL_LINE_ID        NUMBER(15),
  CREATED_BY          NUMBER(15),
  CREATION_DATE       DATE,
  LAST_UPDATE_DATE    DATE,
  LAST_UPDATE_LOGIN   NUMBER(15),
  LAST_UPDATED_BY     NUMBER(15),
  CHALLAN_DATE        DATE,
  BILL_HEADER_ID      NUMBER(15),
  CHALLAN_TYPE        VARCHAR2(50 BYTE),
  MOV_HEADER_ID       NUMBER,
  APPLY_FLAG          VARCHAR2(1 BYTE),
  CHALLAN_NUMBER      VARCHAR2(50 BYTE),
  DELIVERY_BY         VARCHAR2(100 BYTE),
  LOT                 VARCHAR2(80 BYTE),
  TRANSACTION_TYPE    VARCHAR2(500 BYTE),
  BILL_CATEGORY_NAME  VARCHAR2(500 BYTE),
  CHALLAN_QTY         NUMBER
)