SELECT
ABH.OPERATING_UNIT OU,
ABH.CUSTOMER_NAME,
ABH.BILL_NUMBER,
ABH.BILL_DATE,
ABH.BILL_CURRENCY,
ABH.EXCHANCE_RATE,
ABH.BILL_CATEGORY,
ABH.BILL_STATUS,
ABH.CUSTOMER_TYPE,
ABL.CHALLAN_DATE,
ABL.CHALLAN_TYPE,
ABL.CHALLAN_NUMBER,
--ABL.CHALLAN_QTY,
ABD.ITEM_CODE,
ABD.ITEM_DESCRIPTION,
XYTD.YRN_TYPE,
ABD.UOM,
ABD.PI_NUMBER,
ABD.FINISHING_WEIGHT,
ABD.UNIT_SELLING_PRICE,
ROUND(ABD.UNIT_SELLING_PRICE * NVL(ABH.EXCHANCE_RATE,1),2) UNIT_SELLING_PRICE_BDT,
ROUND((ABD.FINISHING_WEIGHT * ABD.UNIT_SELLING_PRICE),2) "USD AMOUNT",
ROUND((ABD.FINISHING_WEIGHT * ABD.UNIT_SELLING_PRICE) * NVL(ABH.EXCHANCE_RATE,1),2) "BDT AMOUNT"
FROM XX_AR_BILLS_HEADERS_ALL ABH,
XX_AR_BILLS_LINES_ALL ABL,
XX_AR_BILLS_LINE_DETAILS_ALL ABD,
XXDBL.XXDBL_YRN_TYPE_DATA XYTD
WHERE ABH.BILL_HEADER_ID = ABL.BILL_HEADER_ID
AND ABL.BILL_LINE_ID = ABD.BILL_LINE_ID
AND ABD.ITEM_CODE= XYTD.ITEM_CODE (+)
--AND ABH.BILL_NUMBER like 'MSML/5220'
AND TRUNC  (ABL.CHALLAN_DATE) between '01/Jan/2020' and '31/May/2020'
AND ABH.OPERATING_UNIT like 'MSML'
--AND ABH.CUSTOMER_TYPE like 'Internal'
--AND ABH.BILL_CATEGORY like 'Yarn Export'
--AND XYTD.YRN_TYPE like 'Carded '
--AND ABL.CHALLAN_NUMBER like 'MSML/12972'
--AND ABL.BILL_LINE_ID = 28295
--AND ABH.BILL_CURRENCY like 'BDT'