/* Formatted on 5/20/2021 10:45:18 AM (QP5 v5.287) */
SELECT * FROM HZ_PARTIES;

select count(*) from HZ_PARTIES
where created_by_module is NULL;

CREATE TABLE HZ_PARTIES_20521
AS
   (SELECT *
      FROM HZ_PARTIES);


UPDATE HZ_PARTIES
   SET CREATED_BY_MODULE = 'TCA_FORM_WRAPPER'
 WHERE CREATED_BY_MODULE IS NULL;