SELECT ODD.ORGANIZATION_NAME,
         CLM.PERIOD_DESC,
         MSI.CONCATENATED_SEGMENTS ITEM_CODE,
         MSI.DESCRIPTION,
         MSI.PRIMARY_UOM_CODE,
         MIC.SEGMENT2 AS ITEM_CATEGORY,
         MIC.SEGMENT3 AS ITEM_TYPE,
         ODD.ORGANIZATION_ID,
         ODD.ORGANIZATION_CODE,
         CLM.LEGAL_ENTITY_ID,
         --CLM.PERIOD_ID,
         -- CM.CMPNT_GROUP,
         SUM (CD.CMPNT_COST) ITEM_COST
    FROM APPS.CM_CMPT_MST CM,
         APPS.CM_CMPT_DTL CD,
         APPS.MTL_SYSTEM_ITEMS_KFV MSI,
         APPS.CM_CLDR_MST_V CLM,
         APPS.MTL_ITEM_CATEGORIES_V MIC,
         APPS.ORG_ORGANIZATION_DEFINITIONS ODD
   WHERE     CD.PERIOD_ID = CLM.PERIOD_ID
         AND CM.COST_CMPNTCLS_ID = CD.COST_CMPNTCLS_ID
         AND CD.ORGANIZATION_ID = ODD.ORGANIZATION_ID
         AND CD.INVENTORY_ITEM_ID = MSI.INVENTORY_ITEM_ID
         AND CD.ORGANIZATION_ID = MSI.ORGANIZATION_ID
         AND MSI.ORGANIZATION_ID = MIC.ORGANIZATION_ID
         AND MSI.INVENTORY_ITEM_ID = MIC.INVENTORY_ITEM_ID
         AND CLM.LEGAL_ENTITY_ID = :P_LEGAL_ENTITY_ID
         AND MIC.CATEGORY_SET_ID = 1
         AND CLM.PERIOD_DESC = :P_PERIOD_DESC
         AND (:P_ORGANIZATION_ID IS NULL
              OR CD.ORGANIZATION_ID = :P_ORGANIZATION_ID)
GROUP BY ODD.ORGANIZATION_NAME,
         CLM.PERIOD_DESC,
         MSI.CONCATENATED_SEGMENTS,
         MSI.DESCRIPTION,
         MSI.PRIMARY_UOM_CODE,
         MIC.SEGMENT2,
         MIC.SEGMENT3,
         ODD.ORGANIZATION_ID,
         ODD.ORGANIZATION_CODE,
         CLM.LEGAL_ENTITY_ID
ORDER BY MSI.CONCATENATED_SEGMENTS