SELECT
PROGRAM,
REQUESTOR,
RESPONSIBILITY_NAME
,REQ.REQUEST_DATE
--,FRT.*
FROM
APPS.FND_CONC_REQ_SUMMARY_V REQ ,
APPS.FND_RESPONSIBILITY_VL FRT
WHERE 1=1
AND REQ.RESPONSIBILITY_ID=FRT.RESPONSIBILITY_ID
AND TO_CHAR(REQ.REQUEST_DATE,'YYYY/MON/DD HH24:MI:SS') BETWEEN '2020/MAR/21 13:00:00' AND '2020/MAR/21 16:14:00'--HH:MI:SS--12:00:00
--AND REQUESTOR='8217'
--AND TO_CHAR(REQ.REQUEST_DATE,'DD-MON-RR')='30-OCT-19'
--AND REQ.REQUEST_ID=52190214


SELECT
FCPT.USER_CONCURRENT_PROGRAM_NAME,
FCR.REQUESTED_BY,
FU.USER_NAME
--FCPT.*
,FCR.*
FROM
APPS.FND_CONCURRENT_REQUESTS FCR,
APPS.FND_CONCURRENT_PROGRAMS FCP,
APPS.FND_CONCURRENT_PROGRAMS_VL FCPT,
APPS.FND_USER FU
WHERE 1=1
--AND REQUEST_ID=52190214
AND FCR.CONCURRENT_PROGRAM_ID=FCP.CONCURRENT_PROGRAM_ID
AND FCR.PROGRAM_APPLICATION_ID=FCP.APPLICATION_ID
AND FCR.CONCURRENT_PROGRAM_ID=FCPT.CONCURRENT_PROGRAM_ID
AND FCR.PROGRAM_APPLICATION_ID=FCPT.APPLICATION_ID
AND FU.USER_ID=FCR.REQUESTED_BY
--AND FCR.ACTUAL_START_DATE IS NOT NULL
AND FCPT.USER_CONCURRENT_PROGRAM_NAME='SCIL TO Advice'
--AND ARGUMENT2='DO/SCOU/965804'
ORDER BY REQUEST_ID DESC


SELECT
*
FROM
APPS.FND_CONCURRENT_PROGRAMS_TL