/* Formatted on 11/7/2020 4:29:35 PM (QP5 v5.354) */
SELECT * FROM APPS.PER_GB_XDO_TEMPLATES;


SELECT * FROM APPS.XDO_DS_DEFINITIONS_B;


SELECT * FROM APPS.XDO_DS_DEFINITIONS_TL;

SELECT * FROM APPS.XDO_DS_DEFINITIONS_VL;

SELECT * FROM APPS.XDO_LOBS;


SELECT * FROM APPS.XDO_TEMPLATES_B;

SELECT * FROM APPS.XDO_TEMPLATES_TL;


SELECT * FROM APPS.XDO_TEMPLATES_VL;


SELECT * FROM APPS.XDO_TEMPLATE_FIELDS;


SELECT * FROM APPS.XDO_TRANS_UNITS;


SELECT * FROM APPS.XDO_TRANS_UNIT_PROPS;


SELECT * FROM APPS.XDO_TRANS_UNIT_VALUES;