/* Formatted on 12/22/2020 12:14:41 PM (QP5 v5.287) */
ALTER TABLE XXDBL.XXDBL_MASTER_LC_HEADERS
   ADD (MPI_NUMBER VARCHAR2 (100 BYTE),
        LC_RCV_DATE DATE,
        LC_TYPE VARCHAR2 (100 BYTE),
        CH_REQ_DATE DATE,
        EXP_NO VARCHAR2 (100 BYTE),
        EXP_DT DATE,
        EXP_EXPIRE_DATE DATE,
        UD_IP_NO VARCHAR2 (100 BYTE),
        UD_IP_RCV_DT DATE,
        UD_IP_HND_OVR_DT DATE,
        UD_IP_ISSUE_DT DATE,
        UD_IP_EXP_DT DATE,
        BILL_ENTRY_NO VARCHAR2 (100 BYTE),
        BILL_ENTRY_DT DATE,
        INFO_REMARKS VARCHAR2 (500 BYTE));
        
CREATE OR REPLACE PUBLIC SYNONYM XXDBL_MASTER_LC_HEADERS FOR XXDBL.XXDBL_MASTER_LC_HEADERS;

ALTER TABLE XXDBL.XXDBL_MASTER_LC_HEADERS
   ADD (UD_ISSUE_DT DATE);