/* Formatted on 12/22/2020 12:59:19 PM (QP5 v5.287) */
SELECT FFV.DESCRIPTION VALUE_DESCRIPTION
  FROM APPS.FND_FLEX_VALUE_SETS FFVS, APPS.FND_FLEX_VALUES_VL FFV
 WHERE     1 = 1
       AND FFVS.FLEX_VALUE_SET_ID = FFV.FLEX_VALUE_SET_ID
       AND FFVS.FLEX_VALUE_SET_NAME = 'XXDBL_CCL2_DBTR_LC_TYPE'
       AND FFV.ENABLED_FLAG='Y'