select
*
from
XX_LOAN_INTEREST_DTL_INFO
order by creation_date desc;

ALTER TABLE XXDBL.XX_LOAN_INTEREST_DTL_INFO 
ADD (
  LOAN_TRX_TYPE VARCHAR2(50)
);

DROP SYNONYM XX_LOAN_INTEREST_DTL_INFO;


CREATE OR REPLACE SYNONYM APPS.XX_LOAN_INTEREST_DTL_INFO FOR XXDBL.XX_LOAN_INTEREST_DTL_INFO#;




CREATE OR REPLACE SYNONYM APPS.XX_LOAN_INTEREST_DTL_INFO# FOR XXDBL.XX_LOAN_INTEREST_DTL_INFO#;


CREATE OR REPLACE SYNONYM APPSRO.XX_LOAN_INTEREST_DTL_INFO# FOR XXDBL.XX_LOAN_INTEREST_DTL_INFO#;


GRANT SELECT ON XXDBL.XX_LOAN_INTEREST_DTL_INFO# TO APPS WITH GRANT OPTION;

GRANT SELECT ON XXDBL.XX_LOAN_INTEREST_DTL_INFO# TO APPSRO;


---

CREATE OR REPLACE SYNONYM APPS.XX_LOAN_INTEREST_DTL_INFO FOR XXDBL.XX_LOAN_INTEREST_DTL_INFO;


CREATE OR REPLACE SYNONYM APPS.XX_LOAN_INTEREST_DTL_INFO FOR XXDBL.XX_LOAN_INTEREST_DTL_INFO;


CREATE OR REPLACE SYNONYM APPSRO.XX_LOAN_INTEREST_DTL_INFO# FOR XXDBL.XX_LOAN_INTEREST_DTL_INFO#;


-----------

select
*
from
fnd_flex_values_vl
where 1=1
and FLEX_VALUE='Take Over';

select
*
from
APPS.FND_FLEX_VALUE_SETS VAL_SET
where 1=1
and FLEX_VALUE_SET_NAME='Loan Transaction Type';

/* Formatted on 8/24/2020 11:13:28 AM (QP5 v5.287) */
SELECT FFV.FLEX_VALUE, FFV.DESCRIPTION
  FROM APPS.FND_FLEX_VALUE_SETS VAL_SET, FND_FLEX_VALUES_VL FFV
 WHERE     VAL_SET.FLEX_VALUE_SET_ID = FFV.FLEX_VALUE_SET_ID
       AND VAL_SET.FLEX_VALUE_SET_NAME = 'Loan Transaction Type';
