

CREATE TABLE XXDBL.XXDBL_VEHICLE_WEBADI_UPD_TMP
(
   M_SL_NO                   NUMBER  GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1)   NOT NULL,
   M_VMS_BILL_ID             NUMBER,
   M_BILL_DATE               DATE,
   M_BLL_NO                  VARCHAR2 (50 BYTE),
   M_DESC_WORK               VARCHAR2 (500 BYTE),
   M_CURRENT_KM              NUMBER,
   M_NEXT_KM                 NUMBER,
   M_REMARKS                 VARCHAR2 (2000 BYTE),
   M_CREATED_BY              NUMBER,
   M_CREATION_DATE           DATE,
   M_ORG_ID                  NUMBER,
   M_VANDOR_NAME             VARCHAR2 (400 BYTE),
   M_PURCH_OU                VARCHAR2 (100 BYTE),
   M_MAINTAINCE_TYPE         VARCHAR2 (130 BYTE),
   M_VOUCHER_NO              VARCHAR2 (50 BYTE),
   M_LEGAL_ENTITY_ID         NUMBER,
   M_LEGAL_ENTITY_NAME       VARCHAR2 (200 BYTE),
   M_LEDGER_ID               NUMBER,
   M_CHART_OF_ACCOUNTS_ID    NUMBER,
   M_LEDGER_NAME             VARCHAR2 (200 BYTE),
   M_VENDOR_ID               NUMBER,
   M_VENDOR_SITE_ID          NUMBER,
   M_INVOICE_AMOUNT          NUMBER,
   M_VOUCHER_NUMBER          NUMBER,
   M_ALTERNATE_VENDOR        VARCHAR2 (200 BYTE),
   M_BILL_STATUS             VARCHAR2 (50 BYTE),
   D_BILL_ITEM_TYPE          VARCHAR2 (30 BYTE),
   D_ITEM_DTL                VARCHAR2 (2000 BYTE),
   D_BILL_AMOUNT             NUMBER (10),
   D_REMARKS                 VARCHAR2 (500 BYTE),
   D_ITEM_QTY                NUMBER,
   D_UNIT_PRICE              NUMBER (30),
   D_DISCOUNT_AMOUNT         NUMBER (30),
   D_DISCOUNT_AMT_PERTENGE   NUMBER,
   D_DR_CODE_COMB            VARCHAR2 (500 BYTE),
   D_DR_CCID                 NUMBER,
   D_VEHICLE_NUMBER          VARCHAR2 (100 BYTE),
   D_PR_NUMBER               VARCHAR2 (512 BYTE),
   D_VAT_PRCT                NUMBER,
   D_VAT_AMNT                NUMBER,
   M_ERROR_CODE              VARCHAR2 (2 BYTE),
   M_ERROR_MESSAGE           VARCHAR2 (3000 BYTE),
   CONSTRAINT VEHICLE_WEBADI_UPD_pk PRIMARY KEY (M_SL_NO)
)


CREATE OR REPLACE SYNONYM APPSRO.XXDBL_VEHICLE_WEBADI_UPD_TMP FOR XXDBL.XXDBL_VEHICLE_WEBADI_UPD_TMP;


CREATE OR REPLACE SYNONYM APPS.XXDBL_VEHICLE_WEBADI_UPD_TMP FOR XXDBL.XXDBL_VEHICLE_WEBADI_UPD_TMP;

