/* Formatted on 1/3/2022 4:31:34 PM (QP5 v5.374) */
XXDBL_BILL_REC_HEADER
XX_LOAN_INTEREST_DTL_INFO
XX_VMS_BILL_DTL
XX_VMS_BILL_MST

CREATE TABLE XXDBL.XXDBL_BILL_REC_HEADER_030122
AS
    SELECT * FROM XXDBL.XXDBL_BILL_REC_HEADER;

CREATE TABLE XXDBL.XX_LOAN_INTEREST_DTL_INFO_3122
AS
    SELECT * FROM XXDBL.XX_LOAN_INTEREST_DTL_INFO;

CREATE TABLE XXDBL.XX_VMS_BILL_DTL_030122
AS
    SELECT * FROM XXDBL.XX_VMS_BILL_DTL;

CREATE TABLE XXDBL.XX_VMS_BILL_MST_030122
AS
    SELECT * FROM XXDBL.XX_VMS_BILL_MST;


--------------------------------------------------------------------------------
SELECT * FROM XXDBL.XXDBL_BILL_REC_HEADER;

SELECT * FROM XXDBL.XX_LOAN_INTEREST_DTL_INFO;

SELECT * FROM XXDBL.XX_VMS_BILL_DTL;

SELECT * FROM XXDBL.XX_VMS_BILL_MST;

--------------------------------------------------------------------------------

SELECT * FROM XXDBL.XXDBL_BILL_REC_HEADER_030122;

SELECT * FROM XXDBL.XX_LOAN_INTEREST_DTL_INFO_3122;

SELECT * FROM XXDBL.XX_VMS_BILL_DTL_030122;

SELECT * FROM XXDBL.XX_VMS_BILL_MST_030122; 
