DROP TABLE XXDBL.XX_VMS_BILL_DTL CASCADE CONSTRAINTS;

CREATE TABLE XXDBL.XX_VMS_BILL_DTL
(
  VMS_BILL_ID            NUMBER,
  COMPONENTS_NAME        VARCHAR2(150 BYTE),
  BILL_ITEM_TYPE         VARCHAR2(30 BYTE),
  ITEM_DTL               VARCHAR2(2000 BYTE),
  BILL_AMOUNT            NUMBER(10),
  REMARKS                VARCHAR2(500 BYTE),
  CREATED_BY             NUMBER,
  CREATION_DATE          DATE,
  LAST_UPDATE_DATE       DATE,
  LAST_UPDATED_BY        NUMBER,
  LAST_UPDATED_LOGIN     NUMBER,
  ITEM_QTY               NUMBER,
  UNIT_PRICE             NUMBER(30),
  DISCOUNT_AMOUNT        NUMBER(30),
  DISCOUNT_AMT_PERTENGE  NUMBER,
  DR_CODE_COMB           VARCHAR2(500 BYTE),
  DR_CCID                NUMBER,
  PROV_REQUIRED_FLAG     VARCHAR2(1 BYTE),
  SL                     NUMBER,
  VEHICLE_NUMBER         VARCHAR2(100 BYTE),
  PR_NUMBER              VARCHAR2(512 BYTE),
  VAT_PRCT               NUMBER,
  VAT_AMNT               NUMBER
)
TABLESPACE XXDBL_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE OR REPLACE SYNONYM APPS.XX_VMS_BILL_DTL FOR XXDBL.XX_VMS_BILL_DTL;


CREATE OR REPLACE SYNONYM APPSRO.XX_VMS_BILL_DTL FOR XXDBL.XX_VMS_BILL_DTL;


GRANT SELECT ON XXDBL.XX_VMS_BILL_DTL TO APPSRO;
