DROP TABLE XXDBL.XX_VMS_BILL_MST CASCADE CONSTRAINTS;

CREATE TABLE XXDBL.XX_VMS_BILL_MST
(
  VMS_BILL_ID           NUMBER,
  VMST_ID               NUMBER,
  BILL_DATE             DATE,
  VANDOR_ID             VARCHAR2(500 BYTE),
  BLL_NO                VARCHAR2(50 BYTE),
  MAINTAINCE_TYPE_ID    VARCHAR2(150 BYTE),
  DESC_WORK             VARCHAR2(500 BYTE),
  CURRENT_KM            NUMBER,
  NEXT_KM               NUMBER,
  REMARKS               VARCHAR2(2000 BYTE),
  CREATED_BY            NUMBER,
  CREATION_DATE         DATE,
  LAST_UPDATE_DATE      DATE,
  LAST_UPDATED_BY       NUMBER,
  LAST_UPDATED_LOGIN    NUMBER,
  ORG_ID                NUMBER,
  VANDOR_NAME           VARCHAR2(400 BYTE),
  V_REG_NO              VARCHAR2(400 BYTE),
  PURCH_OU              VARCHAR2(100 BYTE),
  MAINTAINCE_TYPE       VARCHAR2(130 BYTE),
  VOUCHER_NO            VARCHAR2(50 BYTE),
  TAX_AMT               NUMBER,
  TAX_PER               NUMBER,
  LEGAL_ENTITY_ID       NUMBER,
  LEGAL_ENTITY_NAME     VARCHAR2(200 BYTE),
  LEDGER_ID             NUMBER,
  CHART_OF_ACCOUNTS_ID  NUMBER,
  LEDGER_NAME           VARCHAR2(200 BYTE),
  VENDOR_ID             NUMBER,
  VENDOR_SITE_ID        NUMBER,
  INVOICE_AMOUNT        NUMBER,
  DOC_SEQUENCE_VALUE    NUMBER,
  VOUCHER_NUMBER        NUMBER,
  ALTERNATE_VENDOR      VARCHAR2(200 BYTE),
  BILL_STATUS           VARCHAR2(50 BYTE)
)
TABLESPACE XXDBL_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE OR REPLACE SYNONYM APPS.XX_VMS_BILL_MST FOR XXDBL.XX_VMS_BILL_MST;


CREATE OR REPLACE SYNONYM APPSRO.XX_VMS_BILL_MST FOR XXDBL.XX_VMS_BILL_MST;


GRANT SELECT ON XXDBL.XX_VMS_BILL_MST TO APPSRO;
