DROP TABLE XXDBL.XXDBL_BILL_REC_HEADER CASCADE CONSTRAINTS;

CREATE TABLE XXDBL.XXDBL_BILL_REC_HEADER
(
  HEADER_ID           NUMBER                    NOT NULL,
  CREATED_BY          NUMBER,
  CREATION_DATE       DATE,
  LAST_UPDATED_BY     NUMBER,
  LAST_UPDATE_DATE    DATE,
  LAST_UPDATE_LOGIN   NUMBER,
  ORG_ID              NUMBER,
  OPERATING_UNIT      VARCHAR2(240 BYTE),
  TRX_SOURCE_ID       NUMBER,
  TRX_SOURCE_NAME     VARCHAR2(50 BYTE),
  TRX_TYPE_ID         NUMBER,
  TRX_TYPE_NAME       VARCHAR2(20 BYTE),
  CURRENCY_CODE       VARCHAR2(10 BYTE),
  ISSUE_DATE          DATE,
  GL_DATE             DATE,
  MATURITY_DATE       DATE,
  STATUS              VARCHAR2(30 BYTE),
  BR_BANK_REFERENCE   VARCHAR2(30 BYTE),
  BANK_PARTY_ID       NUMBER,
  BANK_NAME           VARCHAR2(360 BYTE),
  LOAN_AMOUNT         NUMBER,
  OPENING_DATE        DATE,
  NO_OF_BR            NUMBER,
  CUST_ACCOUNT_ID     NUMBER,
  CUST_PARTY_ID       NUMBER,
  CUSTOMER_NAME       VARCHAR2(240 BYTE),
  CUSTOMER_NUMBER     VARCHAR2(30 BYTE),
  CUST_ACCT_SITE_ID   NUMBER,
  PARTY_SITE_ID       NUMBER,
  LOCATION_ID         NUMBER,
  SITE_USE_ID         NUMBER,
  SITE_NAME           VARCHAR2(240 BYTE),
  SITE_ADDRESS        VARCHAR2(4000 BYTE),
  BR_CONTROL_AMOUNT   NUMBER,
  COMM_INV_NUMBER     VARCHAR2(240 BYTE),
  COMM_INV_HEADER_ID  NUMBER,
  LC_NUMBER           VARCHAR2(50 BYTE)
)
TABLESPACE XXDBL_TS_TX_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE OR REPLACE SYNONYM APPS.XXDBL_BILL_REC_HEADER FOR XXDBL.XXDBL_BILL_REC_HEADER;


CREATE OR REPLACE SYNONYM APPSRO.XXDBL_BILL_REC_HEADER FOR XXDBL.XXDBL_BILL_REC_HEADER;


GRANT SELECT ON XXDBL.XXDBL_BILL_REC_HEADER TO APPSRO;
