SELECT
FDFT.TITLE, FDFCU.*,
FDF.*
FROM
APPS.FND_DESCRIPTIVE_FLEXS FDF,
APPS.FND_DESCRIPTIVE_FLEXS_TL FDFT,
 APPS.FND_DESCR_FLEX_COLUMN_USAGES FDFCU
WHERE 
FDF.APPLICATION_TABLE_NAME = NVL(UPPER(:P_TABLE_NAME),FDF.APPLICATION_TABLE_NAME)
AND    FDF.DESCRIPTIVE_FLEXFIELD_NAME = FDFCU.DESCRIPTIVE_FLEXFIELD_NAME
AND    FDF.DESCRIPTIVE_FLEXFIELD_NAME = FDFT.DESCRIPTIVE_FLEXFIELD_NAME
AND    UPPER(FDFT.TITLE) = NVL(UPPER(:P_TITLE),UPPER(FDFT.TITLE))
ORDER BY 5